### ISSUE TITLE
Feature request: Allow column selection for `types` with regex

### ISSUE THREAD

**Issue by AriHuttunen** [JuliaData/CSV.jl#1014]
DataFrames.jl allows column selection using a regex like `r”a”`.

As a DataFrames.jl user I would like to be able to select columns also in CSV.jl using a regex, so it is convenient for me to move the column type selection to CSV reading.

Example:
```
DataFrame(CSV.File("train.csv"); types=Dict(r"tude$" => Float32))
```

**Comment by nickrobinson251** [comment]
i agree this syntax could be nice. in the meantime, i think something like this is possible by passing a function 
```julia
CSV.File(file; types=(num, name) -> !isnothing(match(r"tude$", string(name))) ? Float32 : nothing)
```

**Comment by AriHuttunen** [comment]
I took a look at the tests, and wonder what happens if you map a column to different data types?

```
DataFrame(CSV.File("train.csv"); types=Dict(r"tude$" => Float32, :Magnitude => Int))
```

**Comment by nickrobinson251** [comment]
> I took a look at the tests, and wonder what happens if you map a column to different data types?
> 
> ```
> DataFrame(CSV.File("train.csv"); types=Dict(r"tude$" => Float32, :Magnitude => Int))
> ```

in #1015 `Regex` has lowest precedence, i.e. if the `Dict` contains the column name (or column number) exactly then that will be used e.g.
```julia
julia> data = IOBuffer("a_col,b_col,c,d\n1,2,3.14,hey\n4,2,6.5,hey\n");

julia> f = CSV.File(data; types=Dict(r"_col$" => Int16, :a_col => Int8));

julia> eltype(f.a_col)
Int8

julia> eltype(f.b_col)
Int16
```

If multiple `Regex`es match, then the "first" match will be used... so if using a `Dict` (which is unordered) then that's kinda undefined (although as i say whichever ends up first will be used). You could use an `OrderedDict` if you did want multiple `Regex`es (putting the higher precedence or "more specific" ones first or whatever)
