### ISSUE TITLE
default date format doesn't display time of day

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/CSV.jl#104]
The default date format that is set is `Dates.ISODateFormat` which is `"yyyy-mm-dd"`.  This should be `Dates.ISODateTimeFormat` which is `"yyyy-mm-ddTHH:MM:SS.s"`.  Alternatively perhaps this should be set depending on whether a `Date` or `DateTime` is being displayed.

**Comment by quinnj** [comment]
I'm not sure what you mean by "the default date format is set to `Dates.ISODateFormat`."
On master, the current behavior is this:
- Try to detect a Date type by trying `Date(field, Dates.ISODateFormat)`
- if that fails, try to detect DateTime type by trying `DateTime(field, Dates.ISODateTimeFormat)`

If the user provides a DateFormat, it detects whether that DateFormat includes time-parts or not and will use Date or DateTime appropriately.

Can you post a more specific example of what you're seeing?

**Comment by ExpandingMan** [comment]
Yeah, sorry I didn't look very deep into the source code.

I have a dataframe with `DateTime` fields that get printed with only `"yyyy-mm-dd"`.  Passing the `dateformat` argument works as intended however.
