### ISSUE TITLE
CSV.File for particular file works on v0.10.4 crashes on v0.10.5

### ISSUE THREAD

**Issue by jordancluts** [JuliaData/CSV.jl#1041]
with v0.10.4 running `CSV.File("brokenfile.txt",header=9)` works appropriately. On v0.10.5 it crashes the process. I don't have time today to trim down the file to find what feature is causing the problem but may have a chance in a week or two. In the meantime I have attached the (unfortunately moderately sized) file.
[brokenfile.txt](https://github.com/JuliaData/CSV.jl/files/9842103/brokenfile.txt)

**Comment by quinnj** [comment]
Hmmm, I don't see any crash on apple m1 with Julia 1.8.1. Can you share your platform + Julia version?

**Comment by jordancluts** [comment]
Julia v"1.7.3" (sorry didn't occur to me that I am a bit behind there. My job hasn't needed much coding the last few months)
Windows 10 on an Intel Core-i7

**Comment by quinnj** [comment]
Can you post the full crash you're seeing? Usually that can help us know if there's something in CSV.jl going wrong, or a more general Julia issue (that may have been fixed since 1.7.3).

**Comment by jordancluts** [comment]
```
julia> CSV.File("brokenfile.txt",header=9)

[process exited with code 3221225477 (0xc0000005)]
```

**Comment by jordancluts** [comment]
I first had this happen in Pluto. Figured I would post the REPL output when the Pluto process crashes on the off-chance it is helpful.

```
Worker 3 terminated.
Unhandled Task ERROR: IOError: read: connection reset by peer (ECONNRESET)
Stacktrace:
  [1] wait_readnb(x::Sockets.TCPSocket, nb::Int64)
    @ Base .\stream.jl:408
  [2] (::Base.var"#wait_locked#648")(s::Sockets.TCPSocket, buf::IOBuffer, nb::Int64)
    @ Base .\stream.jl:894
  [3] unsafe_read(s::Sockets.TCPSocket, p::Ptr{UInt8}, nb::UInt64)
    @ Base .\stream.jl:900
  [4] unsafe_read
    @ .\io.jl:724 [inlined]
  [5] unsafe_read(s::Sockets.TCPSocket, p::Base.RefValue{NTuple{4, Int64}}, n::Int64)
    @ Base .\io.jl:723
  [6] read!
    @ .\io.jl:725 [inlined]
  [7] deserialize_hdr_raw
    @ C:\Users\jcluts\scoop\apps\julia\current\share\julia\stdlib\v1.7\Distributed\src\messages.jl:167 [inlined]
  [8] message_handler_loop(r_stream::Sockets.TCPSocket, w_stream::Sockets.TCPSocket, incoming::Bool)
    @ Distributed C:\Users\jcluts\scoop\apps\julia\current\share\julia\stdlib\v1.7\Distributed\src\process_messages.jl:165
  [9] process_tcp_streams(r_stream::Sockets.TCPSocket, w_stream::Sockets.TCPSocket, incoming::Bool)
    @ Distributed C:\Users\jcluts\scoop\apps\julia\current\share\julia\stdlib\v1.7\Distributed\src\process_messages.jl:126
 [10] (::Distributed.var"#103#104"{Sockets.TCPSocket, Sockets.TCPSocket, Bool})()
    @ Distributed .\task.jl:429
    ```

**Comment by pranavkrishna30** [comment]
I am having a similar issue with a file that worked on v0.10.4 but not on v0.10.5. I get the exact same exit code (3221225477 ) in vscode and the terminal crashes. If I try to open the file in a external REPL with CSV.File it crashes the REPL and closes it.  This is the file: [](url)
[results_10192022_mod.csv](https://github.com/JuliaData/CSV.jl/files/9843493/results_10192022_mod.csv). 

I am on Windows 10 Intel Core i7 with Julia 1.7.3. 

![image](https://user-images.githubusercontent.com/82563386/197317369-7253819e-01b9-4285-9336-ab863e3b6860.png)
^Error in VSCode

**Comment by quinnj** [comment]
If either of you would be willing to try out a [new PR](https://github.com/JuliaData/CSV.jl/pull/1043) I'd really appreciate it to see if it fixes your issue. You can try the PR out by doing:

```julia
] add CSV#jq/revert_precompile
```
then reloading your REPL and trying to load the file.

**Comment by jordancluts** [comment]
I tried this PR and it fixed the issue with my file. I was able to load the file at the REPL as expected.

**Comment by quinnj** [comment]
Ok, I've merged the PR; I put up another PR to hopefully fix a different memory leak issue, so once that's merged, I'll tag a new release. Thanks all.
