### ISSUE TITLE
Promotion error with String7 type

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/CSV.jl#1053]
From the flights dataset which is common in R

```
julia> url = "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/nycflights13/flights.csv"
"https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/nycflights13/flights.csv"

julia> t = CSV.read(download(url), DataFrame)
ERROR: MethodError: Cannot `convert` an object of type 
  Parsers.Result{String7} to an object of type 
  Parsers.Result{Any}
Closest candidates are:
```

**Comment by nickrobinson251** [comment]
i couldn't replicate this on the latest CSV release (v0.10.7), with Julia 1.8.2, and with either 1, 4 or 8 threads. It parsed as expected for me.

could you share any more details about package versions, julia version, number of threads?

**Comment by pdeffebach** [comment]
It does seem to work on v0.10.7. So I guess you can close this, unless you want to point me to the commit that most likely fixed this issue.
