### ISSUE TITLE
Do not edit "N/A", "NA", and similar entries **by default**.

### ISSUE THREAD

**Issue by sadish-d** [JuliaData/CSV.jl#1077]
I just wanted to preemptively request that DataFrames.jl not change "N/A", "NA", and similar entries to missing or NaN _by default_ as Python's Pandas currently does. In Pandas, if I import a csv file and export it _with default settings_, I do not necessarily get the same thing (it exports the index, edits NAs, ...). It is very annoying.

**Comment by bkamins** [comment]
This is issue related to CSV.jl not DataFrames.jl so I transferred it.

The thing you request is handled by `missingstring` keyword argument. You can read about it here https://csv.juliadata.org/stable/reading.html#missingstring.

If this is clear and enough for you I propose to close this issue.
