### ISSUE TITLE
Unable to read 1 column 1 row file

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#111]
> data_path
> "d:/data"

The above is the entire content of my csv file. It used work when I do `CSV.read("file.csv")` In fact I can't seem to read any CSV files.

But now it gives error message 
> MethodError: no method matching streamtypes(::Type{DataFrames.DataFrame})
> Closest candidates are:
>   streamtypes(!Matched::Type{CSV.Sink}) at C:\Users\dzj\AppData\Local\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\CSV\src\Sink.jl:32
> in read at CSV\src\Source.jl:311
> in #read#39 at CSV\src\Source.jl:312
> in  at base\<missing>
> in #stream!#17 at DataStreams\src\DataStreams.jl:431

**Comment by quinnj** [comment]
For current master CSV, you'll also need current _release_ of DataStreams + current master of DataFrames. Sorry for the weird state, but everything's a little held up on a new tag of DataFrames right now, but I'm trying to make sure CSV is ready to tag when DataFrames gets tagged as well.

**Comment by quinnj** [comment]
Please reopen if you can reproduce on current 0.6 or 0.7.
