### ISSUE TITLE
Add Zenodo badge to README

### ISSUE THREAD

**Issue by juliohm** [JuliaData/CSV.jl#1112]
Can you please share a bibtex entry for this package?

**Comment by juliohm** [comment]
ping @quinnj

**Comment by quinnj** [comment]
I'm not exactly sure what this means; is there a tutorial on what I need to do here?

**Comment by juliohm** [comment]
Packages usually add a Zenodo badge for citation with a valid DOI. But a
simple bibitex entry would be enough if citation counts aren't important.

Em sáb., 16 de set. de 2023 01:40, Jacob Quinn ***@***.***>
escreveu:

**Comment by quinnj** [comment]
I just went to Zenodo and searched CSV.jl and found this: https://zenodo.org/record/8004128. Do you need me to do something else or is that sufficient for your needs?

**Comment by juliohm** [comment]
That is it. I'll add the entry to the list of references.

Em seg., 18 de set. de 2023 19:50, Jacob Quinn ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Renamed the issue accordingly.
