### ISSUE TITLE
Need option for escapechar=nothing in CSV.read()

### ISSUE THREAD

**Issue by mebrunet** [JuliaData/CSV.jl#112]
I would like to load a dataset of Facebook likes with CSV.read(). It has 2 columns, `like_id` and `like_string`. It is comma delimited, and it uses `"` as the quote char. However, it *does not have an escape char*... the dataset has simply been preprocessed to remove any instance of a `"` from within the values of `like_string`. (I found this strange... but so be it!).

This poses a problem with `CSV.read()`. Since the kwarg `escapechar` cannot be set to nothing, and for any ascii character I choose, I have no guarantee that it will not appear before a closing `"` quote. For example, ending like_strings with the frazzled face `:\` is especially common, and messes with the default escape settings.

For now I have simply set `escapechar='\0'`, which works. However, I don't know much about the use of ascii control characters and whether this could have unintended consequences in general.

**Comment by quinnj** [comment]
I think the best option here is your solution: `escapechar='\0'`.
