### ISSUE TITLE
DataStreams.Data.NullException

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/CSV.jl#113]
Using Julia nightly CSV (checkout) and with either DataStrames (free / checkout) and DataFrames (checkout) I get the following error.
```
DataStreams.Data.NullException("encountered a null value for a non-null column type on...)
```
when attempting to read files with missing values.

**Comment by quinnj** [comment]
I don't see this on 0.6 or 0.7; please reopen if you can still reproduce.
