### ISSUE TITLE
Error in `CSV.read` docstring

### ISSUE THREAD

**Issue by nickeubank** [JuliaData/CSV.jl#114]
I think Line 247 of `src/Source.jl` of should have a period for element-wise operation. I think it should read: 

    string.(::WeakRefString)

not 

    string(::WeakRefString)

I don't have a cloned / forked copy of CSV -- would someone in the project mind fixing? I know it's poor form to note these things without a PR, but seems small enough I'd appreciate if someone on the team would be willing to patch. 

[Edit: clarification of problem]: Otherwise, at least when there are missing values, the output is something like:

```
string(df[:date])

"Union{Missings.Missing, WeakRefString{UInt8}}[\"September 13, 2017\", \"September 14, 2017\", \"September 15, 2017\", \"September 16, 2017\", \"September 17, 2017\", \"September 18, 2017\", \"September 19, 2017\", \"September 20, 2017\", \"September 21, 2017\", \"September 22, 2017\", \"September 23, 2017\", \"September 24, 2017\", \"September 25, 2017\", \"September 26, 2017\", \"September 27, 2017\", \"September 28, 2017\", \"September 29, 2017\", \"September 30, 2017\", \"October 1, 2017\", \"October 2, 2017\", \"October 3, 2017\", \"...
```

Instead of:

```

string.(df[:date])

String[59]
"September 13, 2017"
"September 14, 2017"
"September 15, 2017"
"September 16, 2017"
"September 17, 2017"
"September 18, 2017"
"September 19, 2017"
"September 20, 2017"
"September 21, 2017"
"September 22, 2017"
...
"November 1, 2017"
"November 2, 2017"
"November 3, 2017"
"November 4, 2017"
"November 5, 2017"
"November 6, 2017"
"November 7, 2017"
"November 8, 2017"
"November 9, 2017"
"November 10, 2017"
```

Thanks!

**Comment by nalimilan** [comment]
Thanks for the report. Even if you don't have clone the repository, for simple cases like this you can make a PR by editing the file on GitHub.

**Comment by nickeubank** [comment]
Right! Thanks @nalimilan -- submitted a PR

**Comment by quinnj** [comment]
Addressed in https://github.com/JuliaData/CSV.jl/pull/143
