### ISSUE TITLE
Tests: more testset annotations

### ISSUE THREAD

**Issue by alyst** [JuliaData/CSV.jl#116]
Enclosing the related tests in testsets is very helpful:
* isolates the variables
* improves reporting
* if child testset fails, parent testset can resume
(but I guess I don't need to advertise that :))

Since executing CSV testsuite takes considerable time, the last bullet point is especially important.
In particular, `test/source.jl` would benefit a lot, as currently any failure there stops the whole test run.

**Comment by quinnj** [comment]
Added in https://github.com/JuliaData/CSV.jl/pull/143
