### ISSUE TITLE
Never Ending Computing for CSV.write 0.7-Dev

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/CSV.jl#121]
This code takes forever and never finishes for me.
```
using DataFrames
using CSV
srand(0)
df = DataFrame(PID = repeat(1:10, inner = 10), TID = repeat(1:10, outer = 10),
    X1 = rand(100), X2 = rand(100))
df[:y] = df[:X1] + df[:X2] + rand(100)
CSV.write("SampleData.csv", df)
```
Specs:
```
Julia                         0.7.0-DEV.2279
CSV                           0.2.0
DataFrames                    0.11.1
IJulia                        1.6.2
```

**Comment by nalimilan** [comment]
That code finishes very fast here with Julia 0.6 (it fails on 0.7). Have you tried with that version and without IJulia?

**Comment by Nosferican** [comment]
With IJulia it just takes forever and no extra information. Without IJulia I get a bit extra information
```
signal (11): Segmentation fault: 11
in expression starting at no file:0
_ZN4llvm11PointerType3getEPNS_4TypeEj at /Applications/Julia-0.7.app/Contents/Resources/julia/lib/julia/libLLVM.dylib (unknown line)
```
but same result of never ending.

**Comment by nalimilan** [comment]
Please test with Julia 0.6. AFAIK the package doesn't load without modifications on 0.7, right?

**Comment by Nosferican** [comment]
The package should load without any issues on 0.7.0-DEV.2279. It broke after `Dates` I believe. I have a copy of the .dmg file if you want to install that one rather from the source for Mac OS.

**Comment by nalimilan** [comment]
But can you please confirm that you don't see the problem on 0.6? That's an essential information, as it would mean the compiler regressed in 0.7. Or it could be due to a deprecation, which slow down calls dramatically (even if the warning is printed only once).

**Comment by Nosferican** [comment]
Just tested it with Julia 0.6.1 and works just fine.

**Comment by nalimilan** [comment]
OK, good. So I guess the next step will be to fix all deprecations in CSV and check whether it still happens. Or maybe `julia --depwarn=no` is enough to avoid the performance impact of deprecations.

**Comment by Nosferican** [comment]
The same issue happens with Feather and that package has updated the depreciations. I suspect the culprit is the same for both.

**Comment by quinnj** [comment]
I don't see this on 0.6 or 0.7, so I don't think it's an issue anymore. Please reopen if you can still reproduce.
