### ISSUE TITLE
Allow comments in CSV.read()

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaData/CSV.jl#122]
I liked the option in `DataFrames.jl` to allow comments through:
`df = readtable(filename, allowcomments=true)`

So I could write in my .csv files comments, such as:
```
atom,epsilon,sigma
C,12.0,3.1
# from Ref. [1]
O,3.2,3.2
# from Ref. [2] see URL xxx
H,3.1,323.0
```

And this allowed the reader to skip a variable number of lines in the header as long as the line started with `#`.

Is this possible in `CSV.read()`?

**Comment by cjprybol** [comment]
It's not possible with `CSV.read()`. You'll need to stick to `readtable` for now, although [this](https://cjprybol.github.io/uCSV.jl/latest/man/comments-skiplines.html) may also suit your needs

**Comment by moustachio-belvedere** [comment]
+1 for this if at all possible. For now I will use uCSV as the Atomic Force Microscope I use outputs a nasty format which could only be parsed if hashed lines skipped or stripped out in preprocessing. I would guess this is fairly common requirement for experimental scientists.

**Comment by nalimilan** [comment]
If anybody wants to give a try at implementing this in CSV.jl, I'd be happy to review and help with a pull request.

**Comment by quinnj** [comment]
I don't think this would be too hard to support; I know it's a bit hard to dive into w/ how things are currently factored, but I think adding some logic in the `@checknullstart` macro would be the best place to start. I have some ideas around refactoring all the parsing code though that could make this a lot easier.
