### ISSUE TITLE
Allow string delimiter

### ISSUE THREAD

**Issue by filipebraida** [JuliaData/CSV.jl#126]
I have a CSV that has delimiter "::" and this file my package automatically downloads. Would the delim also be string?

Thanks :D

Example (MovieLens 1M - https://grouplens.org/datasets/movielens/1m/)
1::1193::5::978300760
1::661::3::978302109

**Comment by cjprybol** [comment]
String delimiters are not currently supported. You can use the `replace` command to change instances of `"::"` in your file to an ASCII character such as `','` before passing the data to `CSV.read()`. If you'd like to use string delimiters, the only solution I'm aware of is documented [here](https://cjprybol.github.io/uCSV.jl/latest/man/delimiters.html)

**Comment by quinnj** [comment]
We could potentially support this, but I'd be worried about the performance; maybe we could find a way to dispatch the parsing based on single ASCII byte delimiters (what's currently allowed) vs. arbitrary string delimiters.

**Comment by quinnj** [comment]
I have a local branch that supports string delimiters; will try to push soon.

**Comment by quinnj** [comment]
Support for this is on master with the switch to `CSV.File` (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). You can now specify a string as the `delim=str` keyword argument.

Note for now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
