### ISSUE TITLE
Line numbers in error messages?

### ISSUE THREAD

**Issue by cormullion** [JuliaData/CSV.jl#130]
I don't know if it's possible technically, but it would be useful if `CSV.read` could tell us where in a CSV file it had a problem, or indicate the string it got stuck on. Here's a typical error message:

```
MethodError: Cannot `convert` an object of type WeakRefString{UInt8} to an object of type Missings.Missing
This may have arisen from a call to the constructor Missings.Missing(...),
since type constructors fall back to convert methods.
setindex!(::Array{Missings.Missing,1}, ::WeakRefString{UInt8}, ::Int64) at array.jl:549
streamto! at io.jl:302 [inlined]
macro expansion at DataStreams.jl:512 [inlined]
stream!(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Missings.Missing}, ::Type{DataStreams.Data.Field}, 
```

If it said "on line 237" or something it would be helpful in tracking down the problem.`WeakRefStrings` are bit obscure...

**Comment by nalimilan** [comment]
Row and column numbers are printed in some cases, notably when a missing value is encountered for a column which does not support them.

The error you show is a bit special, as it seems to correspond to a column which was detected as containing only missing values... Does that happen in other cases too?

**Comment by cormullion** [comment]
Does `CSV.read` scan the file (first few lines?) to see what types the columns have, before it does the actual reading? Or does it assume that the first column determines the types? (which makes sense...).

**Comment by nalimilan** [comment]
It only reads the first lines, and I think we should increase the number of lines it uses to limit problems.

**Comment by quinnj** [comment]
Also see the `CSV.validate` function, which takes the same arguments as `CSV.read` and provides helpful diagnostics for malformed csv.

**Comment by cormullion** [comment]
@quinnj That's great - hopefully it will get featured prominently in the docs eventually!

**Comment by quinnj** [comment]
Docs added for `CSV.validate` in https://github.com/JuliaData/CSV.jl/pull/143
