### ISSUE TITLE
encoding is not recognized by `CSV.read`

### ISSUE THREAD

**Issue by zweiglimmergneis** [JuliaData/CSV.jl#131]
reproduce:
- Write csv-file "somecsvdata", UTF-8 encoded, containing German umlauts like "ä".
- Read this file with `CSV.read("somecsvdata")`
- Get a DataFrame with glyphs like "Ã¤"

workaround:
use encoding "latin-1-unix"

I found no option to set the encoding for `CSV.read`

**Comment by nalimilan** [comment]
Actually, that's supposed to be the other way around: CSV only supports UTF-8 input. Are you sure your data is saved in the right encoding? What's your OS? Can you make an example file available somewhere (not by copy/paste as it would lose encoding)?

Non-UTF-8 files can be read using StringEncodings together with CSV. Maybe we could add an argument to make this even easier to use.

**Comment by quinnj** [comment]
Depending on your version, it may just be a `WeakRefString` issue, you could try `CSV.read(file; weakrefstrings=false)`

**Comment by zweiglimmergneis** [comment]
OS is fedora. emacs and editor agree with respect to the encoding. You find test files here:
https://www.magentacloud.de/share/ds3w0qs-lj

**Comment by zweiglimmergneis** [comment]
Yes, with `weakrefstrings=false` UTF-8 is read properly. Thanks to everybody.

**Comment by ElisabeteCoelho** [comment]
I also had exactly the same issue (Windows 10, Julia 0.6.0) with the same solution. Maybe adding a reference in the manual that WeakRefString affects encoding would make it clearer to newbies like me. ;)
Thanks anyway for your help!

**Comment by nalimilan** [comment]
`WeakRefString` is not supposed to affect encoding, that's just a corruption bug which should be fixed. :-)

**Comment by ElisabeteCoelho** [comment]
Ah ok, thanks for the clarification.

**Comment by nalimilan** [comment]
FWIW that argument has just been added back in ea2f215860dc0fec9eca09b1ea02763e683f5e80.
