### ISSUE TITLE
Quotes around strings with number in front

### ISSUE THREAD

**Issue by JoshChristie** [JuliaData/CSV.jl#145]
Hi,

When trying to read with a string that has a number at the front, it detects an Int and doesn't keep searching for the end `escapechar`.

Here's a reproducible example.
```julia
julia> using CSV, DataFrames
julia> df = DataFrame(A="123,aa", B=2, quotefields=true);
julia> CSV.write("out.csv", df);
julia> CSV.read("out.csv")
1×2 DataFrames.DataFrame
│ Row │ A   │ B     │
├─────┼─────┼───────┤
│ 1   │ 123 │ ","2" │
```

I believe the issue may be from `detecttype` (line 220 of io.jl) it first checks for an Int (`CSV.parsefield(io, Union{Int, Missing}, opt)`) and so it doesn't check for a String.

**Comment by andyferris** [comment]
Bump

**Comment by nalimilan** [comment]
Note that to actually reproduce the bug you need to pass `quotefields=true` to `CSV.write`. Else fields are not quoted and a completely different behavior is tested.

**Comment by quinnj** [comment]
This should be fixed on master with a rewrite of `CSV.write` that now integrates with Tables.jl. You can now do `source |> CSV.write(file; kwargs...)`.
