### ISSUE TITLE
Error (no default format) writing non-base type (example: ZonedDateTime)

### ISSUE THREAD

**Issue by JockLawrie** [JuliaData/CSV.jl#152]
Hi there,

This is more of a design question than a functional issue.
Consider this example:

```julia
using Base.Dates
using DataFrames
using TimeZones
using CSV

tz  = TimeZone("Australia/Melbourne")
dt  = ZonedDateTime(DateTime(today()), tz)
tbl = DataFrame(a = [dt])
CSV.write("test.tsv", tbl; delim='\t')  # error
```

That is, I can't write the non-base type (`ZonedDateTime`) because it has no associated `defaultformat` method.

One solution is to convert the non-base type to a string before writing, then converting it back when reading. Quite hacky.

A more elegant approach is to define a `defaultformat` method for the type in question. In this case:

```julia
CSV.defaultformat(::TimeZones.ZonedDateTime) = dateformat"yyyy-mm-ddTHH:MM:SSzzzz"
CSV.write("test.tsv", tbl; delim='\t')  # OK
```

But some hackery is still required when reading:

```julia
tbl2 = CSV.read("test.tsv"; delim='\t')  # eltype(tbl2[:a]) is String
tbl2[:a] = ZonedDateTime.(tbl2[:a], "yyyy-mm-ddTHH:MM:SSzzzz")
```

My questions:
1. To ensure consistency and less repetition, is there a way to extract the default format string (`"yyyy-mm-ddTHH:MM:SSzzzz"`) from the `defaultformat` method?
2. Any other ideas for writing and reading non-base types?
3. Is there a preferred approach?
4. Should this `defaultformat` method be defined in every user's code, or in the relevant package (the TimeZones package in this example)?

Cheers,
Jock

**Comment by JockLawrie** [comment]
Alternatively, CSV/DataStreams could stringify columns with non-base type as part of the `write` method. The same hackery would be required when reading.
Thoughts?

**Comment by ko56** [comment]
I have a similar problem, maybe even somewhat simpler:

julia> dt = DateTime(string("2016-11-27","23:45:00"), "yyyy-mm-ddHH:MM:SS")
2016-11-27T23:45:00
julia> t = Dates.Time(dt)
23:45:00
julia> tbl = DataFrame(a = [t])
1×1 DataFrames.DataFrame
│ Row │ a        │
├─────┼──────────┤
│ 1   │ 23:45:00 │
julia> CSV.write("junk.csv", tbl)

Same issue with the type Dates.Time.

**Comment by quinnj** [comment]
Both these examples now work on master w/ the new implementation of `CSV.write(tbl, "junk.csv")`.
