### ISSUE TITLE
Trouble parsing dates

### ISSUE THREAD

**Issue by jdechalendar** [JuliaData/CSV.jl#161]
If I read in a file with dates, they are parsed automatically. However, if I try to modify the dates, the type of that column changes from Array{Date,1} to DataArrays.DataArray{Date,1}. Is this behavior to be expected?

In my application, this type mismatch is causing trouble because I am inputting dates that sometimes get changed and sometimes don't. For now, I can work around the problem by using type unions when specifying input types but I wonder whether this could lead to other issues later on.

I am raising the issue here, but it may be coming from the DataFrames package. Please let me know if that is the case.

MWE and output below.

########################
using CSV
data = CSV.read(
    IOBuffer("""Date,col\n2018-01-06,3.0""");
    datarow=2, nullable=false
)
println(data)
println(typeof(data[:Date]))
println(typeof(data[:Date]+Dates.Day(1)))
data[:Date]+=Dates.Day(1)
println(typeof(data[:Date]))
########################
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using CSV
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /Users/jacquesdechalendar/.julia/v0.6/NullableArrays/src/operators.jl:99.

julia> data = CSV.read(
           IOBuffer("""Date,col\n2018-01-06,3.0""");
           datarow=2, nullable=false
       )
1×2 DataFrames.DataFrame
│ Row │ Date       │ col │
├─────┼────────────┼─────┤
│ 1   │ 2018-01-06 │ 3.0 │

julia> println(data)

1×2 DataFrames.DataFrame
│ Row │ Date       │ col │
├─────┼────────────┼─────┤
│ 1   │ 2018-01-06 │ 3.0 │

julia> println(typeof(data[:Date]))
Array{Date,1}

julia> println(typeof(data[:Date]+Dates.Day(1)))
Array{Date,1}

julia> data[:Date]+=Dates.Day(1)
1-element Array{Date,1}:
 2018-01-07

julia> println(typeof(data[:Date]))
DataArrays.DataArray{Date,1}

**Comment by nalimilan** [comment]
I guess you're using DataFrames 0.10.1? CSV.jl works better with DataFrames 0.11, see https://discourse.julialang.org/t/dataframes-0-11-released/7296

**Comment by jdechalendar** [comment]
I confirm this fixed it for me. DataFrames was not getting updated because it had non-compatible dependents. I tested on both OSX and Ubuntu.

For reference, this no longer seems to be an issue with the following:
 - CSV                                 0.2.1
 - DataFrames                    0.11.5
