### ISSUE TITLE
Improve CSV.read experience

### ISSUE THREAD

**Issue by juliohm** [JuliaData/CSV.jl#164]
The `CSV.read` experience is not smooth. Every time I try to load a simple CSV file, the builtin `readcsv` works out of the box and the `CSV.read` crashes with a cryptic error message.

Is there any way to make it work "more often" by default? Can we recover the great `readcsv` quality that everything just works out of the box in most cases?

**Comment by nalimilan** [comment]
I'm afraid that's too vague to be actionable. Have a look at the other issues, in particular a common issue is when missing values appear beyond the rows used for type detection.

**Comment by juliohm** [comment]
I am not sure what rows are used for type detection, but that is probably the same issue I am having. Missings appear in random places in the file, including the bottom part of course. If `CSV.read` fails in this case, I'd say it fails 95% of the time in the real world.

**Comment by nalimilan** [comment]
OK, so closing in favor of https://github.com/JuliaData/CSV.jl/issues/153. For now you can increase the value of `row_for_type_detect` as a workaround.
