### ISSUE TITLE
BoundsError when loading csv file

### ISSUE THREAD

**Issue by chameroy** [JuliaData/CSV.jl#167]
Hi,

I'm trying to load a semi-colon delimited csv file, but I receive the following error:
BoundsError

Stacktrace:
 [1] indexed_next at .\tuple.jl:56 [inlined]
 [2] anonymous at .\<missing>:?
 [3] include_string(::String, ::String) at .\loading.jl:522

I don't know if this is a CSV.jl or DataFrames.jl issue.

Just for additional information, I have no problem loading this file into a pandas dataframe.

Thanks.

**Comment by nalimilan** [comment]
Can you provide a file to reproduce the problem? What versions of Julia and packages are you using?

**Comment by chameroy** [comment]
Sure. I'm using Julia 0.62, DataFrames.jl 0.11.5, and CSV.jl 0.2.1. I'll send you the data file I'm trying to work with.

**Comment by chameroy** [comment]
I've attached my data file.

Thanks.

**Comment by nalimilan** [comment]
Thanks. I don't think you can attach a file on GitHub, can you upload it somewhere? Ideally you could reduce it to a small example and past it in a Gist.

**Comment by chameroy** [comment]
I had attached it to my reply e-mail. Going that route, is it trying to upload it to GitHub instead of sending a personal e-mail? I tried responding to my e-mail because I'm concerned about posting my data onto GitHub before I get a chance to publish. Also, is there a possibility that by sending just a snippet of my data, the error will not be reproducible?

**Comment by chameroy** [comment]
Here is a gist snippet of my data. It appears to reproduce the error:

https://gist.github.com/chameroy/8c5b361fbb8ec5e2f31e265a3f6e5d0e

**Comment by nalimilan** [comment]
Thanks. I'm not able to reproduce the problem locally. Can you show the exact command you used and post the output of `Pkg.status`? What's your OS, and is it 32 or 64-bit?

**Comment by chameroy** [comment]
I'm running on Windows 10 64-bit.

The line I'm running to load the csv is:
df = CSV.read("dry_lake_valley_data_2018-02-05.csv"; ';')

My Pkg.status() output is:
5 required packages:
 - CSV                           0.2.1
 - DataFrames                    0.11.5
 - IJulia                        1.7.0
 - Plots                         0.15.0
 - Query                         0.9.1
45 additional packages:
 - BinDeps                       0.8.6
 - BufferedStreams               0.3.3
 - CategoricalArrays             0.3.4
 - CodecZlib                     0.4.2
 - ColorTypes                    0.6.7
 - Colors                        0.8.2
 - Compat                        0.53.0
 - Conda                         0.7.1
 - Contour                       0.4.0
 - DataStreams                   0.3.4
 - DataStructures                0.7.4
 - DataValues                    0.3.1
 - DocStringExtensions           0.4.3
 - Documenter                    0.13.1
 - FixedPointNumbers             0.4.6
 - IterableTables                0.7.0
 - IteratorInterfaceExtensions   0.0.2
 - JSON                          0.16.4
 - LibExpat                      0.4.1
 - Libz                          0.2.4
 - MacroTools                    0.4.0
 - MbedTLS                       0.5.5
 - Measures                      0.1.0
 - Missings                      0.2.6
 - NaNMath                       0.3.1
 - NamedTuples                   4.0.0
 - Nullables                     0.0.3
 - PlotThemes                    0.2.0
 - PlotUtils                     0.4.4
 - QueryOperators                0.2.1
 - RecipesBase                   0.2.3
 - Reexport                      0.1.0
 - Requires                      0.4.3
 - SHA                           0.5.6
 - Showoff                       0.1.1
 - SortingAlgorithms             0.2.0
 - SpecialFunctions              0.3.8
 - StaticArrays                  0.6.6
 - StatsBase                     0.20.0
 - TableTraits                   0.1.0
 - TranscodingStreams            0.4.1
 - URIParser                     0.3.0
 - WeakRefStrings                0.4.2
 - WinRPM                        0.3.1
 - ZMQ                           0.5.1

**Comment by nalimilan** [comment]
I've just checked on Windows 10 64-bit with the same version of all packages, and it works fine here. But note that the command you posted in your last comment is not correct, it should use `delim=';'`. Maybe that's the reason of the error? Indeed the stacktrace in the OP doesn't seem to indicate a problem in CSV itself.

**Comment by chameroy** [comment]
I'm sorry, I mistyped the line because I couldn't find my original code. I am using the delim parameter as such:

df = CSV.read("dry_lake_valley_data_2018-02-05.csv"; delim=';')

I really have no idea what is going on because I am now getting a different error:

stat: invalid argument (EINVAL)

Stacktrace:
 [1] stat(::String) at .\stat.jl:69
 [2] isfile at .\stat.jl:279 [inlined]
 [3] #Source#26(::String, ::CSV.Options{Void}, ::Int64, ::Int64, ::Array{Type,1}, ::Missings.Missing, ::Bool, ::Bool, ::Int64, ::Int64, ::Int64, ::Bool, ::Type{T} where T) at C:\Users\Chameroy\.julia\v0.6\CSV\src\Source.jl:52
 [4] (::Core.#kw#Type)(::Array{Any,1}, ::Type{CSV.Source}) at .\<missing>:0
 [5] #Source#25(::Char, ::UInt8, ::UInt8, ::String, ::Int64, ::Int64, ::Array{Type,1}, ::Missings.Missing, ::Void, ::UInt8, ::String, ::String, ::Bool, ::Bool, ::Int64, ::Int64, ::Int64, ::Bool, ::Type{T} where T, ::String) at C:\Users\Chameroy\.julia\v0.6\CSV\src\Source.jl:28
 [6] (::Core.#kw#Type)(::Array{Any,1}, ::Type{CSV.Source}, ::String) at .\<missing>:0
 [7] #read#47(::Bool, ::Dict{Int64,Function}, ::Bool, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at C:\Users\Chameroy\.julia\v0.6\CSV\src\Source.jl:313
 [8] (::CSV.#kw##read)(::Array{Any,1}, ::CSV.#read, ::String, ::Type{T} where T) at .\<missing>:0 (repeats 2 times)
 [9] include_string(::String, ::String) at .\loading.jl:522

**Comment by chameroy** [comment]
I decided to try re-saving my file as comma-delimited and using the following line:

df = CSV.read("dry_lake_valley_data_2018-02-05_comma.csv")

No problems. Any ideas why I'm having issues using a semi-colon delimited file?

**Comment by nalimilan** [comment]
Maybe the file was just locked by another process? You can try with `use_mmap=false`.

**Comment by nalimilan** [comment]
Bump.
