### ISSUE TITLE
-Inf can not be parsed as Float64

### ISSUE THREAD

**Issue by Wikunia** [JuliaData/CSV.jl#168]
My csv has the following line:
`nuclear14,1563,1227,576,0,602,Min,-Inf`

If I have this header formats: 
`types=[String,Int64,Int64,Int64,Int64,Int64,String,Float64]`

it doesn't work and gives this error:

```
ERROR: LoadError: CSV.ParsingException("error parsing a `Float64` value on column 8, row 283; encountered '-'")
```

there doesn't seem to be an error with `Inf` instead of `-Inf`

**Comment by nalimilan** [comment]
Looks like we need to change something here to take into account the possibility that a `'-'` character is followed by `"Inf"`: https://github.com/JuliaData/CSV.jl/blob/127041e862fad33d2bb4f0a30c930271ad87e512/src/float.jl#L94

Do you want to give it a try?

**Comment by Wikunia** [comment]
Sry, how can I give it a try?

**Comment by nalimilan** [comment]
I don't know, I just meant investigate how the code could be adapted to support this case.

**Comment by Wikunia** [comment]
Ah okay. Sure I can give it a try later today.

**Comment by jondea** [comment]
Also breaks on -nan

**Comment by Wikunia** [comment]
@nalimilan sorry I'm not really sure how to implement it by myself.
@jondea Is there any use-case for minus not a number?

**Comment by jondea** [comment]
@Wikunia, the bit representations are different and some languages/environments print them differently, see [Wikipedia page on not a number](https://en.m.wikipedia.org/wiki/NaN#Display). 

> Since, in practice, encoded NaNs have a sign, a quiet/signaling bit and optional 'diagnostic information' (sometimes called a payload), these will often be found in string representations of NaNs, too, for example: -NaN

As far as the logic goes, after discovering a minis sign, it needs to also check whether the next character is a number or a letter (or something along those lines). Currently it assumes minus sign implies number.

**Comment by nalimilan** [comment]
I have a fix at https://github.com/JuliaData/CSV.jl/pull/176.
