### ISSUE TITLE
segfaults from WeakRefString on 0.7

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/CSV.jl#177]
Sorry, I don't have a MWE yet but I wanted to post this issue so I don't forget.  Seeing it often enough that hopefully it won't be that hard for you to reproduce.  Never seems to occur when `weakrefstrings=false`.  Will try to create a minimal example and post it soon.

**Comment by nalimilan** [comment]
Is this still relevant?

**Comment by ExpandingMan** [comment]
I don't know.  I always do `weakrefstrings=false` now because this issue was scaring me.  Since I never took the time to track down this issue, I can close it unless I encounter it again.
