### ISSUE TITLE
more than 100 missing values at the top cause error

### ISSUE THREAD

**Issue by denizyuret** [JuliaData/CSV.jl#183]
I get an error with the following file:
```
a b
1 
1
...
1
1  1
1  1
```
If the number of lines missing 'b' is more than 100. This is a tab separated file.  The error message is:

```
ERROR: MethodError: Cannot `convert` an object of type WeakRefString{UInt8} to an object of type Missings.Missing
This may have arisen from a call to the constructor Missings.Missing(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] setindex!(::Array{Missings.Missing,1}, ::WeakRefString{UInt8}, ::Int64) at ./array.jl:583
 [2] streamto! at /ai/home/dyuret/.julia/v0.6/DataFrames/src/abstractdataframe/io.jl:303 [inlined]
 [3] macro expansion at /ai/home/dyuret/.julia/v0.6/DataStreams/src/DataStreams.jl:547 [inlined]
 [4] stream!(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"),Tuple{Base.Da$
 [5] #stream!#17(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Function, ::CSV.Source{Base$
 [6] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Arr$
 [7] #read#47(::Bool, ::Dict{Int64,Function}, ::Bool, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at /ai/home$
 [8] (::CSV.#kw##read)(::Array{Any,1}, ::CSV.#read, ::String, ::Type{T} where T) at ./<missing>:0
```

I guess after 100 missing values, CSV.jl decides that this column should have type Missing?

**Comment by nalimilan** [comment]
That's expected (and documented AFAIK): `rows_for_type_detect` rows are used to choose the number and types of columns. There's no way to parse a file efficiently without assuming that its structure won't change after a limited number of rows.

**Comment by jacobadenbaum** [comment]
It would be really useful if CSV.read could handle this gracefully.  I'm not quite sure how `readtable` in the old dataframes package did it, but I've found that it was much more stable when dealing with exactly these sorts of issues...

**Comment by matthieugomez** [comment]
Just to note, I think fread (in R/data.table) and read_csv (in R/readr) also reads some lines in the middle and at the end of the file to check the overall structure of the file.
```
A sample of 10,000 rows is used for a very good estimate of column types. 100 contiguous rows are read from 100 equally spaced points throughout the file including the beginning, middle and the very end. This results in a better guess when a column changes type later in the file (e.g. blank at the beginning/only populated near the end, or 001 at the start but 0A0 later on). This very good type guess enables a single allocation of the correct type up front once for speed, memory efficiency and convenience of avoiding the need to set colClasses after an error because there is no error. Even though the sample is large and jumping over the file, it is almost instant regardless of the size of the file because a lazy on-demand memory map is used. If a jump lands inside a quoted field containing newlines, each newline is tested until 5 lines are found following it with the expected number of fields. The lowest type for each column is chosen from the ordered list: logical, integer, integer64, double, character.
```

**Comment by jacobadenbaum** [comment]
The current approach of requiring the user to specify how many rows to use for type detection (and throwing an error if it changes at any point later in the file) seems to cause a lot of problems for interactive data work.  In particular, when I receive a file where a column contains mostly missing values, I may not know where the nonmissing values are ahead of time, so I _can't_ specify how many columns to use for type detection, or I'll have to do this in an iterative process where I keep trying to use increasing values until the file loads without error.  

It would be extremely useful to have a fallback method, which will obviously be not as performant, that can handle these pathological datasets which can show up in applied/interactive work.  I know that there were problems with the old `readtable` function, but as I recall it was pretty good about handling these sorts of corner cases.

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/CSV.jl/pull/203.

**Comment by proflage** [comment]
hi guys,

I'm afraid I got the same error; please [see it here](https://github.com/proflage/2018-julia-hands-on/blob/master/data-driven_journalism.ipynb).

Any news on how to solve it? Is it at `CSV.jl` milestone?

**Comment by proflage** [comment]
good news, @quinnj, thanks ! Please let us know when you do it and how to use it.

**Comment by quinnj** [comment]
This should be fixed on master with a refactoring of internals; the new approach uses the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
