### ISSUE TITLE
`append` to Dataframe not working?

### ISSUE THREAD

**Issue by ssfrr** [JuliaData/CSV.jl#188]
I'm using the baby name dataset from [here](https://catalog.data.gov/dataset/baby-names-from-social-security-card-applications-data-by-state-and-district-of-)

And trying to read the state-by-state files into a single dataframe doesn't seem to be appending properly.

MWE:

```julia
using Glob
using CSV

statefiles = glob("data/states/*.TXT")
headers = ["state", "sex", "year", "name", "count"]
state1data = CSV.read(statefiles[1], header=headers)
println("got $(size(state1data, 1)) entries from first only")
state2data = CSV.read(statefiles[2], header=headers)
println("got $(size(state2data, 1)) entries from second only")

bothstatedata = CSV.read(statefiles[2], state1data, header=headers, append=true)
println("got $(size(bothstatedata, 1)) entries from both combined")
```

which gives:
```
got 27624 entries from first only
got 130297 entries from second only
got 130297 entries from both combined
```

So it seems that it's not appending the 2nd to the first.

**Comment by quinnj** [comment]
This is fixed in the current release by doing `append!(existing_df, CSV.File(file))`
