### ISSUE TITLE
CSV.read(): set categorical to false by default

### ISSUE THREAD

**Issue by funnell** [JuliaData/CSV.jl#191]
I just got caught by the classic stringsAsFactors gotcha from R using CSV.read(). I was even more surprised to find conversion depends on the data content!
This setting caused unexpected behaviour regarding sort order in a DataFrame. Even though CategoricalArrays seem nicer than R factors, categorical=true can still cause unexpected behaviour.
Would it be all right to switch the categorical arg to false by default?

**Comment by nalimilan** [comment]
Yes, we should probably stop using `CategoricalArray` by default for string columns with a small proportion of unique values. We made this choice as an experiment, because it's much more efficient than `Array{String}` (which differs from R). Maybe we should use `PooledArray` instead, which offers the same performance benefits but without any difference in behavior.

> This setting caused unexpected behaviour regarding sort order in a DataFrame. Even though CategoricalArrays seem nicer than R factors, categorical=true can still cause unexpected behaviour.

Can you give details regarding the sort order difference you observed? By default a `CategoricalArray` uses lexicographic ordering, so it shouldn't differ in behavior compared with a standard array.

**Comment by funnell** [comment]
I had a `DataFrame` that looked like the following:
```
│ Row │ c1 │ c2 │
├─────┼────┼────┤
│ 1   │ a  │ s1 │
│ 2   │ a  │ s2 │
│ 3   │ a  │ s4 │
│ 4   │ b  │ s2 │
│ 5   │ b  │ s3 │
│ 6   │ b  │ s4 │
```
which resulted in this
```
julia> sort(df)
6×2 DataFrames.DataFrame
│ Row │ c1 │ c2 │
├─────┼────┼────┤
│ 1   │ a  │ s1 │
│ 2   │ a  │ s2 │
│ 3   │ a  │ s4 │
│ 4   │ b  │ s2 │
│ 5   │ b  │ s4 │ <-
│ 6   │ b  │ s3 │
```
The levels are set by order of appearance when I load the `DataFrame` from a file using `CSV.read()`. Creating a `DataFrame` manually using `CategoricalArray`s seems to set the levels according to a sorted ordering. However, using the sorted levels can give unexpected results too:
```
julia> df = DataFrame(c1=CategoricalArray(["b", "a"]))
2×1 DataFrames.DataFrame
│ Row │ c1 │
├─────┼────┤
│ 1   │ b  │
│ 2   │ a  │

julia> unique(df[:c1])
2-element Array{String,1}:
 "a"
 "b"
```
where I'd normally expect `["b", "a"]`.

**Comment by nalimilan** [comment]
OK, I see the problem. https://github.com/JuliaData/CategoricalArrays.jl/pull/139 fixes `unique`. The sorting problem needs to be fixed in DataFrame, which currently uses the order of appearance of values.

**Comment by quinnj** [comment]
`categorical=false` is now the default on master with `CSV.File`.

The new approach uses the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
