### ISSUE TITLE
Reading a CSV2 file with the minus sign as missing value

### ISSUE THREAD

**Issue by iscalprog** [JuliaData/CSV.jl#198]
Trying to read the following data:
```
;Taux de l'Eonia (moyenne mensuelle);EURIBOR à 1 mois;EURIBOR à 12 mois;EURIBOR à 3 mois;EURIBOR à 6 mois;EURIBOR à 9 mois
18/04/2018;-0,368;-0,371;-0,189;-0,328;-0,271;-0,219
17/04/2018;-0,368;-0,371;-0,189;-0,328;-0,27;-0,219
16/04/2018;-0,367;-0,371;-0,189;-0,329;-0,27;-0,219
15/04/2018;-;-;-;-;-;-
14/04/2018;-;-;-;-;-;-
13/04/2018;-0,364;-0,371;-0,19;-0,329;-0,271;-0,219
```
using 
```
CSV.read("Euribor.csv", decimal = ',',  delim = ';',  missingstring="-", datarow = 2, header = ["Date", "EONIA", "1m", "12m", "3m", "6m", "9m"])
```
The problem in this case is reading ```-``` (minus sign) as the missing value. I get the following error:
```
ERROR: LoadError: CSV.ParsingException("error parsing a `Float64` value on column 2, row 4; encountered ';'")
```
Is it possible to overcome this problem? Thank you very much.

**Comment by stevengj** [comment]
I think the problem may be this line: https://github.com/JuliaData/CSV.jl/blob/4ca71c5e85037c73197a8e027c2b867e5eec129a/src/float.jl#L123

If it isn't the end of the file, it consumes the next byte (after the `-`), at which point the subsequent `checkmissingend` will fail.  It seems like it needs to replace `b = readbyte(io)` with something like:
```jl
c = peekbyte(io)
(c == LITTLEN | c == BIGN | c == LITTLEI | c == BIGI) || @goto checkmissingend
b = readbyte(io)
```

**Comment by nalimilan** [comment]
Thanks @stevengj! It would have been nice to be able to avoid `peekchar`, but I couldn't find a better way. See https://github.com/JuliaData/CSV.jl/pull/202.

There's still a separate bug, which already exists on master, with the following example:
```
A;B;C
a;-0,367;-0,371
b;++;++;++
c;++;++;++
d;-0,364;-0,371
```
The result of both `CSV.read("test.csv", missingstring="+", delim=';', decimal=',')` and `CSV.read("test.csv", missingstring="++", delim=';', decimal=',')` is incorrect, with values in weird orders and missing values all over the place.

**Comment by quinnj** [comment]
I think this is all fixed on master; I at least have a local branch w/ tests added covering the cases reported here and everything passes fine.
