### ISSUE TITLE
Number in quotes read incorrectly

### ISSUE THREAD

**Issue by tk3369** [JuliaData/CSV.jl#207]
See https://discourse.julialang.org/t/csv-misread/10966

Repeated here:
```
shell> cat > test.csv
a,b,c,d,e,f
1863001,134,10000,1.0009,1.0000,-0.002033899
1863209,137,0,1.0000,"2,773.9000",

julia> CSV.read("test.csv")
2×6 DataFrames.DataFrame
│ Row │ a       │ b   │ c     │ d      │ e   │ f          │
├─────┼─────────┼─────┼───────┼────────┼─────┼────────────┤
│ 1   │ 1863001 │ 134 │ 10000 │ 1.0009 │ 1.0 │ -0.0020339 │
│ 2   │ 1863209 │ 137 │ 0     │ 1.0    │ 2.0 │ 773.9      │
```

**Comment by grinsted** [comment]
I'm also struggling with numbers in this form. "25,540,000","column 2",,...

**Comment by grinsted** [comment]
This is my workaround:
```julia
hur = CSV.read("mycsv.csv",  transforms=Dict{Int64, Function}(4=>x->tryparse(Float64,replace(string(x),",",""))))
```

**Comment by quinnj** [comment]
This should be fixed on master with a refactoring of internals; the new approach uses the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
