### ISSUE TITLE
Several `String`s for missing values

### ISSUE THREAD

**Issue by AsileBcd** [JuliaData/CSV.jl#208]
I was looking at a way to pass several values for missing values at the same time, like "NA", "-" and "" in `CSV.read`.
It currently does not work as the expected argument is a `String`. Is their a way around this behavior?

(for those who wonder why I need several missing values, I am reading outputs from different software, with different conventions on the matter and aggregating the data).

**Comment by AsileBcd** [comment]
Thank you for your answer. I will try to use transforms and post an example if I manage too.

**Comment by AsileBcd** [comment]
Thank you for your answer.
As far as I can tell, using `transforms` will be quite burdensome: it has to be able to detect all potential types in the table, and transforms the values that are considered as  `missings` (for me, `"-", "NA", ""`). Am I right or is there a shortcut?

**Comment by quinnj** [comment]
Support for this is merged in master; the new approach uses the `CSV.File(file; missingstrings=[...], kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
