### ISSUE TITLE
Ignore consecutive delimiters in files with padded columns in CSV.read(...)

### ISSUE THREAD

**Issue by cossio** [JuliaData/CSV.jl#209]
I am reading a file with CSV.read(...) that contains many consecutive spaces between columns because the colmuns are padded. I passed the keyword argument delim=' ', but it thinks that every space counts as a new column, instead of ignoring long stretches of consecutive white spaces.

**Comment by MarioMacedo22** [comment]
I'm having the same problem for at least 2 weeks. In my case the delim is ";".

**Comment by quinnj** [comment]
I think we should be able to support this w/o too much trouble.

**Comment by quinnj** [comment]
Closing as dup of #71
