### ISSUE TITLE
precompilation failing on 0.7

### ISSUE THREAD

**Issue by kafisatz** [JuliaData/CSV.jl#219]
Every now and then I run into this: 
https://discourse.julialang.org/t/pkg-precompilation-failing-0-7alpha/11853

Sometimes `rm` and then `add` does the trick. But right now I cannot fix this...
Any ideas?

Also, when should I invoke `]precompile` versus `CSV`. Is there any preference?
I suppose, ideally I would be able to simply do `using MyPackage` to

**Comment by nalimilan** [comment]
You said on Discourse you have been able to fix it. Is that the case?

Anyway, it looks like there's a problem with the cache for SortingAlgorithms.

**Comment by kafisatz** [comment]
I was able to fix it ONCE by simply doing rm and then add again.
But it came up again. And right now I cannot fix it.

Yes, it might be related to SortingAlgorithms, but still I am not sure how to fix it.

BTW: I get a very similar issue (maybe identical) with OnlineStats complaining about LearnBase

**Comment by nalimilan** [comment]
You'll probably get more useful comments on Discourse, as this seems like a bug in Pkg3 or in a package down the stack, not in CSV...

**Comment by quinnj** [comment]
Fixed on master
