### ISSUE TITLE
Reading a big dataset is slower than R's read.csv

### ISSUE THREAD

**Issue by miguelmorin** [JuliaData/CSV.jl#224]
Similar to #51: I load a big dataset in CSV with 5.18 GB and 14 colums. It takes 34 minutes in R and 41 minutes in Julia:
```
2461.108097 seconds (4.72 G allocations: 77.585 GiB, 82.99% gc time)
```
For my specific problem, I used streaming with selected fields. But I would have expected Julia to be faster than R.

**Comment by miguelmorin** [comment]
Streaming line by line with 4 fields selected out of 14 and discarding about half the rows took 3 minutes:
```
192.874299 seconds (1.97 G allocations: 80.750 GiB, 50.77% gc time)
33222892×4 DataFrames.DataFrame
```
A naïve extrapolation: 192.87*2*14/4 = 1350, so it's the same order of magnitude as CSV.read. Maybe I should close the issue?

**Comment by nalimilan** [comment]
If you can make the dataset or a similar toy dataset available somewhere, maybe we can have a look.

**Comment by miguelmorin** [comment]
Yes, please find below the code to generate a dataset with the same size and structure. Julia takes 36 minutes, R is even faster than in my post and takes 9 minutes.

Code to generate data:
```
num_records = 7.2e7

# Dummy data
fields = ["YEAR","SERIAL","MONTH","HWTFINL","CPSID","ASECFLAG","PERNUM","WTFINL","CPSIDP","EMPSTAT","OCC","OCC1990","QEMPSTAT","QOCC"]

csv_array = String[]
headers = ""
for i in 1:length(fields)
    headers *= fields[i]
    if (i < length(fields))
        headers *= ","
    end
end
push!(csv_array, headers)

for i in 1:Int(num_records / 2)
    push!(csv_array, "1976,1,1,,19760101020100,,1,1880.56,19760100020101,10,100,100,0,")
    push!(csv_array, "2018,71147,2,102.7764,20120337348500,,1,605.0388,20010347458602,12,4122,416,,0")
end

filepath = "data.csv"

open(filepath, "w+") do f
    for i in 1:length(csv_array)
        write(f, csv_array[i] * "\n")
    end
end
```

Code to read it in Julia:
```
using CSV, DataFrames
@time CSV.read(filepath)
```
The result is:
```
2144.473223 seconds (4.75 G allocations: 82.076 GiB, 79.99% gc time)
```

Code to read it in R:
```
system.time(read.csv("data.csv"))
```
The result is:
```
   user  system elapsed 
327.179 121.567 525.879 
```

The function to read the file line by line and process only the relevant fields takes 7 minutes. Because this is a bit of "cheating", I omit it and can include it if required.

**Comment by quinnj** [comment]
Good news, on #232, I see:
```julia
julia> @time CSV.read(s)
127.990949 seconds (1.48 G allocations: 29.571 GiB, 2.01% gc time)
┌ Warning: The start/next/done iteration protocol is deprecated. Implement `iterate(::DataFrames.DFColumnIterator{DataFrames.DataFrame})`.
│   caller = ip:0x0
└ @ Core :-1
```
So it looks like whatever performance issue was happening will be fixed.

**Comment by quinnj** [comment]
On current master:
```julia
julia> using Tables, CSV

julia> @time data = CSV.File("data.csv") |> columntable;
 37.428396 seconds (72.30 M allocations: 3.334 GiB, 1.59% gc time)
```

**Comment by quinnj** [comment]
The code for this has been merged in master; right now it's accessible through the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
