### ISSUE TITLE
error parsing a `Int64` value on column 1, row 3; encountered '.'

### ISSUE THREAD

**Issue by EricForgy** [JuliaData/CSV.jl#23]
Hi,

I am interested in giving this package a try, but am having some difficulty reading my first CSV file.

I start by defining a Source:

``` julia
f = CSV.Source("my.csv")
```

Then I try to `stream!` this to a `Data.Table`:

``` julia
julia> ds = Data.stream!(f,Data.Table)
ERROR: CSV.CSVError("error parsing a `Int64` value on column 1, row 3; encountered '.'")
```

Here is a snapshot of the first data values (below the headers) opening the CSV file in Notepad:

![image](https://cloud.githubusercontent.com/assets/8954730/16177020/a63cfc5e-3653-11e6-9708-ecefef3772ef.png)

When I inspect `f.schema.header`, it read the headers correctly and when I inspect `f.schema.types`, it inferred the types correctly, i.e. 2 columns of Int64 and 20 columns of Float64.

Subsequent calls to `stream!` give similar errors but referring to different columns/rows:

``` julia
julia> ds = Data.stream!(f,Data.Table)
ERROR: CSV.CSVError("error parsing a `Int64` value on column 1, row 2; encountered '.'")

julia> ds = Data.stream!(f,Data.Table)
ERROR: CSV.CSVError("error parsing a `Int64` value on column 2, row 1; encountered '.'")
```

Any ideas? The CSV file seems OK to me, so I suspect I need to set some option/schema property.

Thanks.

**Comment by EricForgy** [comment]
Update:

I just deleted columns 3-22 keeping just the first 2 Int64 columns:

~~~julia
julia> f = CSV.Source("my 2 cols.csv")
[snip]
    CSV.Options:
        delim: ','
        quotechar: '"'
        escapechar: '\\'
        null: ""
        dateformat: Base.Dates.DateFormat(Base.Dates.Slot[],"","english")
123000x2 Data.Schema:
 Trial, Timestep
 Int64,    Int64

julia> ds = Data.stream!(f,Data.Table)
Data.Table:
123000x2 Data.Schema:
 Trial, Timestep
 Int64,    Int64

        Column Data:
        [1,1,1,1,1,1,1,1,1,1  …  3000,3000,3000,3000,3000,3000,3000,3000,3000,3000]
        [0,3,6,9,12,15,18,21,24,27  …  93,96,99,102,105,108,111,114,117,120]
~~~

This looks good.

**Comment by EricForgy** [comment]
Update:

Hmm... if I open the CSV file in Excel and "Save as" CSV, then I can `stream!` the whole thing.

**Comment by EricForgy** [comment]
It looks like my original CSV file had trailing commas at the end of each line I didn't notice before.

How could I make CSV.jl read a "bad" CVS file, etc, get it to handle an extra trailing comma, e.g. ignore it?

**Comment by quinnj** [comment]
We now have the `CSV.validate(file)` function which takes the same arguments as `CSV.read`, but will give informative error information for improperly formatted csv data.
