### ISSUE TITLE
Overflow occurs when reading very long decimals regardless of forcing a type

### ISSUE THREAD

**Issue by Ortix92** [JuliaData/CSV.jl#234]
I'm using this CSV package with `DataFrames` as sink. Some of my numbers in my csv are read incorrectly. These numbers are in scientific notation.

This row:

    -5.871153289887625082e-01,8.095032986136727615e-01,9.900000000000006573e-01,9.900000000000006573e-01,-9.866066418838319585e-01,-3.138907529596844714e+00,-5.129218106887371675e+00,-4.803915800699462224e+00

results in:

    -0.587115   │ 0.809503  │ -0.854674 │ -0.854674 │ 0.858068  │ -3.13891  │ -5.12922 │ -4.80392 

Take note of column 3 and 4. All of a sudden they are a completely different number.

This bug has been confirmed by others on stackoverflow.

**Comment by davidanthoff** [comment]
[CSVFiles.jl](https://github.com/queryverse/CSVFiles.jl) reads them correctly, so you can use that until things are fixed here.

**Comment by quinnj** [comment]
Thanks for the report here and sorry for the delay; this is fixed in Parsers.jl master (which CSV.jl uses for the underlying type parsers). This will be available in CSV.jl with its next tagged release (hopefully in the next few days)
