### ISSUE TITLE
Slow to read file with many columns

### ISSUE THREAD

**Issue by jmgnve** [JuliaData/CSV.jl#244]
I have a file with almost 800 columns but only 50 rows (~1mb in size). It takes really long time to read that file, in particular the first time. I use this code to read the file.

```julia
using CSV
data = CSV.read("table_test.txt", delim = ",")
```

R reads this file in 0.5s whereas it takes 7s in Julia (v0.7 and v1.0 with latest CSV release). But it takes minutes the first time.

Here is the file: [table_test.txt](https://github.com/JuliaData/CSV.jl/files/2307760/table_test.txt)

**Comment by quinnj** [comment]
Looking at this now.

**Comment by quinnj** [comment]
Alright, I have a fix for this:
```julia
julia> @time t = f |> columntable;
  1.839327 seconds (3.20 M allocations: 114.565 MiB, 7.01% gc time)

julia> @time t = f |> columntable;
  0.024310 seconds (384.30 k allocations: 6.750 MiB)
```
so 1.8 seconds for first run; 0.02 on the 2nd. I think we can improve the first-run time as well.

**Comment by quinnj** [comment]
The code for this has been merged in master; right now it's accessible through the `CSV.File(file; kwargs...)` function (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). For now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
