### ISSUE TITLE
If column is detected as integer, CSV fails to read 4e5 type of values

### ISSUE THREAD

**Issue by jmgnve** [JuliaData/CSV.jl#245]
If CSV has identified a column as integers, it can no longer handle numbers of scientific format (e.g. 4e+05). If CSV has identified the column as floating point numbers, then it works. Here is a small reproducable example.

```julia
CSV.read("test.txt", delim=";", header = false, rows_for_type_detect = 2)
```

And here is the file: [test.txt](https://github.com/JuliaData/CSV.jl/files/2309704/test.txt)

**Comment by quinnj** [comment]
Closing as dup of #200; we'll track progress there.
