### ISSUE TITLE
CSV.read() - Cannot convert WeakRefString to Missing

### ISSUE THREAD

**Issue by kescobo** [JuliaData/CSV.jl#248]
When reading a large CSV file, I'm getting the following error:

```julia
MethodError: Cannot `convert` an object of type WeakRefString{UInt8} to an object of type Missing
Closest candidates are:
  convert(::Type{Missing}, ::Any) at missing.jl:50
  convert(::Type{Union{Missing, T}}, ::Any) where T at missing.jl:43
  convert(::Type{Missing}, !Matched::Missing) at missing.jl:45
  ...
convert(::Type{Missing}, ::WeakRefString{UInt8}) at missing.jl:50
setindex!(::Array{Missing,1}, ::WeakRefString{UInt8}, ::Int64) at array.jl:769
stream!(::CSV.Source{Base.GenericIOBuffer{Array{UInt8,1}},Dates.DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"),Tuple{Dates.DatePart{'y'},Dates.Delim{Char,1},Dates.DatePart{'m'},Dates.Delim{Char,1},Dates.DatePart{'d'},Dates.Delim{Char,1},Dates.DatePart{'H'},Dates.Delim{Char,1},Dates.DatePart{'M'},Dates.Delim{Char,1},Dates.DatePart{'S'},Dates.Delim{Char,1},Dates.DatePart{'s'}}}}, ::DataStreams.Data.Query{0x01,Tuple{DataStreams.Data.QueryColumn{0x01,Union{Missing, CategoricalString{UInt32}},1,1,:iamc_id,nothing,
# Truncated
```

This despite the fact that I have `allow_missing_values` set to `:all`. If I increase the number of rows used for type inference, it works fine and the subset of columns I checked have the correct `Union{T, Missing}` types. 

I get the impression that the type inference is assuming no missing values after 100 rows, and then just giving me type `T`, and this makes a kind of sense, but my assumption was that the `allow_missing_values` flag would make everything the union type (I may want to add missings later for example).

**Comment by diegozea** [comment]
I've just got the same error using Julia 0.6.4. I think https://github.com/JuliaData/CSV.jl/issues/156 is the same error, the suggestion there is to use `types=Dict(...` to indicate the type of the column interpreted as containing only `Missing` values.

**Comment by kescobo** [comment]
@diegozea Yeah, that's not practical - I've got a giant table with hundreds of columns with lots of different types. Besides - the issue for mine is not that there are only Missing values, it's that there aren't any Missing values until after the 100 rows that are used to infer type.

**Comment by quinnj** [comment]
The keyword argument for this is `allowmissing=:all`; were you using the wrong keyword argument?

**Comment by kescobo** [comment]
@quinnj I don't think so - I think that's just a typo. I was using the default (which from the docs appears to be `allowmissing=:all`. In any case, this issue doesn't happen on `master` anymore, so I think your overhaul fixed it somehow.

**Comment by nalimilan** [comment]
Closing then.
