### ISSUE TITLE
CategoricalValues with non-Strings

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaData/CSV.jl#263]
I tried to read categorical values for floats from a file with
```julia
CSV.read("test.csv", use_mmap=!Sys.iswindows(), types=Dict("a"=>Int,"b"=>Union{Missing, CategoricalValue{Float64,UInt32}}))
```
but I got
```julia
ERROR: MethodError: Cannot `convert` an object of type WeakRefString{UInt8} to an object of type Float64
```
The contents of `test.csv`:
```
a,b
1,2.0
2,2.0
```

[copied from Slack]

**Comment by quinnj** [comment]
I've looked into this once or twice but it seems more work/effort than it's worth. It's easy enough to call `categorical!` after parsing.
