### ISSUE TITLE
CSV.write chewing up all my memory

### ISSUE THREAD

**Issue by JockLawrie** [JuliaData/CSV.jl#267]
Hi there,

I have a weekly ETL job that extracts data from a database (using ODBC.jl), modifies/cleans/formats it, and writes it to disk (in several tab-separated files).
I have been running this job on Julia 0.6.4 without issue for months.
I am now migrating the code to Julia 0.7 (with CSV 0.3.1) and `CSV.write` chews up all my memory (8GB) when writing one of the tsv files. Weirdly, `CSV.write` has no issues with the other files, some of which are bigger than the one that consistently grinds to a halt. The problem persists even if a try to write just 1 row of this `DataFrame`.

Also, I have tried to construct a minimal example but just can't seem to do it...even if I construct a DataFrame with exactly the same data, types and all (without doing all the ETL work beforehand). The only thing I can think of is some issue related to the state during the ETL job.

That's not much to go on, sorry, but I can't post the data because it's sensitive. Any ideas what might be happening?

**Comment by quinnj** [comment]
Sounds suspiciously similar to https://github.com/JuliaData/CSV.jl/issues/236, which should be fixed w/ the next point release to Julia (1.0.1), or you could also try CSV#master, which has a new `CSV.write` implementation that wouldn't encounter the same problem. I'm trying to get things cleaned up for a new release in the next week or two.

**Comment by JockLawrie** [comment]
Thanks for your quick responses.

Tried CSV#master, but DataFrames hasn't yet implemented the Tables interface.
Going with uCSV for now because of minimal dependencies and flexibility with schema (via types, encodings).
I'll try CSV again on the next release.

Thanks again,
Jock
