### ISSUE TITLE
Bug in reading numbers

### ISSUE THREAD

**Issue by phlavenk** [JuliaData/CSV.jl#269]
MWE:
```
write("test1.txt", """0.000000000000000000e+00
1.638500000000000000e+04
9.831100000000000000e+04
3.113180000000000000e+05
7.209430000000000000e+05
1.671285000000000000e+06
4.358441000000000000e+06
1.638519000000000000e+06
6.554000000000000000e+04
9.831000000000000000e+04
9.831000000000000000e+04
1.638500000000000000e+04
0.000000000000000000e+00 """)
ds = CSV.read("test1.txt", datarow=1, allowmissing=:none)
ds[3,1]
```
returns `-86156.44073709552` instead of the correct value '9.831100000000000000e+04'

That's pretty serious bug, as some values are correct and some aren't.
Happens on both 0.2.5 (Julia 0.6.4) and v0.3.1 (julia 0.7) on win7-64.

**Comment by quinnj** [comment]
Thanks for the report; this is fixed on the current master branch; I'm hoping to get a new release out soon w/ the fix.
