### ISSUE TITLE
CVS.read - ArgumentError

### ISSUE THREAD

**Issue by venkat5315** [JuliaData/CSV.jl#270]
I am very new to Julia and exploring.

julia> df=CSV.read("train.csv", types=Dict("col8"=>Float64))
ERROR: ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output instead.

I am using:

 [336ed68f] CSV v0.3.1
  [a93c6f00] DataFrames v0.13.1
  [7073ff75] IJulia v1.11.1
on Windows 10.

When using the above command in notebook, the variable df doesn't get set, while in REPL, despite the error message, I could access the variable df and it does show me the data frame.

Very much appreciate help/suggestions.

**Comment by quinnj** [comment]
This is fixed on CSV master (`pkg> add CSV#master`), but we haven't done a release yet (hopefully soon!). In the meantime, I think if you use Julia 0.7, it should be an overall easier experience right now as many things like this that are errors will be just warnings.
