### ISSUE TITLE
Is allowmissing=:none correct?

### ISSUE THREAD

**Issue by jmgnve** [JuliaData/CSV.jl#272]
Perhaps I have misunderstood `allowmissing`. Shouldn't this fail, since some rows contain `missings` for all columns?

```julia
file = joinpath(dirname(pathof(CSV)), "..", "test/testfiles/baseball.csv")
CSV.File(file, allowmissing=:none)
```

These two readings seem to give the same answer:

```julia
file = joinpath(dirname(pathof(CSV)), "..", "test/testfiles/Fielding.csv")
CSV.File(file, allowmissing=:auto)
CSV.File(file, allowmissing=:none)
```

I would have expected the second one to drop columns with `missings` or to have failed.

Whereas this one gives the answer that I expected, all are `Unions{missing, stuff}:

```julia
CSV.File(file, allowmissing=:all)
```

**Comment by jmgnve** [comment]
Intuitively, or whatever one likes to call it, I was expecting it to throw an error. Thus, the "hey, there shouldn't be any missing values in this dataset" scenario. Later I thought maybe it does only remove columns containing missings, which it doesn't do. However, such operations perhaps belong to packages such as DataFrames.jl, since this seems more like an post processing step. Therefore, I think I would vote for the error throwing case.

**Comment by quinnj** [comment]
@nalimilan thoughts on whether we should throw an error here? I'm leaning towards yes, but if anyone else thinks not, I'm fine keeping it since it's easier 😛
