### ISSUE TITLE
spaces after comma

### ISSUE THREAD

**Issue by gdkrmr** [JuliaData/CSV.jl#279]
the spaces after the commas in the first line of a file make parsing fail:
```julia
julia> IOBuffer("""
"a", "b", "c"
""") |> CSV.read
ERROR: CSV.ParsingException("Unexpected start of quote (34), use \"9234\" to type \"34\"")
```

**Comment by quinnj** [comment]
This is fixed on master
```julia
julia> io = IOBuffer("""
       "a", "b", "c"
       """)
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=14, maxsize=Inf, ptr=1, mark=-1)

julia> f = DataFrame(CSV.File(io))
0×3 DataFrame
```

**Comment by gdkrmr** [comment]
I cannot test it with the actual file because I think that I am running into the memory leak issue #236/#264, I updated `CSV` and `DataFrames` to master, I also have tried using `CSV.File |> DataFrame`, but this gives a conversion error. Before it worked fine most of the times.

**Comment by gdkrmr** [comment]
It doesn't fail any more, but now there are spaces/underscores around the column names:
```julia
julia> """ "a", "b", "c" """ |>
       IOBuffer |>
       CSV.File |>
       DataFrame |>
       names
3-element Array{Symbol,1}:
 :_a_
 :_b_
 :_c_
```
