### ISSUE TITLE
ERROR: argument is an abstract type; size is indeterminate

### ISSUE THREAD

**Issue by femtotrader** [JuliaData/CSV.jl#28]
Hello,

I have a CSV file named `test.csv` like this

```
ticker,dt,bid,ask
EUR/USD,20140101 21:55:34.378,1.37622,1.37693
EUR/USD,20140101 21:55:40.410,1.37624,1.37698
EUR/USD,20140101 21:55:47.210,1.37619,1.37696
EUR/USD,20140101 21:55:57.963,1.37616,1.37696
EUR/USD,20140101 21:56:03.117,1.37616,1.37694
EUR/USD,20140101 21:56:07.254,1.37616,1.37692
EUR/USD,20140101 21:56:16.911,1.3762,1.37695
EUR/USD,20140101 21:56:19.433,1.37615,1.37692
EUR/USD,20140101 21:56:24.971,1.37615,1.37691
EUR/USD,20140101 21:56:24.972,1.37615,1.37689
```

I'd like to load it using CSV.jl but it raises an error

```julia
julia> CSV.read("test.csv")
ERROR: argument is an abstract type; size is indeterminate
 in call at /Users/femto/.julia/v0.4/DataStreams/src/DataStreams.jl:189
 in stream! at /Users/femto/.julia/v0.4/DataStreams/src/DataStreams.jl:196
 in read at /Users/femto/.julia/v0.4/CSV/src/Source.jl:294
```

I have no idea how to fix this.

Kind regards

**Comment by tkelman** [comment]
Go back to the 0.0.8 release, and possibly corresponding older releases of the dependencies. http://pkg.julialang.org/detail/CSV.html

This is why things should be tagged one at a time and tested before tagging.

**Comment by abhijithch** [comment]
This is coming from [`DataStreams`](https://github.com/JuliaData/DataStreams.jl/issues/16).

**Comment by quinnj** [comment]
A new tag was just released that resolves this; do a `Pkg.update()` to get the latest and greatest
