### ISSUE TITLE
CSV.read renames columns

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#281]
This is a regression (in old `CSV.read` the file was read in correctly).

```
julia> io = IOBuffer("""",",a\n",",a""")
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=11, maxsize=Inf, ptr=1, mark=-1)

julia> CSV.File(io)
CSV.File("<Base.GenericIOBuffer{Array{UInt8,1}}>", rows=1):
Tables.Schema:
 :_  Union{Missing, String}
 :a  Union{Missing, String}
```

and you can see that the first column name is incorrect (it should be `Symbol(",")`).

**Comment by quinnj** [comment]
This behavior was changed in https://github.com/JuliaData/CSV.jl/pull/256 so that column names are valid Julia identifiers and translate well when read into a DataFrame or when rows are accessed via getproperty. We could add a note when we do a new release that this behavior has changed.

**Comment by bkamins** [comment]
I think it would also be good to print a warning at least when reading in the data.

In particular `String(",")` is a fully valid column name for a `DataFrame`, the only limitation is that you cannot access it using `getproperty` but you have to use `df[Symbol(",")]` or column number syntax.

From my experience column names with space are common enough (e.g. for files exported from Excel - which is one of the most common sources of CSV files 😄) that we should not silently overwrite them.

**Comment by bkamins** [comment]
Or as it was noted in https://github.com/JuliaData/CSV.jl/issues/158 we might have a keyword argument to choose the behavior (and normalizing names could be the default).

**Comment by bkamins** [comment]
Ah - now I can see that this is exactly what was implemented in `CSV.File` via `normalizenames`. My bad. I guess you can close this issue if there is nothing more to add.

Thank you for all the work on this.

**Comment by quinnj** [comment]
Printing a warning might be good though, at least for a release or two so people aren't caught by surprise. What do you think @nalimilan?

**Comment by nalimilan** [comment]
Why not. Though people will easily find out what's going on. I guess @bkamins only filed an issue because he's aware of the design discussions around it. Most users would just adapt.

**Comment by bkamins** [comment]
Let me close this issue.
But I would recommend to list breaking changes in when the next is made as they are many and significant.
