### ISSUE TITLE
CSV.read not reading in the correct values in the csv file

### ISSUE THREAD

**Issue by caimichael** [JuliaData/CSV.jl#285]
When I try to read in a csv file (I converted it to a .xlsx so I could post it in this issue, but initially when I downloaded it from the Federal Reserve Bank of St. Louis FRED Database, it was a CSV), some of the values that are being read in when calling CSV.read are just completely wrong.

This issue is happening both in Julia v0.6 and Julia v0.7 on CSV versions 0.2.5 and 0.3.1 respectively on both Linux and OSX.
The deprecated method of readtable on Julia v0.6 still works correctly.

Here is a picture with the column DFF from calling "readtable" and DFF_1 from calling "CSV.read". You can see that some of the entries are completely different (specifically row 10 for instance).

<img width="318" alt="screen shot 2018-09-19 at 12 16 57 pm" src="https://user-images.githubusercontent.com/7290408/45766583-f2d98480-bc05-11e8-9013-1b6ff8096475.png">

I have attached the .xlsx version of the file below since Github doesn't allow .csv files as attachments, but you can also download the data directly from FRED at this link:
https://fred.stlouisfed.org/series/DFF
Where you need to select "Edit Graph" > Modify frequency to "Monthly" > Close that side pane > Download CSV (data).
[DFF.xlsx](https://github.com/JuliaData/CSV.jl/files/2397849/DFF.xlsx)

Also, attached are the versioninfo() outputs from the Linux and OSX versions of Julia.
![unnamed](https://user-images.githubusercontent.com/7290408/45766939-e1dd4300-bc06-11e8-8804-d804340b3c2d.png)
<img width="501" alt="screen shot 2018-09-19 at 12 16 33 pm" src="https://user-images.githubusercontent.com/7290408/45766880-b195a480-bc06-11e8-9702-83ab726d657f.png">

**Comment by Magalame** [comment]
I have exactly the same problem:

I have a csv file that a reduced for clarity. The reduced file contains the following:

````
9.171999999999999860e-04
9.271999999999999860e-04
9.202000000000000346e-04
9.292000000000000346e-04
9.393000000000000091e-04
````
(note that row 1 and row 2 differ by one digit, same for row 3 and row 4)

But when I try to parse it:

`data = CSV.read(DATAPATH,header=false,use_mmap=false)`

I obtain this:
````
0.0009172
-0.000917474
0.0009202
-0.000915474
-0.000905374
````

*But*, if I parse it as a string:
`data = CSV.read(DATAPATH,header=false,use_mmap=false,types=[String])`

It parses it well

````
9.171999999999999860e-04
9.271999999999999860e-04
9.202000000000000346e-04
9.292000000000000346e-04
9.393000000000000091e-04
````
