### ISSUE TITLE
delimiters inside quotes

### ISSUE THREAD

**Issue by gdkrmr** [JuliaData/CSV.jl#289]
the first comma inside the quotes is parsed as a delimiter.
```julia
julia> tmp = """ "a, b", "c" """ |>
       IOBuffer |>
       x -> CSV.File(x, header = false) |>
       DataFrame
1×3 DataFrame
│ Row │ Column1 │ Column2 │ Column3 │
│     │ String⍰ │ String⍰ │ String⍰ │
├─────┼─────────┼─────────┼─────────┤
│ 1   │  "a     │  b"     │  "c"    │
```

**Comment by quinnj** [comment]
Currently spaces before/after quote characters are not allowed (i.e. they must be immediately preceded/followed by delimiters). We can obviously consider changing this, but it's another case of bending parsing rules to account for non-standard csv formats.

**Comment by nalimilan** [comment]
@gdkrmr Do you know how other software handle this?

**Comment by gdkrmr** [comment]
This one is a real show stopper and I had to use `rcopy(R"""fread("file.csv")""")` to get around this, because you are the only performant CSV reader in Julia AFAIK. I was able to work around the other issues, e.g. `CSV.jl` sometimes adds extra spaces and forgets to remove the quoting characters.

> Currently spaces before/after quote characters are not allowed (i.e. they must be immediately preceded/followed by delimiters). We can obviously consider changing this, but it's another case of bending parsing rules to account for non-standard csv formats.

This one is about the comma inside the quotes being misinterpreted as a delimiter. 

> @gdkrmr Do you know how other software handle this?

There is `CSVFiles.jl`, which seemed to work, but it is not performant. I finally used `RCall` and `data.table`, see solution above. `data.table` handles almost everything just fine and I never had to give much thought to any of this before. Also LibreOffice Calc imports almost all files just fine. If there is white space between quotes and delimiters, then both the quotes and the white space should be removed, this seems like the only sensible solution for me.

Over the course of the last week I had to read in some pretty complicated csv [files](http://databank.worldbank.org/data/download/WDI_csv.zip) and I think you should generally imitate what `data.table`/`tidyverse` do in R, because "non-standard" csv is probably more common than "standard" csv as soon as it encodes more than a numeric matrix, even my bank emits bad csv. Is there even something like an official csv standard?

**Comment by quinnj** [comment]
> This one is about the comma inside the quotes being misinterpreted as a delimiter.

No, the problem here is the whitespace that starts a field. If a field doesn't begin and end with the `quotechar`, then it is _not_ considered a quoted field and will be parsed as is, with delimiters and newlines being interpreted as layout signals. 

There is a [spec](https://tools.ietf.org/html/rfc4180) and we adhere to it (except we currently have a default `escapechar='\\'` instead of `'"'`, but we've also talked about changing this).

**Comment by nalimilan** [comment]
FWIW, looks like readr has the same problem: https://github.com/tidyverse/readr/issues/823
