### ISSUE TITLE
On column name transformations

### ISSUE THREAD

**Issue by gdkrmr** [JuliaData/CSV.jl#295]
On current master you automatically transform column names so that the symbol representation in Julia is simpler (`:a_b` instead of `Symbol("a b")`).

I guess R did this for the same reason you changed the standard behaviour, i.e. to facilitate `df.column` notation, `df$column` in R. The `data.table`/`readr` packages changed the base `R` behaviour, the `data.table` way is much more predictable and therefore easier to use. 
Seeing these parallels and that the newer `R` packages reversed this, you may want to reconsider this change.

Other remarks:
- The current transform you use also fails if the column name consists solely of numbers (`"2017"` becomes `Symbol("2017")` on current master, base `R` used to solve this by prepending the letter `X`, e.g. `"2017"` becomes `X2017`).

- add the following functions:
```julia
function simplify_symbol(x)
    x |> String |> x -> replace(x, " " => "_") |> Symbol
end

function simplify_column_names!(x)
    names!(x, simplify_symbol.(names(x)))
end
```

**Comment by quinnj** [comment]
Is there a request here? You mention that `data.table` does something different than base `R`, but you failed to explain what they do "more predictably". You also mention newer `R` packages reversed this, what does that mean? Which R packages? What did they reverse?

**Comment by nalimilan** [comment]
I hadn't realized that neither data.table nor readr (which are the "newer packages" compared to base R) normalize column names. And AFAICT Pandas doesn't either. So we should probably do the same thing, with an argument to enable normalization.

**Comment by gdkrmr** [comment]
> Is there a request here?

- This is not a real request, I think this is something that the package maintainers have to decide. My intention was to explain what happened in R so you can avoid similar mistakes in CSV.
- The most important thing is to be stable, changing everything from `:a_b` to `Symbol("a b")` is quite annoying, so you should take a decision and stick with it.

> You mention that data.table does something different than base R, but you failed to explain what they do "more predictably". You also mention newer R packages reversed this, what does that mean? Which R packages? What did they reverse?

sorry if this wasn't clear: base `R` normalizes column names so that the symbol representation is more readable (`df$a.b`), while all the newer packages (`data.table`, `readr`) do not (`df$'a b'`, these should be backticks).

**Comment by gdkrmr** [comment]
I forgot to add:
- I don't really want to tell you what to do with this because I do not know the reasons behind `data.table` and `readr` not following standard R behavior.

- "more predictable" means that in a one to one translation for column names is easier and simpler than even the simplest normalization and over time I got so used to the `data.tables` behaviour that I do not know the exact rules that R uses to normalize column names.

**Comment by nalimilan** [comment]
@hadley Sorry to bother you with this, but would you mind telling us whether your experience with not normalizing column names in readr's `read_csv` is positive? I would have expected users to get confused a lot by non-standard names that cannot be used with the `df$col` syntax.

Some history of discussions about invalid names in DataFrames:
https://github.com/JuliaData/DataFrames.jl/issues/899
https://github.com/JuliaData/DataFrames.jl/pull/559
https://github.com/JuliaData/DataFrames.jl/issues/617
https://github.com/JuliaData/DataFrames.jl/issues/637

The most recent one:
https://github.com/JuliaData/DataFrames.jl/issues/1348

**Comment by hadley** [comment]
I think transforming a header row to syntactic names is a bad idea because often the header row is not column names, but is instead data — and if the header row is full of non-syntactic names, it's particularly likely to be data. I think it's better to require that the user explicitly ask for a transformation, either with an argument that defaults to not transforming, or with another function.

You can see our latest thinking about this behaviour in https://github.com/tidyverse/tibble/issues/445 — we'll have new behaviour in the next version of tibble, and it will slowly roll out throughout the rest of the tidyverse.

**Comment by nalimilan** [comment]
Thanks for the pointers! We have decided not to support duplicate names in tables in general, which is consistent with the default you retained (allowing them as an option would be difficult since Julia's named tuples currently require names to be unique too). Our data frames never "repair" names automatically. The only place where this happens by default is reading CSV files (this issue), which we could change.

**Comment by quinnj** [comment]
Yes, big thanks @hadley for chiming in; great to hear your perspective on this. I've changed the default to `normalizenames=false`, so it will be less surprising for users in the default case. I do think it's handy having the option to normalize, if the users wants/needs that.

**Comment by gdkrmr** [comment]
1) there should be a function to normalize the column names after the fact.
2) normalization of column names like `2001` did not work properly, R normalizes to `X2001`

**Comment by quinnj** [comment]
> there should be a function to normalize the column names after the fact.

CSV.jl can't really do much w/ column names once you've read the file into a different sink; if it's in a DataFrame, then DataFrames.jl provides (I'm pretty sure) a way to normalize the column names. If it's an SQLite table, you'll have to run a SQL statement yourself to normalize the names. In any case, you're always free to call `CSV.normalizename(name::String)` from your own code if you'd like the normalizing behavior.

> normalization of column names like 2001 did not work properly, R normalizes to X2001

??
```julia
julia> CSV.normalizename("2001")
:_2001
```

**Comment by nalimilan** [comment]
> CSV.jl can't really do much w/ column names once you've read the file into a different sink; if it's in a DataFrame, then DataFrames.jl provides (I'm pretty sure) a way to normalize the column names.

I don't think we do, but we could certainly provide such a function. Maybe `normalizename` could be moved to Tables.jl so that all packages that need it can use the same rules.
