### ISSUE TITLE
Error thrown after reading 100 lines

### ISSUE THREAD

**Issue by akazachk** [JuliaData/CSV.jl#298]
Hello everyone, I'm new to Julia and a little stuck reading in a csv file. Sorry if this question has already been answered (it seems related to issues [#156](
https://github.com/JuliaData/CSV.jl/issues/156) and [#248](https://github.com/JuliaData/CSV.jl/issues/248) but the comments there did not seem to help). I am working with Julia 1.0.0. The issue appears to arise when there is a column that has missing values in the first 100 rows, but afterwards it has a non-missing value. An example file is attached.

To read the file in, I am calling ```CSV.read("test.txt")```. Adding ```allowmissing=:all``` does not help. The error thrown is `ERROR: MethodError: Cannot convert an object of type WeakRefStrings.WeakRefString{UInt8} to an object of type Missing`.

[test.txt](https://github.com/JuliaData/CSV.jl/files/2409051/test.txt)

**Comment by gdkrmr** [comment]
Specify the type of the column:
```julia
DataFrame(CSV.File("test.csv", types = Dict(:column_name => Union{Float64, Missing}))
```

**Comment by quinnj** [comment]
On master, you probably don't need to specify the column type as the type inference algorithm has improved significantly.

**Comment by akazachk** [comment]
The types trick does work, though I am still using `CSV.read`. I think I am on master, but `CSV.File` is not recognized (at least in REPL). So I must be doing something wrong...

I find it curious that having exactly 100 lines with missing values causes an error, while having 99 lines (or fewer) does not.
