### ISSUE TITLE
Project 0.5

### ISSUE THREAD

**Issue by quinnj** [JuliaData/CSV.jl#30]
This issue is for tracking progress towards the next major release, corresponding to the broader release of Julia 0.5:

- [x]  Rewrite high-level functions of the form `CSV.read(io_or_file, sink, args...; kwargs...)` and `CSV.write(io_or_file, source, args...; kwargs...)`
- [x] Add tests for reading to: DataFrame, CSV.Sink, SQLite.Sink, Feather.Sink, ODBC.Sink, Domo.Sink
- [x] Test write from: DataFrame, CSV.Source, SQLite.Source, Feather.Source, ODBC.Source, Domo.Source
- [x] Ensure tests pass on 0.4 & 0.5
- [x] Add benchmarks for reading/writing to/from DataFrames vs. R's fread/fwrite and pandas dataframes, run benchmarks through Travis, commit results to perf/historical directory
- [x] Update docs to include an examples + guid page, in addition to the "reference" page

**Comment by asbisen** [comment]
Hi @quinnj, I was wondering if Feather.Sink is implemented? The following code using `CSV.Sink` works but the reverse does not

``` julia
s=CSV.Sink("t.csv")
Feather.read("Formaldehyde.feather", s)
```

but performing the reverse operation from CSV to Feather does not

``` julia
s=Feather.Sink("t.feather")
CSV.read("./formaldehyde.csv", s)
ERROR: ArgumentError: `source` doesn't support the supported streaming types of `sink`: DataType[DataStreams.Data.Column]
 in stream!(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Feather.Sink, ::Bool) at /Users/abisen/.julia/v0.5/DataStreams/src/DataStreams.jl:128
 in #read#21(::Bool, ::UInt8, ::UInt8, ::UInt8, ::String, ::Int64, ::Int64, ::Array{DataType,1}, ::Bool, ::Base.Dates.DateFormat, ::Int64, ::Int64, ::Int64, ::Bool, ::CSV.#read, ::String, ::Feather.Sink) at /Users/abisen/.julia/v0.5/CSV/src/Source.jl:297
 in read(::String, ::Feather.Sink) at /Users/abisen/.julia/v0.5/CSV/src/Source.jl:293
```

**Comment by quinnj** [comment]
Hey @asbisen, sorry I somehow missed your comment here. I believe there was a transition time where Feather didn't support streaming with CSV, but this should be fixed on the latest releases of both CSV and Feather. Let me know if you have any issues there!
