### ISSUE TITLE
missingstring ignored?

### ISSUE THREAD

**Issue by lbilli** [JuliaData/CSV.jl#306]
On `CSV 0.4.0`, if I run

```
using CSV, DataFrames
txt = """
       a,b
       1,2
       3,4
       """;
CSV.File(IOBuffer(txt), missingstrings="1") |> DataFrame
```
I get this:
```
2×2 DataFrame
│ Row │ a      │ b      │
│     │ Int64⍰ │ Int64⍰ │
├─────┼────────┼────────┤
│ 1   │ 1      │ 2      │
│ 2   │ 3      │ 4      │
```
It seems that single char missingstrings are ignored.

**Comment by lbilli** [comment]
So, I guess, cases where special values are used instead of missing values (like `-1` or `99999`) need to be manually postprocessed by the user.

**Comment by quinnj** [comment]
Currently yes, but it seems like something we should change; I'll look into it.

**Comment by quinnj** [comment]
Oh cool, it recognized my Parsers.jl commit fixed the issue here. Turns out we were already doing the right thing for Dates/Strings, just not other type parsers (Int, Float, Bool). It was also a pretty easy fix, so definitely the right call here. Thanks for reporting.

**Comment by lbilli** [comment]
Thanks for the fix and quick response. So far it's handled correctly all the cases I tried.

I don't know the spec requirements nor have I thought about corner cases, but I would have thought the logic to be along these lines:
- if any sentinel (empty string or otherwise) is matched and end-of-field is reached (i.e. no chars left), then `missing`
- else, try to parse a value. If it fails it's an `error` otherwise it's a valid value
