### ISSUE TITLE
Parsers depencency problem after release

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#307]
This is a warning I am getting when using CSV 0.4.0:

```Package CSV does not have Parsers in its dependencies```

see cell [2] in:
https://github.com/bkamins/Julia-DataFrames-Tutorial/blob/master/04_loadsave.ipynb

**Comment by quinnj** [comment]
Just waiting on https://github.com/JuliaLang/METADATA.jl/pull/18413
