### ISSUE TITLE
remove seekstart

### ISSUE THREAD

**Issue by iwelch** [JuliaData/CSV.jl#311]
https://discourse.julialang.org/t/csv-write-to-unix-pipe-e-g-lz4-or-bzip2/15759

seekstart should not be called on `Process`, so that we can pipe in the results of a Unix decompressor.

**Comment by bkamins** [comment]
@quinnj 
See also: https://stackoverflow.com/questions/52590792/how-do-i-read-a-gzipped-csv-file-in-julia
for the same class of problem with `position` not supported by certain `IO`.
