### ISSUE TITLE
CSV.read no longer works with `Callable`

### ISSUE THREAD

**Issue by morris25** [JuliaData/CSV.jl#322]
Previously it was possible to do
```CSV.read(file, transforms=Dict{String, Callable}("column_name" => Symbol))```
which was extremely convenient, but now the `transforms` only accepts `Function`s. It would be nice to see the previous behavior reinstated.

**Comment by quinnj** [comment]
Sorry about that; should be fixed on master now. Let me know if you any any other issues.

**Comment by morris25** [comment]
Thanks!

**Comment by quinnj** [comment]
Test being added in https://github.com/JuliaData/CSV.jl/pull/336
