### ISSUE TITLE
segfault after importing CSV and Images, PyPlot from a separate module

### ISSUE THREAD

**Issue by MaxandreJ** [JuliaData/CSV.jl#328]
Hi,

I get the following segfault
```
signal (11): Segmentation fault: 11
in expression starting at /MyProjectDirectory/Test.jl:4
_platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
```

when I run `/MyProjectDirectory/Test.jl` which contains the code
```
push!(LOAD_PATH, "/MyProjectDirectory")
import CSV
using MyModule
```

that uses `/MyProjectDirectory/MyModule.jl` which contains the code
```
module MyModule
using Images
import PyPlot
end
```

I don't know if this is an issue to do with CSV, Images, PyPlot or Julia itself. This is a minimal working example. I'm using Julia 1.0.1 on MacOS Mojave.

I hope this can be resolved soon! Segfaults are frightening...

PS: These are the versions of the packages in question + important dependencies
```
Images v0.16.0
PyCall v1.18.5+ #Master (https://github.com/JuliaPy/PyCall.jl.git)
PyPlot v2.6.3
CSV v0.4.1
```

PPS: I have also posted this issue on the [`PyPlot.jl` github](https://github.com/JuliaPy/PyPlot.jl/issues/402) and the [`Images.jl` github](https://github.com/JuliaImages/Images.jl/issues/759).

Best,
Max

**Comment by nalimilan** [comment]
Does the crash go away if you avoid loading one of these three packages? Can you try starting Julia with `--check-bounds=yes`?

**Comment by MaxandreJ** [comment]
Hi, thank you for answering! 

Yes, the segfault goes away if I don't load any one of these three packages. 

There is still a segault if I start Julia with `--check-bounds=yes`.

**Comment by MaxandreJ** [comment]
I've added the version numbers of the packages in question in the main post.

**Comment by MaxandreJ** [comment]
Yes, I do.

**Comment by nalimilan** [comment]
Then maybe it's not CSV's fault. That's not for certain, but the package has changed a lot since then. Also report this to other involved packages, especially the Python ones, which are much more complex than CSV (which is pure Julia).

**Comment by MaxandreJ** [comment]
Okay, I will! Thanks!

**Comment by quinnj** [comment]
Feel free to ping me here if this is still an issue, but closing for now.
