### ISSUE TITLE
`size(::File)` is two dimensional

### ISSUE THREAD

**Issue by andyferris** [JuliaData/CSV.jl#339]
I note that `size` and `length` of a `CSV.File` don't seem to agree.

Generally, these properties relate to iteration, e.g. `length(x) == prod(size(x))` and if there is a `size` then `IteratorSize` is `HasShape`, and these things are picked up by `collect` and so-on. The status quo seems a bit inconsistent.

I'm bringing this up because I'd like to introduce multi-dimensional tables that `HasShape` (e.g. an `AbstractMatrix` of `NamedTuples` can neatly represent the Cartesian join of two tables), and therefore use `size` in the same way as `Base` throughout the *Tables.jl* ecosystem.

**Comment by quinnj** [comment]
Already fixed in current release
