### ISSUE TITLE
Parsing error (I believe)

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/CSV.jl#34]
I'm trying to read the following file:
````
Name,Age,Children
John, 38., 3
Sally, 23., 1
Kirk, 64., 5
````
and get this:
````
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc2+0 (2016-08-12 11:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using CSV

julia> x = CSV.Source("data.csv")
CSV.Source: data.csv
    CSV.Options:
        delim: ','
        quotechar: '"'
        escapechar: '\\'
        null: ""
        dateformat: Base.Dates.DateFormat(Base.Dates.Slot[],"","english")
Data.Schema:
rows: 3 cols: 3
Columns:
 "Name"      WeakRefString{UInt8}
 "Age"       Float64
 "Children"  Int64

julia> Data.getfield(x,Float64,1,2)
ERROR: CSV.CSVError("error parsing a `Float64` value on column 2, row 1; encountered 'J'")
 in checknullend at C:\Users\anthoff\.julia\v0.5\CSV\src\parsefields.jl:52 [inlined]
 in parsefield(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Float64}, ::CSV.Options, ::Int64, ::Int64, ::Base.RefValue{CSV.ParsingState}) at C:\Users\anthoff\.julia\v0.5\CSV\src\parsefields.jl:126
 in getfield(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Type{Float64}, ::Int64, ::Int64) at C:\Users\anthoff\.julia\v0.5\CSV\src\Source.jl:195
````
I'm on master for CSV and DataStreams.

Am I using the API in the wrong way, or is this a bug?

**Comment by quinnj** [comment]
Yeah, the problem here is that the `CSV.Source` is "stateful", i.e. after you create it, it has an internal pointer at the beginning of row 1, column 1. `Data.getfield` then needs to be called in row-major order (for row 1, read each column, then row 2, each column, etc.). Does that make sense? I'm wondering how to make this more accessible/understandable......

**Comment by davidanthoff** [comment]
Yes, that makes sense and works well for my Query.jl case. I think just mention it in the DataStreams.jl documentation would be enough?

**Comment by quinnj** [comment]
Yeah, I'll mention it there and then in the CSV docs too for CSV.Source.

**Comment by davidanthoff** [comment]
Alright, Query.jl now supports any DataStream source. I'm just waiting to push that until you have tagged versions of the whole DataStreams universe that all work together.
