### ISSUE TITLE
TSV over CSV

### ISSUE THREAD

**Issue by mkborregaard** [JuliaData/CSV.jl#340]
In Julia, and in particular this package, comma-separated values files are treated as the "default" file format. This reflects a culture where CSV is treated as default, but that is not international, but only restricted to some countries.

At the heart of it, the comma is the worst possible column separator in countries where the decimal separator is also a comma. Here's a world map of those countries (light green is comma, blue [former British colonies + China] is dot, red and dark green something else):

![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/DecimalSeparator.svg/940px-DecimalSeparator.svg.png)

This makes it either impossible to have data with floating point values (not really an option), or forces everyone to adopt the English dot decimal separator. While good things can be said on just converging on a standard (like we all speak English on Github), it's not as simple as that. For apps like Excel, the way to force English dot separator is to set your computers global locale settings to UK/US, which is first of all very inconvenient, second, most people aren't going to do it. Indeed in e.g. excel, if you open a csv file on a non-English locale and save it back to csv again, Excel will automatically save it using semicolons as column separators! - which is of course Excel's problem, but just illustrates that this is not easily resolved by just arguing that everyone must adopt the English standard.

There's another issue with comma separation, and that is that it makes it impossible to have any natural language (such as notes) in data sets, because natural language often have commas.

Fortunately there exists a standard, which is the standard format in countries with comma decimal separator, that has none of the above problems, is international, and actually makes for much more human-readable text files: the tab-separated value. I'd suggest adopting this standard whereever possible in Julia.

I think many people don't realize just how nice it is for all of us in non-English countries that Julia has adapted UTF-8 as the standard over ASCII - in any other language I've used, strings of natural language (in my case mostly geographic place names) are a constant headache, but not so in Julia. It really underlines that Julia is a language of the present and future in a globalized world. No, seriously.

My most wide-reaching suggestion would be to rename this package TSV instead of CSV. A more basic suggestion is to use tabs instead of commas as the default separator, so that you have to specify the separator explicitly if you want commas. This makes even more sense, as in half the world, `csv` means "semicolon-separated values", so it is natural to expect the user to choose which one. The very minimal suggestion would be to have CSV automatically use tab-separation in `read` and `write` when the file extension is `.tsv` (and possibly `.txt`) (`CSVFiles` does that, and `DataFrames.readtable` used to do that too).

R solves this issue by having `read.table`, `read.delim`, `read.delim2`, `read.csv`, `read.csv2` etc. But - I don't think that's an example to emulate.

**Comment by SimonDanisch** [comment]
>A more basic suggestion is to use tabs instead of commas as the default separator

why are we not funding this!? :D Seems like a much better separator!

**Comment by nalimilan** [comment]
I agree we should either provide "CSV2" variants or (probably better) detect the separator automatically. FWIW, data.table's `fread` function does that, so it's not that crazy:
```
     sep: The separator between columns. Defaults to the character in
          the set ‘[,\t |;:]’ that separates the sample of rows into
          the most number of lines with the same number of fields. Use
          ‘NULL’ or ‘""’ to specify no separator; i.e. each line a
          single character column like ‘base::readLines’ does. 
```

**Comment by Nosferican** [comment]
Any update on automatically inferring the `delim` based on file extension for `tsv`? I have adopted `tsv` as the standard for the ecosystem I a working on so it would be nice to drop the `delim = '\t'` for the tutorials. If it is straightforward I can probably cook the PR.

**Comment by davidanthoff** [comment]
[CSVFiles.jl](https://github.com/queryverse/CSVFiles.jl) automatically uses ``\t`` if the file extension is ``tsv``, you could check that out if this is important to you.

**Comment by mkborregaard** [comment]
I think it might be meaningful to also infer it automatically as suggested by @nalimilan above, but I think the heuristic is poorly chosen. IIUC this would split
```
12,345\t23,231
35,231\t43,121
```
into
```
12    345\t23    231
35    231\t43    121
```
instead of
```
12.234    23.231
35.231    43.121
```

**Comment by nalimilan** [comment]
The detection rule I proposed would only apply to distinguish CSV files from CSV2 files, i.e. to choose whether the separator is `,` or `;`. TSV files can be detected using the extension.

**Comment by mkborregaard** [comment]
OK, makes sense.

**Comment by Nosferican** [comment]
I think it might be best to have the 5-lines rules for `.txt` files. `.cvs` and `.tsv` should probably have the implied delimiters by file extension.

**Comment by Nosferican** [comment]
With #365 merged, we now have autodetect for `tsv`, `csv`, and `wsv`. `txt` files default to `,`, but that could be modified once the auto-detect is implemented.

**Comment by mkborregaard** [comment]
That's great! To my mind this does not close the issue, but it does make it a lot easier for users to work around.

**Comment by quinnj** [comment]
So what exactly is the ask here?

**Comment by mkborregaard** [comment]
That tab separated be the default

**Comment by Nosferican** [comment]
The default now is auto-detect, but tab is the default for `.tsv`. Best practices would be to save tab-separated values as `.tsv` rather than `.txt` or `.text`.

**Comment by mkborregaard** [comment]
Hm that sounds like the issue is actually now closable :-)

**Comment by quinnj** [comment]
I don't think we need to be in the business of appending file extensions when writing. Closing.

**Comment by Nosferican** [comment]
My comment is relating to the fact that if people saved their data with tab-delimited and named as such (e.g., `filename.tsv`) CSV.jl will read it correctly by default now as opposed to before.

**Comment by mkborregaard** [comment]
Thanks again guys 💖
