### ISSUE TITLE
Incorrect reading of IOStream to DataFrame

### ISSUE THREAD

**Issue by clintonTE** [JuliaData/CSV.jl#344]
Wrapping the read in an IOStream prevents Julia from properly reading a CSV as a dataframe. This makes CSV almost unusable for me since I typically work with compressed CSV files (eg. using GZIP.jl). 

The bug didn't really seem sensitive to file particulars, but a zipped version of one of the files it breaks on is attached (couldn't attach the unzipped file on github). I tried a few different reading options and couldn't get it to work.

[NCCSMetaIndex.zip](https://github.com/JuliaData/CSV.jl/files/2523106/NCCSMetaIndex.zip)

This is on Julia 1.01:

```
using DataFrames, CSV

function mwe()
  someFile::String = "NCCSMetaIndex.csv"

  iStream::IOStream = open(someFile)
  df::DataFrame = CSV.read(iStream)
  close(iStream)
  println("Size: $(size(df))")

  df = CSV.read(someFile)
  println("Size: $(size(df))")
end

mwe()
```

Output:
Size: (0, 1)
Size: (89, 9)

**Comment by clintonTE** [comment]
Found a workaround. Wrapping the stream in an IOBuffer as below did the trick. I'll leave the issue open since I imagine the behavior in the original post is not as intended.

```
using DataFrames, CSV

function mwe()
  someFile::String = "NCCSMetaIndex.csv"

  iStream = IOBuffer(read(open(someFile)))
  df::DataFrame = CSV.read(iStream)
  close(iStream)
  println("Size: $(size(df))")

  df = CSV.read(someFile)
  println("Size: $(size(df))")
end

mwe()
```

**Comment by quinnj** [comment]
Thanks for the report @clintonTE; somewhat baffling (and embarrassing), is we somehow didn't have a single test in CSV.jl or Parsers.jl that did csv reading from an IOStream. Sheesh. Sorry about that. A new release for Parsers.jl was just made; once that get's merged, then this should work as expected.

**Comment by clintonTE** [comment]
Thanks for the fast turnaround! It speaks well for the community that bugs like this get fixed so quickly once reported.
