### ISSUE TITLE
CSV drops first character of quoted fields when reading via an IOStream

### ISSUE THREAD

**Issue by clintonTE** [JuliaData/CSV.jl#345]
Title basically says it all. Quoted fields lose their first character when they are read in this specific manner.

Data file (zipped):
[mwe.zip](https://github.com/JuliaData/CSV.jl/files/2544436/mwe.zip)

```
using CSV, DataFrames

function mwe()
  local df::DataFrame
  local b::IOBuffer

  iStream = open("mwe.csv")
  df = CSV.read(iStream)
  println("This is using open: $(df[:NAME])")
  close(iStream)

  iStream = open("mwe.csv")
  b = IOBuffer(read(iStream))
  df = CSV.read(b)
  println("This uses an IOBuffer: $(df[:NAME])")
  close(iStream)

  df = CSV.read("mwe.csv")
  println("This is direct: $(df[:NAME])")
end

mwe()
```
Output:
This is using open: Union{Missing, String}["ALLAS BLACK DANCE THEATRE4", "EARTHSHARE", "OCUS LEARNING ACADEMY INCORPORATEDU", "UNT RITAS FOUNDATIONY"]
This uses an IOBuffer: Union{Missing, String}["DALLAS BLACK DANCE THEATRE", "EARTHSHARE", "FOCUS LEARNING ACADEMY INCORPORATED", "AUNT RITAS FOUNDATION"]
This is direct: Union{Missing, String}["DALLAS BLACK DANCE THEATRE", "EARTHSHARE", "FOCUS LEARNING ACADEMY INCORPORATED", "AUNT RITAS FOUNDATION"]

Version Info:
```
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = "C:\Users\Clinton\AppData\Local\atom\app-1.32.1\atom.exe" -a
  JULIA_NUM_THREADS = 6
```

**Comment by quinnj** [comment]
Thanks for the detailed report! Got the fix in Parsers.jl and tagged a new release here: https://github.com/JuliaLang/METADATA.jl/pull/19284.

**Comment by clintonTE** [comment]
Your welcome! I'm glad it was helpful.
