### ISSUE TITLE
Would it make sense to register CSV.jl with FileIO?

### ISSUE THREAD

**Issue by dmbates** [JuliaData/CSV.jl#36]
The `FileIO` package allows for various extensions to be registered to invoke other packages' read routines when encountered.  Would it make sense to register `CSV.read` for the `.csv` extension and possibly others like `.tsv`?  That way 

```
load("myfile.csv")
```

could be used instead of remembering whether the call is `CSV.read` or `read_csv` or `readtable` or ...

**Comment by nalimilan** [comment]
That would be nice, but we'd have to choose why kind of object to return. A `DataFrame`?

**Comment by dmbates** [comment]
Yes, it should return whatever `CSV.read("mycsvfile.csv")` would return.  i.e. use the defaults for all other arguments.

**Comment by davidanthoff** [comment]
Couldn't it just return a ``DataStreams.Sink`` type? If you wanted a ``DataFrame``, you could use something like ``DataFrame(load("myfile.csv"))``?

**Comment by quinnj** [comment]
If someone wants to take this up, feel free, but I don't personally have a strong use-case.

**Comment by davidanthoff** [comment]
Note also that you can read CSV, Feather, Excel, Stata, SPSS and SAS files via FileIO.jl today, I integrated all of that with IterableTables.jl. So ``DataFrame(load("filename.ext"))`` and ``load("filename.ext") l> DataFrame`` work for all those file extensions. Saving also works for CSV and Feather files.
