### ISSUE TITLE
incorrect docstring signature for CSV.write

### ISSUE THREAD

**Issue by tpapp** [JuliaData/CSV.jl#360]
In [this line](https://github.com/JuliaData/CSV.jl/blob/db92782153b1f67151c3180381bd7d6a658c354b/src/write.jl#L2), `file` appears twice, as
```julia
    CSV.write(file::Union{String, IO}, file; kwargs...) => file
```
This is also rendered in the generated documentation.

**Comment by quinnj** [comment]
This is fixed on master
