### ISSUE TITLE
CSV file not-roundtrippable if a value contains a quote

### ISSUE THREAD

**Issue by yurivish** [JuliaData/CSV.jl#369]
It seems that quotes (`"`) are not escaped on write, which confuses the reading machinery to the point that it omits any lines after the offending line with the quote. Minimal reproduction (you can also remove the `escapechar` designation, which has no effect here):
```
using CSV
CSV.write("bug.csv", [(a="one", b="two"), (a="th\"ree", b="four"), (a="five", b="six")], escapechar='☃')
CSV.read("bug.csv")
```

The file as read back contains only the first 2 rows rather than the full 3 rows in the file.

The contents of bug.csv after the write are:
```
a,b
one,two
th"ree,four
five,six
```

**Comment by quinnj** [comment]
Ah, I think we need an extra validation step here; only ascii characters are supported for `escapechar`; I'll add an argument check so that this case throws an informative error instead.
