### ISSUE TITLE
Support parsing to PooledArrays

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/CSV.jl#378]
It's been requested several times that we support parsing strings to PooledArrays. That would be more appropriate than CategoricalArray in many situations, and it would be much more efficient (especially for grouping) than `Vector{String}`.

In terms of implementation, it should be quite similar to CategoricalArrays, but there's a difficulty. While we can simply use `CategoricalValue` to carry the information about the parsed value *and* about the type of the column to allocate, there's no equivalent for PooledArrays (which is the whole point of having two packages). I can see two approachs:
- Define a custom `PooledString <: AbstractString` type which would be almost identical to `CategoricalString`, but would be used to indicate that a `PooledArray` should be allocated to store the result. This is my preferred approach.
- Don't use a wrapper when streaming `CSV.File`, but find a way to indicate to `CSV.read` which columns should be `PooledArray`. This would have the drawback that it would be impossible to use when streaming.

**Comment by matthieugomez** [comment]
Thanks for opening this @nalimilan!

**Comment by quinnj** [comment]
Implemented in #395
