### ISSUE TITLE
Cannot clone CSV Julia 1.10

### ISSUE THREAD

**Issue by Jeffguitarhero** [JuliaData/CSV.jl#393]
![image](https://user-images.githubusercontent.com/39103818/54729769-5c096880-4b53-11e9-840f-ad62aa31a2ac.png)

Are you familiar with the issue?

Thanks

**Comment by nalimilan** [comment]
Looks like a problem with ASTInterpreter2 and/or Atom rather than CSV.

**Comment by quinnj** [comment]
Yeah, this sounds like a better issue to post on discourse or discuss in https://julialang.slack.com/messages/C67EFTEF3/convo/C674VR0HH-1556287323.042400/ if it's still an issue for you.
