### ISSUE TITLE
Add some examples to the documentation

### ISSUE THREAD

**Issue by galenlynch** [JuliaData/CSV.jl#399]
Even though I use CSV.jl quite often and have gotten used to working with it, I think its documentation is very opaque, and seems to be written for other library developers instead of users. Simple, first order questions like "How do I access the data in a CSV file?" have no obvious answer in the documentation. I think the only thing in the documentation that speaks to how data is accessed, without the use of other packages, is:

> CSV.Row supports propertynames and getproperty to access individual row values.

In reality, it seems like CSV.jl is meant to be used only in conjunction with other packages, which should probably be more explicit. The following line in the documentation hints at this, but it's not clear that it's the only supported solution:

> By supporting the Tables.jl interface, a CSV.File can also be a table input to any other table sink function.

Even the examples that follow that line, which use a DataFrame and SQLite, don't explicitly show how the data in a file would be accessed. Furthermore, the documentation for Tables.jl is also opaque, so referring readers to the documentation there is not helpful, in my opinion.

FWIW, I often use CSV.jl for simple tasks, and turn to using the relatively obscure `columntable` function in Tables.jl to return a `NamedTuple` of the file contents. I think it would be great if this path, which gives you the data from a file in a uncomplicated type from base Julia, were better documented.

**Comment by nalimilan** [comment]
A PR to improve the docs would certainly be welcome!

**Comment by galenlynch** [comment]
Thank you!
