### ISSUE TITLE
Pkg.test() on windows with Julia-0.5 fails

### ISSUE THREAD

**Issue by mdpradeep** [JuliaData/CSV.jl#40]
`Pkg.test("CSV")` on windows fails. If the file type of the following files are modified to `unix`, then the tests pass.
```
baseball.csv
stocks.csv
test_utf8.csv
test_single_column.csv
test_empty_file_newlines.csv
```

**Comment by quinnj** [comment]
Weird, because everything passes just fine on appveyor. https://ci.appveyor.com/project/quinnj/csv-jl-groth

**Comment by quinnj** [comment]
I've confirmed both locally and on appveyor that windows tests now pass. Will tag a new release soon.

Ref: https://ci.appveyor.com/project/quinnj/csv-jl-groth
