### ISSUE TITLE
Appveyor url is incorrect. 

### ISSUE THREAD

**Issue by aviks** [JuliaData/CSV.jl#41]
The appveyor link in the homepage points to https://ci.appveyor.com/project/JuliaData/documenter-jl/branch/master, which is clearly incorrect. 

I dont know what it should be, since https://ci.appveyor.com/project/JuliaData/CSV-jl seems to lead nowhere. Is this set up on appveyor at all?

**Comment by quinnj** [comment]
https://ci.appveyor.com/project/quinnj/csv-jl-groth
