### ISSUE TITLE
Performance difference of `DataFrame` vs `DataFrame!`

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#417]
Here is the code:

https://discourse.julialang.org/t/ann-new-csv-jl-0-5-release/23848/5

for group-by operation.

And here are additional benchmarks without grouping:
```
julia> @btime sum($df.x5);
  62.472 ms (1 allocation: 16 bytes)

julia> @btime sum($df2.x5);
  4.145 ms (1 allocation: 16 bytes)

julia> @btime count(==("a"), $df.g);
  194.988 ms (2 allocations: 32 bytes)

julia> @btime count(==("a"), $df2.g);
  65.090 ms (2 allocations: 32 bytes)

julia> @btime $df.x1-$df.x6;
  117.182 ms (2 allocations: 76.29 MiB)

julia> @btime $df2.x1-$df2.x6;
  33.331 ms (2 allocations: 76.29 MiB)
```

(in them also `df` is created via `DataFrame!` and `df2` is created via `DataFrame`)

You can see that the difference is significant (I have added one more benchmark in the edit)

CC @nalimilan

**Comment by nalimilan** [comment]
I imagine this is unavoidable since `CSV.Column` is row-major, right? There's a trade-off which depends on whether you expect to work with columns only once or multiple times (in which case copying may be worth it).

Given the additional issue that `CSV.Column` is read-only, which can confuse/annoy users, I'm tempted to say we should make copies by default. Or maybe deprecate `CSV.read` so that users have to choose between `DataFrame(CSV.File(...))` and `DataFrame!(CSV.File(...))`.

**Comment by bkamins** [comment]
> I imagine this is unavoidable

This was my point when we discussed this change. @quinnj mentioned that it is possible to improve the performance (in particular to make `@simd` work), but I think there is a limit to it and columnar storage will be always faster (you do not have to load unused data to CPU cache).

**Comment by quinnj** [comment]
In my initial performance comparisons, `CSV.Column` had no problem using simd for Int/Float types, which was the whole reason I felt ok moving forward in the first place. I'll dig in a bit tomorrow to do a more comprehensive performance comparison and see if there are tweaks to improve things.

**Comment by quinnj** [comment]
Ok, got some improvements coming in hot:
```julia
julia> @btime sum($df.x5);
  13.991 ms (1 allocation: 16 bytes)

julia> @btime sum($df2.x5);
  4.007 ms (1 allocation: 16 bytes)

julia> @btime count(==("a"), $df.g);
  79.931 ms (2 allocations: 32 bytes)

julia> @btime count(==("a"), $df2.g);
  69.326 ms (2 allocations: 32 bytes)

julia> @btime $df.x1-$df.x6;
  38.803 ms (2 allocations: 76.29 MiB)

julia> @btime $df2.x1-$df2.x6;
  22.243 ms (2 allocations: 76.29 MiB)
```

**Comment by quinnj** [comment]
I'm going to close this as I believe the performance gap has significantly improved.
