### ISSUE TITLE
Support multiple "null" strings

### ISSUE THREAD

**Issue by quinnj** [JuliaData/CSV.jl#42]

**Comment by holder66** [comment]
I would like this also; like the nastrings keyword argument in readtable.

**Comment by quinnj** [comment]
Do people really have strong use-cases for this? On the one hand, I understand the "hey, just check for a whole bunch of these possible null strings", but for performance, it can be really handy to only need to check a single string; I just haven't personally run across actual use-cases where there were multiple representations of null values in a single dataset.

**Comment by holder66** [comment]
A bunch of years ago I was working on a survey dataset which had a number of strings indicating various conditions, which I ultimately needed to treat as missing data: if I recall, -9, -99, -999 were representative of refused to answer, answer uninterpretable, out of bounds response, or some such. And this was in addition to empty fields!

Henry

**Comment by nalimilan** [comment]
> A bunch of years ago I was working on a survey dataset which had a number of strings indicating various conditions, which I ultimately needed to treat as missing data: if I recall, -9, -99, -999 were representative of refused to answer, answer uninterpretable, out of bounds response, or some such. And this was in addition to empty fields!

This is indeed very common, but usually I would handle this only after loading the data: the values indicating missingness for one variable (typically, categorical ones) may be valid for other ones (e.g. a continuous integer variable), so a massive replacement could corrupt the data.

**Comment by gizmaa** [comment]
I have seen plenty of bizarre error strings in programmatically collected data. My old Matlab code has these as values that must be treated as NaN's: "NAN","INF","-INF","1.#INF","-1.#IND","#NAME?". If I remember it correctly these were all found in numeric columns.

**Comment by nalimilan** [comment]
At https://github.com/JuliaData/CSV.jl/issues/160 it appeared that it would make sense to allow the `null` argument to be a dict mapping column names to strings which should be considered as missing for that column. I think Pandas supports this.

**Comment by quinnj** [comment]
This is supported on master with `CSV.File(file; missingstrings=[...])`.
