### ISSUE TITLE
File That Breaks CSV when Read

### ISSUE THREAD

**Issue by clintonTE** [JuliaData/CSV.jl#420]
CSV breaks when I read in the file below. Specifically it throws `ReadOnlyMemoryError()`.

The error seems to occur any way that I read the file, but the below serves as an example:
```
CSV.File("nccs.core2015pc_full990.csv") |> DataFrame!
```

I cannot seem to figure out why this file is failing. It works for similar files on the site.

The file is located here (sorry for the large size ~220mb):
https://nccs-data.urban.org/data/core/2015/nccs.core2015pc_full990.csv

Any idea for a workaround?

(Running Julia 1.1 on Windows)

**Comment by quinnj** [comment]
I can reproduce on linux; I'll dig in and try to figure out what's going on. Thanks for the report.

**Comment by clintonTE** [comment]
Confirmed that the file works now. @quinnj you are the man
