### ISSUE TITLE
`categorical=true` not working?

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CSV.jl#421]
If I understand the docs corrrectly , `categorical=true` means my string column should be a CategoricalVector, no?

```julia
(jjj) pkg> add CSV
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/jjj/Project.toml`
  [336ed68f] + CSV v0.5.0
  Updating `~/.julia/environments/jjj/Manifest.toml`
  [336ed68f] + CSV v0.5.0
  [a93c6f00] + DataFrames v0.18.2
  [69de0a69] + Parsers v0.3.3

julia> using CSV
[ Info: Recompiling stale cache file /Users/anthony/.julia/compiled/v1.1/CSV/HHBkp.ji for CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]

julia> df = CSV.read("iris.csv", pool=true, categorical=true)
150×5 DataFrames.DataFrame
│ Row │ sepal_length │ sepal_width │ petal_length │ petal_width │ target    │
│     │ Float64      │ Float64     │ Float64      │ Float64     │ String    │
├─────┼──────────────┼─────────────┼──────────────┼─────────────┼───────────┤
│ 1   │ 5.1          │ 3.5         │ 1.4          │ 0.2         │ setosa    │
│ 2   │ 4.9          │ 3.0         │ 1.4          │ 0.2         │ setosa    │
⋮
│ 149 │ 6.2          │ 3.4         │ 5.4          │ 2.3         │ virginica │
│ 150 │ 5.9          │ 3.0         │ 5.1          │ 1.8         │ virginica │

julia> typeof(df.target)
CSV.Column{String,PooledString}
```

**Comment by quinnj** [comment]
To get CategoricalVector, you also need to pass `copycols=true`. We can fix the documentation here.

**Comment by nalimilan** [comment]
Maybe we can ensure that categorical columns are copied automatically? One of the main points of keeping `categorical` was to avoid breaking existing uses.

**Comment by quinnj** [comment]
Yeah, maybe. I'd also like `CSV.Column{String, Pooledstring}` to act like a proper "pooled" array though too. If we do the `refarray`, `refpool`, `refvalue` interface in DataAPI.jl and have downstream packages do optimizations off that, then `CSV.Column{String, PooledString}` could be used directly for DataFrame grouping optimizations, for example.

**Comment by nalimilan** [comment]
Yeah, but that's mostly orthogonal to `categorical=true`. I think we should either have that argument work out of the box, or deprecate it and have them call `categorical!(df)` at the end. (Though even if we deprecate it it would be nice to have the deprecation working as in the previous release.)

**Comment by quinnj** [comment]
I've updated the docs for `categorical` for now to clarify. If we hear additional complaints/confusion, we can do something more involved.
