### ISSUE TITLE
Not detecting values as well as TableReader.jl on hflights

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#425]
The `DepTime` and `ArrTime` are detected as string but they should be detected as `Union{Integer, Missing}`.

```julia
download("https://github.com/xiaodaigh/testing/raw/master/hflights.csv", "hflights.csv")
using CSV
@time a = CSV.read("hflights.csv"); 
```

TableReader.jl seems to detect it correctly.
```julia
@time b = readcsv("hflights.csv"); 
```

**Comment by quinnj** [comment]
Can you share more details on what you expect here? Just saying broadly "not detecting values as well" isn't very helpful. Are there specific columns that seem to have their types misdetected? What are they detected as vs. what you expect?

**Comment by quinnj** [comment]
One thing I noticed just manually looking through the file is that several columns with lots of integers include values like `NA`; if those should be considered as `missing` values, then you can do `CSV.read(file; missingstring="NA")`. Maybe TableReader.jl considers `NA` to be `missing` by default? Hence the confusion?

**Comment by quinnj** [comment]
Closing as I don't think there's actually an issue here; please comment if otherwise
