### ISSUE TITLE
Provided types only partially interpreted?

### ISSUE THREAD

**Issue by Drvi** [JuliaData/CSV.jl#431]
Hi and thanks for the awesome package!

I was just upgrading to a new version of CSV and I noticed that the provided type info is not being interpreted exactly:
```julia
julia> DataFrame(CSV.File(IOBuffer("a,b\n1,2"), types = [Float32,UInt8]))
1×2 DataFrame
│ Row │ a       │ b     │
│     │ Float64 │ Int64 │
├─────┼─────────┼───────┤
│ 1   │ 1.0     │ 2     │
```

I do a lot of these explicit type conversions to save some space when working with large tables.

Please let me know if I can help with this..

CSV v0.5.2
Julia 1.1.0

**Comment by quinnj** [comment]
Yes, I was anticipating this would come up. The issue here is that during parsing we treat everything as Int64/Float64, and any input types are just converted to those. I think we could have a way to pass an `inttype=Int8` and/or `floattype=Float32` arguments that would control how int/float columns are handled. But maybe we could still figure out how to propagate the types to the resulting columns as well.

**Comment by nalimilan** [comment]
Disregarding how the data is stored internally, the `types` argument should be respected IMO.

**Comment by versipellis** [comment]
This is coming up as an issue for me.

I have a CSV with columns that require Int128, and this error gets thrown:
```
warnings: error parsing Int64 on row = 2, col = 1: "10000000000000000000000000000000,", error=INVALID: DELIMITED | INVALID_DELIMITER | OVERFLOW 
```

**Comment by quinnj** [comment]
Yeah, the case of `Int128` or `BigInt` are not ideal right now. You'd be better off doing something like:
```julia
df = CSV.File(filename; types=Dict(bigintcol=>String)) |> Tables.transform(bigintcol=x->Parsers.parse(BigInt, x)) |> DataFrame
```

**Comment by ExpandingMan** [comment]
Note that currently if you write e.g. `UInt64`, these will look like integers in the file, and by default it tries to read them back as `Float64`.  If you specify `types=Dict(col=>UInt64)` it apparently tries to read as `Int` and can get an overflow.

**Comment by sbromberger** [comment]
It'd be really great to get this working. For performance reasons, `UInt32` is an ideal data type for 99% of my work. I'd love to be able to read in UInt32s directly.

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaData/CSV.jl/pull/649

**Comment by Drvi** [comment]
Amazing! Thank you.
