### ISSUE TITLE
Memory usage for large files

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#432]
Following https://github.com/h2oai/db-benchmark/pull/85#issuecomment-491340029 we have an issue in H2O benchmarks for large files.

@quinnj - do you think it is related to a conversion using `DataFrame`? The error seems to indicate that we have a problem earlier.

**Comment by nalimilan** [comment]
So IIUC they are using a VM with 125GB of RAM and trying to load a 50GB CSV file. That should be enough to hold both the file contents and the tape in RAM.

**Comment by quinnj** [comment]
Is there a way to "retry" the benchmark to see if it's better on the latest 0.5.3 release? The most recent release should be a little better on memory pressure, but I'd like to know if we need to dig in further.

**Comment by bkamins** [comment]
If you want to reproduce the benchmark data exactly [here](https://github.com/h2oai/db-benchmark/blob/master/README.md) are the instructions in **Reproduce** section (but probably producing large files with structure similar to described [here](https://h2oai.github.io/db-benchmark/) will be good enough :)) - I never tried to reproduce the steps described in the official guide.

**Comment by nalimilan** [comment]
Apparently they ran the benchmarks on July 29th (so with recent package versions), and they still run out of memory.

**Comment by quinnj** [comment]
@bkamins, do you know if there's a way to provide the types explicitly for the h20 benchmark? If so, that would drastically improve the memory footprint with #510 merged.

**Comment by nalimilan** [comment]
I think we can basically make a PR to apply any changes we want at https://github.com/h2oai/db-benchmark/blob/master/juliadf/groupby-juliadf.jl#L23. They shouldn't object since the benchmark is about grouping, not CSV reading.

**Comment by nalimilan** [comment]
Oh, and do you think that without changing that line, https://github.com/JuliaData/CSV.jl/pull/510 may improve memory use enough that it may now work? We don't really need reading the data to be fast (it's not included in the benchmark), it just has to work.

**Comment by bkamins** [comment]
Yes - in general in H2O benchmark, we should change to the option that is most memory efficient for the larges data set case (it does not have to be the fastest). And any PR we would submit there should be accepted.

**Comment by bkamins** [comment]
H2O benchmark still produces "out of memory" due to CSV.File. See https://github.com/h2oai/db-benchmark/blob/7e178c1d2fb9102c8b12ac201f883981254a9df6/benchplot-dict.R#L171.
for the detailed list of offending tests

@quinnj - is anything still fixable here? Thank you!

CC @nalimilan

**Comment by nalimilan** [comment]
I've filed https://github.com/h2oai/db-benchmark/pull/119 to pass types explicitly, let's see whether that fixes the problem.

**Comment by quinnj** [comment]
This should be much better on master; a good optimization we should look into is passing the exact # of rows via `limit=rows` to ensure the row-estimation mechanism doesn't over-estimate too much (and hence over-allocate).

**Comment by bkamins** [comment]
:+1: 

Let us hope this makes 50GB H2O benchmarks go through!
