### ISSUE TITLE
CSV.write Cannot write Nothing

### ISSUE THREAD

**Issue by evveric** [JuliaData/CSV.jl#433]
```
df = DataFrame(d=[nothing])
CSV.write(raw"c:\temp\t.txt", df)
```

This has error

**Comment by quinnj** [comment]
Yeah, the question is what we should write/print for `nothing`. In Base, they made the decision that `nothing` shouldn't be printable. I think in the previous release, CSV.jl treated `nothing` like `missing`, so it just printed an empty field (or a provided null string). I guess we could go back to that behavior.

**Comment by quinnj** [comment]
@nalimilan, @bkamins, do either of you have an opinion here? Should we just treat `nothing` like `missing` when writing out a csv file?

**Comment by nalimilan** [comment]
I guess it would make sense to provide an option to choose the string to use for `nothing`, as for `missing`. A simpler solution would be to print it as `nothing`, as it seems Base is going to switch to that soon anyway https://github.com/JuliaLang/julia/pull/32148).

At any rate, `nothing` and `missing` should probably not be printed the same way by default, as it would make a round-trip lose information.

**Comment by quinnj** [comment]
Ok, I think I'd like to go with not supporting writing `nothing` in CSV files, with reasoning as follows:

* CSV.jl isn't really in the business of supporting custom types, particularly on the parsing side; so in that respect, it makes sense, at least for the moment, to restrict parsing ***and*** writing to the known set of basic types (date, datetime, time, int, float, bool, string)
* So this makes CSV.jl on the side of ***not*** being a "serialization" type package, and more of a dedicated "data format" package. That might change in the future, but for now, I think it makes sense and limits what we need to test/cover for
