### ISSUE TITLE
5.0+ builds create Pooled arrays which is impossible to modify

### ISSUE THREAD

**Issue by anj00** [JuliaData/CSV.jl#434]
Hello, for versions 0.5.0 - 0.5.2 I see the following code failing. whereas it works fine in 0.4.3
```
using CSV, DataFrames

#
# create larger DataFrames
#
data_str1 = "col1,col2\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\n"
data_str2 = "col1,col2\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\nS,T\r\n"

data1 = CSV.read(IOBuffer(data_str1); copycols = true)
data2 = CSV.read(IOBuffer(data_str2); copycols = true)

#fails here
#ERROR: MethodError: no method matching
#append!(::PooledArrays.PooledArray{String,UInt32,1,Array{UInt32,1}},
#        ::PooledArrays.PooledArray{String,UInt32,1,Array{UInt32,1}})
append!(data1, data2)
```
interestingly, for small enough datasets it actually works, the following code works fine. whereas the only difference is the size of the dataset
```
data_str1 = "col1,col2\r\nS,T\r\nS,T\r\nS,T\r\n"
data_str2 = "col1,col2\r\nS,T\r\nS,T\r\nS,T\r\n"

data1 = CSV.read(IOBuffer(data_str1); copycols = true)
data2 = CSV.read(IOBuffer(data_str2); copycols = true)

#this works fine
append!(data1, data2)
```

Any idea how I can fix it in my code or is it an issue in the CSV.jl?

**Comment by anj00** [comment]
Found a solution which works for me. `pool = false` parameter actually fully disables pooling.

`CSV.read(IOBuffer(data_str1); copycols = true, pool = false)`

**Comment by nalimilan** [comment]
`PooledArray` doesn't impleemnt `append!` currently, but https://github.com/JuliaComputing/PooledArrays.jl/pull/23 will fix that. Please report other missing methods to PooledArrays.jl.
