### ISSUE TITLE
StringArray columns returned when no pulling

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#435]
By default when the column contains strings and pulling is disabled the type of returned column is `WeakRefStrings.StringArray{String,1}`. This has two consequences:

* it surprises users (see eg https://github.com/JuliaData/DataFrames.jl/issues/1812#issuecomment-493400577) - who expect `Vector{String}`
* it has bad memory performance consequences if you later heavily mutate the vector (you can get out-of-memory problems, as the buffer grows with each change)

There are two things I would propose:
* improve the documentation (@quinnj you probably should know what is best to write :))
* discuss if we should provide some way to get a "normal" `Vector{String}` in the output.

**Comment by bkamins** [comment]
Another problem with `WeakRefStrings.StringArray{String,1}` is that it does not support `deleteat!`, which is needed in `filter!` in the DataFrames.jl package.

**Comment by nalimilan** [comment]
> Another problem with `WeakRefStrings.StringArray{String,1}` is that it does not support `deleteat!`, which is needed in `filter!` in the DataFrames.jl package.

AFAIK this has just been fixed by https://github.com/JuliaData/WeakRefStrings.jl/pull/61.

Regarding the memory issues, maybe `StringArray` should compress the buffer periodically from `setindex!` based on some heuristics?

**Comment by bkamins** [comment]
Excellent!

**Comment by bkamins** [comment]
@quinnj Here is a list of methods that we should support if possible to be consistent with `Vector` API:
* `deleteat!`
* `insert!`
* `splice!`
* `prepend!`

**Comment by nalimilan** [comment]
`pop!` too?

**Comment by bkamins** [comment]
Right. I missed it, because it does not have `Vector` in the signature in the Julia documentation and I did an automatic scan.

**Comment by quinnj** [comment]
We need to make sure PooledArray/CategoricalArray support all those too, right?

**Comment by nalimilan** [comment]
Yes. See https://github.com/JuliaComputing/PooledArrays.jl/pull/23, https://github.com/JuliaData/CategoricalArrays.jl/pull/192 and https://github.com/JuliaLang/julia/pull/32065. It seems that `deleteat!` is the most commonly requested function because DataFrames needs it for `filter!` and `dropmissing!`.

**Comment by quinnj** [comment]
I think the main issues here are all resolved now (missing mutation methods for custom arrays)
