### ISSUE TITLE
sort() vs. sort!()

### ISSUE THREAD

**Issue by GregorMatheis** [JuliaData/CSV.jl#438]
Performing sort on a dataset created via CSV.read()  works while sort!() throws error etindex! not defined for CSV.Column{String,String}

Setup:
Julia v1.1.0
CSV v0.5.2
DataFrames v0.18.2
```
Con_data = CSV.read("Con_data.csv")
names!(Con_data, Symbol.(names(Con_data),"_con"));
categorical!(Con_data,:Status_con);
levels!(Con_data.Status_con, ["Expired","Live","Signed","Sent","New","Cancelled"]);
```
Sorting:
`Con_data = sort(Con_data, [:Status_con, :CreatedDate_con], rev = [false,true]); ` works fine
`sort!(Con_data, [:Status_con, :CreatedDate_con], rev = [false,true]) `doesn't work

ERROR: setindex! not defined for CSV.Column{String,String}

Would be great if that could be fixed.

**Comment by quinnj** [comment]
@GregorMatheis , sorry for not commenting on this earlier before closing; by default `CSV.read` will return a DataFrame w/ `CSV.Column` columns, which are read-only "views" into the underlying csv data. This is for performance and to avoid unnecessary copies when mutable operations aren't needed on the resulting DataFrame/columns. To get mutable columns, you can do `CSV.read(file; copycols=true)`, or by working w/ a `CSV.File` directly, you can do `CSV.File(file) |> DataFrame`, or to make a single column mutable, you can do `copy(f.col1)` (i.e. copying a `CSV.Column` will turn it into a regular `Vector`). Hopefully that helps clarify! I also added a helpful error message if people try to do `setindex!` operations on a `CSV.Column` to basically do one of the options I just listed above.

**Comment by GregorMatheis** [comment]
Thank you for explaining. That and the changed error message is really helpful.
