### ISSUE TITLE
question: how to handle `parsefield(io, Char)`

### ISSUE THREAD

**Issue by tpapp** [JuliaData/CSV.jl#44]
It comes up quite often: eg a dataset I am now working with encodes gender as `M` and `F`, another uses `E`, `U`, `O` for employment, unemployment, out of the labor force, etc.

Using `String` is not optimal. I could define a method for `parse(Char, str; raise=true)` as suggested by the manual, or one for `parsefield(io, Char, ...)`.

**Comment by quinnj** [comment]
Just added this. Note that columns aren't going to be detected automatically as `Char`, but you can specify a column to be `Char` type and it will use the new parsing function. Let me know if you run into any issues.

(also, you'll need current master for this to work obviously, just do `Pkg.checkout("CSV")`)

**Comment by tpapp** [comment]
Thanks. I also found that I can handle encodings like this as
```julia
@enum Gender male=1 female=2

function Base.parse(::Type{Gender}, string)
    s = strip(string)
    if (s == "M")
        male
    elseif (s == "F")
        female
    else
        throw(ArgumentError("string $(s) not recognized as Gender"))
    end
end

CSV.parsefield(source, Gender)
```
Once other than `Int32` `Enum`s are supported, this should be really compact.

**Comment by nalimilan** [comment]
FWIW, CategoricalArrays should be easier to set up and as efficient for most cases. You can already use a `UInt8` storage to save space.
