### ISSUE TITLE
request `headerskip` like `footerskip`

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaData/CSV.jl#441]
Sometimes I want legalese at the top of a data file.  Or, to start using data after the initial K rows are passed over (and to stop after L rows).  I know there is an electable comment char, but that gets messy with multiple paragraphs. I guess a better way might be to specify a "when you see a line that starts with this, then you know to begin parsing with the next line".   Your thoughts?

**Comment by quinnj** [comment]
We have the `skipto` keyword argument that allows you to specify the line number where the ***data*** begins in a file. Would that work for you?

**Comment by JeffreySarnoff** [comment]
that is good -- (very nice work)
