### ISSUE TITLE
ArgumentError: Symbol name may not contain \0

### ISSUE THREAD

**Issue by Jo-Fleck** [JuliaData/CSV.jl#442]
I am trying to read a csv file and get:  **ArgumentError: Symbol name may not contain \0**

The csv file is [here.](https://www.huduser.gov/portal/datasets/FMR/FMR_All_1983_2019_rev.csv) It has 270 columns. Some of them are titled in the following pattern: "fmrYY_0".

Does the "_0" part cause the argument error? If yes, are there any options to read the data without changing the names (by hand)?

Thanks a lot for hints and help!

**Comment by quinnj** [comment]
`CSV.read(file; normalizenames=true)`

**Comment by Jo-Fleck** [comment]
Thanks @quinnj - works!

I just read the manual regarding `normalizenames`. Can you enlighten me: Was the error thrown because of spaces in the column names? Or because _ is an invalid identifier character?

**Comment by quinnj** [comment]
We use the `Base. is_id_char(c)` to determine whether a character needs to be replaced for normalizenames; spaces aren't allowed, `_` should be fine.

**Comment by Jo-Fleck** [comment]
Thanks a lot @quinnj
