### ISSUE TITLE
another mmap error on windows

### ISSUE THREAD

**Issue by jaakkor2** [JuliaData/CSV.jl#443]
This looks a bit like closed https://github.com/JuliaData/CSV.jl/issues/424 , a bit like https://discourse.julialang.org/t/csv-mmap-error-when-parsing-large-file/24555 , but involves lines to be skipped in the beginning of the file
```julia
hh = true ## additional garbage in the beginning of file
using CSV, DataFrames
cols = 1000
for rows in (10, 100, 1000)
    filename = string("test_", rows, "x", cols, ".csv")
    println("Writing ", filename)
    open(filename, "w") do io
    	hh && write(io, "foo\nbar\n")
    end
    df = DataFrame(rand(rows, cols))
    CSV.write(filename, df, writeheader=true, append=true)
	a = CSV.read(filename, header=1+2*hh, datarow=2+2*hh)
end
```

Output looks like
```
Writing test_10x1000.csv
Writing test_100x1000.csv
Writing test_1000x1000.csv
ERROR: could not create file mapping: The operation completed successfully.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] #mmap#1(::Bool, ::Bool, ::Function, ::Mmap.Anonymous, ::Type{Array{UInt64,1}}, ::Tuple{Int64}, ::Int64) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Mmap\src\Mmap.jl:218
 [3] #mmap#14 at .\none:0 [inlined]
 [4] mmap at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Mmap\src\Mmap.jl:251 [inlined]
 [5] file(::String, ::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Int64, ::Bool, ::Nothing, ::Bool, ::Array{String,1}, ::String, ::Nothing, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Nothing, ::UInt8, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Dict{Int8,Int8}, ::Bool, ::Float64, ::Bool, ::Bool, ::Bool, ::Bool, ::Nothing) at C:\Users\j\.julia\packages\CSV\IwqOm\src\CSV.jl:278
 [6] #File#20 at C:\Users\j\.julia\packages\CSV\IwqOm\src\CSV.jl:158 [inlined]
 [7] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:header, :datarow),Tuple{Int64,Int64}}, ::Type{CSV.File}, ::String) at .\none:0
 [8] #read#57 at C:\Users\j\.julia\packages\CSV\IwqOm\src\CSV.jl:625 [inlined]
 [9] (::getfield(CSV, Symbol("#kw##read")))(::NamedTuple{(:header, :datarow),Tuple{Int64,Int64}}, ::typeof(CSV.read), ::String) at .\none:0
 [10] top-level scope at REPL[21]:9
```

Setting `hh=false` works.

I'm on Windows 10, 16 GB RAM, Julia v1.1.1, CSV v.0.5.5.

**Comment by jaakkor2** [comment]
Some observations with the example above.

If `hh=false`, I can read and write `rows=100000`. Did not have patience/memory to go higher.

I have access to two Windows 10 machines. If `hh=true`, then the failing number of `rows` is different:  machine A (i7-8650U, 16 MB) `rows=300` ok, `rows=1000` fails.  Machine B (E5-1630v3, 128 MB) `rows=1000` ok, `rows=3000` fails.

Size of failing `test_400x1000.csv` is only 7 MB, so we are not talking about big files.

Also, with `hh=true`, before seeing the error `ERROR: could not create file mapping: The operation completed successfully.`, the reading speed slows considerably

`test_1000x1000.csv`
  0.248909 seconds (716.31 k allocations: 3.447 MiB)
`test_1500x1000.csv`
 13.725572 seconds (1.06 M allocations: 4.774 MiB)
`test_3000x1000.csv` 
failed reading

**Comment by jaakkor2** [comment]
Setting `debug=true` reveals that `rowsguess` can vary a lot depending how much non-data there is in the beginning of the file.

https://github.com/JuliaData/CSV.jl/blob/v0.5.5/src/CSV.jl#L226 says
```
# we call guessnrows upfront to simultaneously guess how many rows are in a file (based on average # of bytes in first 10 rows), and to figure out our delimiter: if provided, we use that, otherwise, we auto-detect based on filename or detected common delimiters in first 10 rows
```
Should it start from `datarow` and take 10 lines from there, and not the first 10 rows of the file?

**Comment by jaakkor2** [comment]
Another example
```
using CSV, DataFrames
fn = "debug.txt"
n_emptylines = 10
open(fn, "w") do io
	for i=1:n_emptylines
		print(io, "\n")
	end
	CSV.write(io, DataFrame(rand(50,1000)), append=true, writeheader=true)
end
```
Then reading the file
```
CSV.read(fn, header=n_emptylines+1, datarow=n_emptylines+2, debug=true)
```

For `n_emptylines=10` I get
```
header is: 11, datarow computed as: 12
Char(attempted_delim) = ','
bvc.counts[Int(attempted_delim)] = 0
nlines = 10
Char(attempted_delim) = '\t'
bvc.counts[Int(attempted_delim)] = 0
nlines = 10
Char(attempted_delim) = ' '
bvc.counts[Int(attempted_delim)] = 0
nlines = 10
Char(attempted_delim) = '|'
bvc.counts[Int(attempted_delim)] = 0
nlines = 10
Char(attempted_delim) = ';'
bvc.counts[Int(attempted_delim)] = 0
nlines = 10
Char(attempted_delim) = ':'
bvc.counts[Int(attempted_delim)] = 0
nlines = 10
smallest line detected with 1 bytes
estimated rows: 968337
detected delimiter: ","
column names detected: Symbol[:x1, :x2, :x3, :x4, ......
```

For `n_emptylines=0` I get
```
header is: 1, datarow computed as: 2
Char(attempted_delim) = ','
bvc.counts[Int(attempted_delim)] = 9990
nlines = 10
smallest line detected with 4893 bytes
estimated rows: 198
detected delimiter: ","
column names detected: Symbol[:x1, :x2, :x3, :x4, :x5 .........
```

**198** vs **968337** estimated rows is quite a difference when the actual number of data rows is 50.

**Comment by quinnj** [comment]
It would certainly be better to start from datarow and then average 10 lines for guessing the # of rows; but as you've noted, there will always be worst-case scenarios where we way overestimate.

**Comment by jaakkor2** [comment]
The last example with 10 empty rows: reading it once works, but second time fails `ERROR: could not create file mapping: The operation completed successfully.`. 

So, this is a usability issue: now I have to hand edit the files to remove lines before the data starts.

**Comment by quinnj** [comment]
Sorry for the delay here; I agree that we can tighten up our rows guessing logic, most likely by combining it with the datalayout detection logic. I'll need to noodle on it a bit, but it could be a good win to do all this together.

**Comment by quinnj** [comment]
Ok, I'm going to close this issue because w/ #485, the row estimation logic is cleaned up quite a bit (the original examples here from @jaakkor2 now estimate 56 rows no matter how many empty lines are in the file). We also have other open issues for the mmap issue.
