### ISSUE TITLE
eltypes is not working correctly (Date column)

### ISSUE THREAD

**Issue by kafisatz** [JuliaData/CSV.jl#446]
In the example below, I specify the column type as Date, but it is parsed as String.
I would either expect an error (or a Date column type).

```
using Dates 
using CSV 
using DataFrames 

arr=[1 "01/01/2017" 3;
    4 "08/02/2011" 6;
    4 "08/02/2011" 6;
    4 "01/02/2011" 6;
    4 "01/02/2011" 6;
    4 "02/02/2011" 6;
    4 "31/03/2011" 6]

sep=','
df=DataFrame(arr)
fn ="C:\\temp\\arr.csv"
CSV.write(fi,df,delim=',')

elt=[String,Date,Int64][:]

df_read=CSV.read(fn,allowmissing=:none,eltypes=elt,delim=sep)

@assert eltype(df_read[:x2])==elt[2]
@show  eltype(df_read[:x2]),elt[2]
```

**Comment by quinnj** [comment]
I'm not sure where you heard of `eltypes`, but the keyword argument for `CSV.read` is `CSV.read(fn; types=[String, Date, Int64])`

**Comment by kafisatz** [comment]
@quinnj  Thank you. My mistake. Although I was not aware, that I can provide a non-existent keyword. From my point of view, it would preferable if you could check for that (although it is probably rare that people make the same mistake that I did).
