### ISSUE TITLE
extra trailing newline

### ISSUE THREAD

**Issue by visr** [JuliaData/CSV.jl#447]
I have files that sometimes have 2 trailing newlines. I expected that they would be ignored, however an extra row was added with all `missing`. Since it only happens sometimes, and the lines are empty, `footerskip` doesn't seem ideal. Would you consider changing this behavior?

```julia
julia> CSV.File(IOBuffer("a,b,c\n1,2,3\n\n"))
warning: only found 1 / 3 columns on data row: 2. Filling remaining columns with `missing`
CSV.File("<Base.GenericIOBuffer{Array{UInt8,1}}>"):
Size: 2 x 3
Tables.Schema:
 :a  Union{Missing, Int64}
 :b  Union{Missing, Int64}
 :c  Union{Missing, Int64}
```

This is on CSV master and Julia 1.1.1:
```
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Got a bit of a deja vu, since my first julia issue was https://github.com/JuliaLang/julia/issues/5602 over 5 years ago haha.

**Comment by quinnj** [comment]
Yeah, I'm wondering if we should just ignore empty lines, no matter where they happen in a file. Would that be too surprising to anyone?
