### ISSUE TITLE
non-comma repeated auto-delimiters

### ISSUE THREAD

**Issue by visr** [JuliaData/CSV.jl#448]
I came across some edge cases when combining auto-delimiter finding and repeated delimiters. All works as expected for comma:

```julia
CSV.File(IOBuffer("1,,2,3\n4,5,6"), header=false, ignorerepeated=false)  # -> 2 x 4 (double comma adds column)
CSV.File(IOBuffer("1,,2,3\n4,5,6"), header=false, ignorerepeated=true)  # -> 2 x 3
```

But using another delimiter (space, tab, semicolon), it combines all columns in a single `String` column:

```julia
CSV.File(IOBuffer("1;;2;3\n4;5;6"), header=false, ignorerepeated=false)  # -> 2 x 1
CSV.File(IOBuffer("1;;2;3\n4;5;6"), header=false, ignorerepeated=true)  # -> 2 x 1
```

It goes well if I explicitly give the delimiter:
```julia
CSV.read(IOBuffer("1;;2;3\n4;5;6"), header=false, ignorerepeated=true, delim=';')  # -> 2 x 3
```

I'm not searching for edge cases, I just happen to have a messy set of files that are either space or tab delimited, often multiple spaces that need to be ignored. Would be great if the combination of auto delimiter detection and repeated delimiters covered all this.

This is on CSV master and Julia 1.1.1:
```
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by quinnj** [comment]
Yeah, auto-delimiter detection really isn't built to handle the `ignorerepeated=true` case right now; we should probably require the user to pass the delimiter in that case since auto-detection will almost surely fail.

**Comment by visr** [comment]
That would probably be good to require, yes. Though from the `ignorerepeated=false` case above we see that it also affects behavior there (2 x 1 instead of 2 x 4), so perhaps it could be a note in the auto-delimiter detection docs. And I guess the comma works since it is the default fallback if auto-delimiter detection fails. In that case we need to make auto-delim robust to repeated delim. Or do you also want to auto detect double delims, for the case where you may have `a;;b;;c` meaning `a,b,c`? I'd say we should auto detect `a;;b;;c` as `a,,b,,c`. Though I didn't dive in the code yet.

**Comment by quinnj** [comment]
Ok, we now don't do auto-delimiter detection if `ignorerepeated=true` (an error is thrown instead). It's also not really possible to detect string delimiters (i.e. you suggestion fo `;;` or `,,`) given the current logic (it tries to find a single character that occurs the same # of times on each line). `a,,b,,c` is perfectly valid csv meaning 5 columns with values: `a`, `missing`, `b`, `missing`, and `c`.
