### ISSUE TITLE
Quote Characters in File Read

### ISSUE THREAD

**Issue by versipellis** [JuliaData/CSV.jl#454]
I'm not entirely sure if this issue belongs here or with Parsers.jl. Google Forms data is dumped out CSVs to the format of `"some","","text"`, with quotes around everything, including empty fields.

This works, until you try to specify `missingstring="\"\""` to try to have the `""` fields treated as missing, which throws `ArgumentError: sentinel value isn't allowed to start with openquotechar, closedquotechar, or escapechar characters`.

While the desired behavior seems to vary by implementation in other languages, having the option to specify whether `""` gets read as missing or simply empty fields offers flexibility in reading in Google forms CSVs.

**Comment by quinnj** [comment]
in `"some","","text"`, the empty quotes should be treated as missing; can you share an example file where that's not happening? That's the default behavior to treat those as missing.

**Comment by versipellis** [comment]
I can create a synthetic test file later, but there's nothing special about the dataset that I'm using. The code in question being used is as follows:
```
using CSV
using DataFrames
filename = "survey.csv"
data = pwd() * "/" * filename
df = CSV.read(data, normalizenames = true)

typeof(df[6])
CSV.Column{String,PooledString}
```

**Comment by quinnj** [comment]
Oh wow, sorry for speaking too soon; there does indeed seem to be a problem where `""` isn't being treated as `missing`. Let me investigate.

**Comment by quinnj** [comment]
Ok, this should be fixed w/ the latest Parsers.jl release; let me know if you see any issues.

**Comment by versipellis** [comment]
Thank you so much!
