### ISSUE TITLE
question: how to use with gzipped file

### ISSUE THREAD

**Issue by tpapp** [JuliaData/CSV.jl#46]
The following does not work:

``` julia
fh = GZip.open("my_file.gz")
source = CSV.Source(fh;
                    delim = ';', dateformat = "yyyymmdd",
                    header = true,
                    rows_for_type_detect = false,
                    use_mmap = false)
```

and fails with the error message

``` julia
ERROR: TypeError: Type: in typeassert, expected Int64, got Bool
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{CSV.Source}, ::GZip.GZipStream) at ./<
missing>:0                                                                        
```

which is somewhat cryptic. Using the first few lines of the same file as an `IOBuffer(string)` works fine.

Does this library handle `GZip` streams? If yes, an example would be useful.

Using latest tagged `GZip`, master `CSV`. (Sorry for so many questions today, and thanks for your patience).

**Comment by quinnj** [comment]
No, currently GZip streams are not supported. They were at one point, but they ended up being a total performance trap (like 1000x slower than just unzipping the file beforehand). So for now, the recommended approach is to unzip your file beforehand then parse it.

To ultimately support GZip, we need to do an overhaul of the GZip/Libz packages to combine the best of each. Currently, GZip sucks for performance, but supports file-based operations, while Libz is fast, but only supports stream-based operations. It's on my TODO list.

**Comment by tpapp** [comment]
Apparently https://github.com/BioJulia/Libz.jl addresses (or plans to address) the same problems (but still gives the same error message). Perhaps it would be easier to make CSV work with that?

**Comment by tpapp** [comment]
Unfortunately decompression is cumbersome, the multiple CSV files are about 1GB each and `gzip -9` gives me a factor of 10-15. I have enough space, but the server is HDD-based so everything is so much faster with gzipped files.

**Comment by quinnj** [comment]
Reading gzipped files is now supported via `Libz.jl` package, like
```julia
julia> f = ZlibInflateInputStream(open(joinpath(dir, "test_basic.csv.gz")))
BufferedStreams.BufferedInputStream{Libz.Source{:inflate,BufferedStreams.BufferedInputStream{IOStream}}}(<8.0 KiB buffer, 0% filled>)

julia> df = CSV.read(f)
3×3 DataFrames.DataFrame
│ Row │ col1 │ col2 │ col3 │
├─────┼──────┼──────┼──────┤
│ 1   │ 1    │ 2    │ 3    │
│ 2   │ 4    │ 5    │ 6    │
│ 3   │ 7    │ 8    │ 9    │

```
