### ISSUE TITLE
it `types` is passed as a Dict, then it should be allowed to contain extra entries.

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/CSV.jl#460]
Since one can't actually know what column names one is going to get,
it turns out sometimes to be easier to specify the types of columns that may or may not be present.

Logically this could be done by passing in types as a `Dict` to the `CVS.File`.
But right now, that errors if that dict has more entries than there are columns.

**Comment by oxinabox** [comment]
hmm this seems to already work.
I wonder what was going wrong for me
before

**Comment by quinnj** [comment]
I believe I've tweaked a few things on master that haven't been released yet, which would explain a difference or two.

**Comment by oxinabox** [comment]
hmm nope, it also seem to work fine in 0.5.5

**Comment by oxinabox** [comment]
Can't even reproduce for my non MWE.
Closing
