### ISSUE TITLE
`ignoreemptylines` doesn't work in the middle of the file

### ISSUE THREAD

**Issue by karajan9** [JuliaData/CSV.jl#469]
Reading the file
```
A,B
1,2
,
,3
```
with `ignoreemptylines` results in
```
CSV.read(fn, ignoreemptylines = true)
3×2 DataFrames.DataFrame
│ Row │ A       │ B       │
│     │ Int64⍰  │ Int64⍰ │
├─────┼─────────┼─────────┤
│ 1   │ 1       │ 2       │
│ 2   │ missing │ missing │
│ 3   │ missing │ 3       │
```
while I would have expected
```
CSV.read(fn, ignoreemptylines = true)
2×2 DataFrames.DataFrame
│ Row │ A       │ B       │
│     │ Int64⍰  │ Int64   │
├─────┼─────────┼─────────┤
│ 1   │ 1       │ 2       │
│ 2   │ missing │ 3       │
```
It seems the [tests](https://github.com/JuliaData/CSV.jl/blob/5d756a2c68fba4085c054aa2f7a94c182cbc0d8f/test/runtests.jl#L149) only check against empty lines at the end of the file. Is it intentional that this doesn't work the way I would've expected?

**Comment by quinnj** [comment]
This is working as expected; your second line in the example isn't "empty" in the sense that `ignoreempty` checks for: it only skips lines that are ***literally*** empty, i.e. no delimiters or characters of any kind, just a single newline (or CRLF). Only in that scenario will the line be ignored.

**Comment by karajan9** [comment]
Ah, thanks, that's good to know. Is there maybe another way to achieve what I want to do? I mainly want the line removed so that column `B` isn't a `Union` with `Missing` any more.

**Comment by asinghvi17** [comment]
`dropmissing!(df; disallowmissing=true)` should do it

**Comment by quinnj** [comment]
Closing for now; but please comment if there's anything else unclear here. Thanks.
