### ISSUE TITLE
DataFrames.jl dependency

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#471]
Currently CSV.jl in Project.toml has DataFrames.jl version fixed at 0.18. This will disallow upgrading DataFrames.jl to 0.19 when also CSV.jl is installed.

@quinnj Can we please change this?

**Comment by bkamins** [comment]
If it is OK with you then a patch release to CSV.jl would be great to have.

In general my intention is to have one week before JuliaCon to catch any bugs in DataFrames.jl so that we can release a patch if needed before the conference. Thank you.

**Comment by quinnj** [comment]
No problem; feel free to do a PR I can do it later today (in 12 hours or so)
