### ISSUE TITLE
Comment not working with crlf endings on windows

### ISSUE THREAD

**Issue by ahyork** [JuliaData/CSV.jl#478]
When using the option for `comment='#'` while reading in this [file](https://github.com/JuliaData/CSV.jl/files/3473783/error_comment.txt) it does't ignore the commented lines at the end and infers the wrong type for each of the columns. 

This issue only occurs when the file has dos line endings and the command is run on a windows machine. When the file is converted to dos line endings and run on linux it ignores the lines correctly.

I am running Julia 1.1.1 and CSV 0.5.9, thank you for your help!

**Comment by quinnj** [comment]
Thanks for reporting this @ahyork! Sorry for the slow response here; I've been knee-deep in some other projects and getting mulithreaded parsing working for this package. I've got a fix for this up in [this PR](https://github.com/JuliaData/CSV.jl/pull/483).
