### ISSUE TITLE
Entire column of missing data produces unsavable DataFrame

### ISSUE THREAD

**Issue by jiahao** [JuliaData/CSV.jl#48]
I was playing around with the [NYC taxicab data](www.nyc.gov/html/tlc/html/about/trip_record_data.shtml) and reading it in produces one particular  column that is entirely empty:

```jl
using CSV
filename = "green_tripdata_2015-09.csv"
isfile(filename) || download("https://s3.amazonaws.com/nyc-tlc/trip+data/green_tripdata_2015-09.csv", filename)
df = CSV.read(filename)
```

```
julia> df[:Ehail_fee]
1494926-element NullableArrays.NullableArray{WeakRefString{UInt8},1}:
 #NULL
 ⋮
```

It looks like the field is missing for every row of the CSV file. However, I think it would be better to return something like `NullableArray{Void}` rather than the current `NullableArray{WeakRefString}`, since the latter produces a data frame that is hard to work with. For example, it cannot be saved with JLD:

```jl
julia> JLD.save("df.jld", "t", df[:Ehail_fee], compress=true)
ERROR: cannot write a pointer to JLD file
...
```

**Comment by quinnj** [comment]
You can do `CSV.read(file; weakrefstrings=false)` to force regular `String` instead of `WeakRefString`. There's also no way to return a `NullableArray{Void}`, we look at the first 100-250 rows to do "type inference" with a fallback to string.

**Comment by jiahao** [comment]
Thanks - looks like `weakrefstrings` only works on master, not current release
