### ISSUE TITLE
Question: Big gap in performance between data.table::read and CSV.read

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#487]
There still seems to be a big gap between `data.table::fread` and `CSV.read`.

I am interested in understanding a bit more at the technical why there is still a gap? And how close can we reasonably to get with multi-threading now. 

For example, reading a 7G CSV takes 200 seconds (single-threaded) using CSV.jl but only 40s using data.table (multi-threaded).

**Comment by quinnj** [comment]
Nah, [there's not really a performance gap](https://quinnj.home.blog/2019/08/24/everyones-favorite-blogpost-csv-benchmarks/) between fread & CSV.read. We need to improve [memory usage](#484), and it looks like we can probably improve float parsing a bit, but overall, CSV.jl is faster or on-par in a large sample of files.
