### ISSUE TITLE
memory mapping failed: Cannot allocate memory

### ISSUE THREAD

**Issue by aplavin** [JuliaData/CSV.jl#488]
Reading many and/or large CSV files starts giving `ERROR: SystemError: memory mapping failed: Cannot allocate memory` from time to time, even with `use_mmap = false`. Can't see any relevant options to control mem-mapping further.

A simple example:
```julia
# create CSV file
CSV.write("tmp.csv", DataFrame(a=1:1000, b=1:1000))

# read it many times
[CSV.read("tmp.csv", use_mmap=false) for i in 1:1000];
# running the previous line several times reliably gives the error for me
```

Julia 1.2.0, CSV 0.5.11.

**Comment by quinnj** [comment]
I can't reproduce this in https://github.com/JuliaData/CSV.jl/pull/510, even when doing `[CSV.read("tmp.csv", use_mmap=false) for i in 1:10000];`, i.e. 10,000 times instead of just 1,000. The memory efficiency has been improved in that branch, which would explain the improvement.

**Comment by quinnj** [comment]
Please re-open/comment if you still see an issue

**Comment by FredSoftwares** [comment]
I confirm that the problem still exists with Julia 1.4.1 and it is related to multithread and probably hyperthreading [see this post](https://discourse.julialang.org/t/memory-mapping-failed-when-reading-many-csvs/27979/12)

Test done with :
(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [336ed68f] CSV v0.6.2
  [861a8166] Combinatorics v1.0.1
  [a93c6f00] DataFrames v0.21.0
