### ISSUE TITLE
Ability to parse multiple columns with different date formats

### ISSUE THREAD

**Issue by kcajf** [JuliaData/CSV.jl#490]
I have a csv with a strangely formatted column of Dates like `2019/03/04`, and a strangely formatted column of DateTimes like  `2019-03-04 23:32:32`. I couldn't work out a way to parse both of these using the `dateformat` and `types` arguments to `CSV.read`. I had a look for a similar issue and was surprised to not easily find one. Any tips please?

**Comment by non-Jedi** [comment]
Note that the documentation explicitly notes that this is currently impossible. I would like to add to this feature request a request for using multiple dateformats in a single column that stores dates heterogeneously. I realize this could be ambiguous, but simply using the first dateformat that matched would be acceptable.

**Comment by quinnj** [comment]
PR to add this functionality is up: https://github.com/JuliaData/CSV.jl/pull/605
