### ISSUE TITLE
SIGBUS on CSV.write

### ISSUE THREAD

**Issue by mlhetland** [JuliaData/CSV.jl#498]
Hi!

I'm getting a SIGBUS when trying to use `CSV.write` to overwrite a file previously read. I.e.:

```
using CSV
df = CSV.read("myfile.csv")
open("myfile.csv", "w") do io
    CSV.write(io, df)
end
```

Julia then crashes with the error:

```
'julia' terminated by signal SIGBUS (Misaligned address error)
```

Unfortunately, it does not seem to be entirely consistent. When executing the commands above in the REPL, I get the SIGBUS, but if I put them in a file and run it, things work just fine. Then I try with just another file name (same csv contents), and it "works", except the file ends up empty.

So … it's hard to provide a 100% reproducible example, here. (Also, I can't really post the file I'm working on, but I don't think there's anything particularly odd about it.)

Some metadata:

```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
CSV v0.5.12
DataFrames v0.19.4
```

**Comment by quinnj** [comment]
Sorry for the very slow response here. Before a recent refactoring, CSV.jl, by default, would lazily read string columns and the resulting columns, even in a DataFrame, would hold a reference to the underlying file to lazily materialize each string cell. You could do `CSV.read(file; copycols=true)` to ensure no reference to the file was held.

On current master, strings are materialized by default and no reference is held to the file after reading (so no more need to do `copycols=true`), so with the upcoming release, I don't think this should be an issue anymore.
