### ISSUE TITLE
threaded is 10x slower sometimes

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#499]
I have a 64GB RAM Windows 10 runing Julia 1.3-rc1.

The performance of reading [Fannie Mae 2010Q3.txt(https://docs.rapids.ai/datasets/mortgage-data) is as shown shows that threaded is like 10x slower than non-threaded.

How can I help you diagnose further? The data is about 2.8GB in size, but it uses almost all of my 64GB when doing multithreading. I am running on the latest master of as of Sept 17. 

Could it be a memory efficiency issue?
![image](https://user-images.githubusercontent.com/4497189/65003201-c7819680-d93a-11e9-8d02-ce62e264a2de.png)

**Comment by quinnj** [comment]
I can't reproduce this issue on the `jq/mem3` branch in https://github.com/JuliaData/CSV.jl/pull/510.

**Comment by xiaodaigh** [comment]
Seems to be resolved in jq/mem3.

**Comment by KristofferC** [comment]
This smells like https://github.com/JuliaLang/julia/issues/33338.
