### ISSUE TITLE
CSV.Row2 supports getindex, but CSV.Row does not

### ISSUE THREAD

**Issue by ianfiske** [JuliaData/CSV.jl#500]
Just checking if there is a reason why we don't want to have `getindex` for `CSV.Row`.  It makes some operations a lot easier.  It's already there for `CSV.Row2` https://github.com/JuliaData/CSV.jl/blob/f046da7d3c42fb435cee8de6947ed314260d4a54/src/rows.jl#L224.

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaData/CSV.jl/pull/510
