### ISSUE TITLE
`propertynames` does not return column names on a `CSV.Row2`

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaData/CSV.jl#501]
```
julia> using CSV

julia> io = IOBuffer("x,y\n1,3\n2,4");

julia> rows = CSV.Rows(io);

julia> row1 = first(rows);

julia> propertynames(row1)
(:names, :tape, :buf, :e)
```

The following line from the `CSV.Rows` doc leads me to believe that `propertynames(row1)` should return a tuple or array with the names of the columns.

>Each row object supports propertynames, getproperty, and getindex to access individual row values.

(`propertynames` does return an array of column names when called on a `CSV.Row`.)

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaData/CSV.jl/pull/510
