### ISSUE TITLE
Update compatibility with CategoricalArrays.jl

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#502]
CSV.jl requires CategoricalArrays.jl to be 0.5 or 0.6 only.

@nalimilan - given the new release when this should be synced? Now?

**Comment by nalimilan** [comment]
Just wait a few hours until the version is tagged. :-)

**Comment by matthieugomez** [comment]
bump

**Comment by bkamins** [comment]
I will make this change when I test all works OK (I think tomorrow)
