### ISSUE TITLE
CSV.write structures

### ISSUE THREAD

**Issue by Jo-Fleck** [JuliaData/CSV.jl#505]
I am trying to save a structure (of parameter values) as a CSV.

When I try to execute 
`CSV.write(param_out, params)`
(where `param_out` is the target file and `params` my structure) I get the following error:

`ArgumentError: no default 'Table.rows' implementation for type: struct_params`

Is there any workaround for this? Or any way to add this functionality?

Thanks!

**Comment by quinnj** [comment]
As the error reports, `CSV.write` can currently write anything that implements the [Tables.jl](https://github.com/JuliaData/Tables.jl) interface, which includes NamedTuples of AbstractVectors. You can also check out [`StructArrays.jl`](https://github.com/piever/StructArrays.jl) for compatibility.

Otherwise, you'll need to be more specific with the kind of structure you're trying to write to a csv file.

**Comment by Jo-Fleck** [comment]
Thanks @quinnj !

> Otherwise, you'll need to be more specific with the kind of structure you're trying to write to a csv file.

My apologies, but I am not sure I understand what you mean. Should I convert the structure to another type (e.g. a dataframe) to allow for `csv.write` to work as expected?

**Comment by quinnj** [comment]
What is your `params`? i.e. what is `typeof(params)`?

**Comment by Jo-Fleck** [comment]
`params` is an immutable structure containing two (possibly many) float and integer scalars. It is constructed in this way:

```
struct struct_params
  beta::Float64
  M::Int64
end
params = struct_params(0.5,10)
```

(So `typeof(params)` is `struct_params`.)

**Comment by quinnj** [comment]
So do you have an Array of `struct_params` that you want to write out to a file?

**Comment by Jo-Fleck** [comment]
Yes. 

So far, I am taking a detour: I extract the fields of `struct_params`, re-arrange them into an array and then write this array using `CSV.write` to a file. 

However, this approach becomes becomes very cumbersome when I have many fields and several instances of `struct_params`. 

My question is if there is a "direct" way of doing this with `CSV.write`?

**Comment by quinnj** [comment]
Sorry, I'm quite following how you're using `struct_params`; do you have a full example of code that you're doing right now? That would probably be easiest in order to help see if there's a more efficient way of using `CSV.write`

**Comment by Jo-Fleck** [comment]
@quinnj Sorry for my delayed reply (I had to meet a deadline). I've been able to solve this issue using a function which converts the content of the structures to a dataframe and prints them using `CSV.write`. It has only a minor footprint on performance so I suggest we close this issue.
