### ISSUE TITLE
Speed up getproperty(r::Row2, nm::Symbol)?

### ISSUE THREAD

**Issue by JockLawrie** [JuliaData/CSV.jl#507]
Hi there,

I've recently given [Schemata.jl](https://github.com/JockLawrie/Schemata.jl) a makeover and now I'm working on performance improvements. I am testing with files around 50M records, so small improvements add up.

Having profiled these tests, one opportunity for a speed up is a Dict lookup for `getproperty(r::Row2, nm::Symbol)` instead of using `findfirst`.

Here's a not-very-rigorous MWE:
```julia
a = [Symbol("x$(i)") for i = 1:9]
d = Dict(Symbol("x$(i)") => i for i = 1:9)

@time findfirst(==(:x1), a)
@time d[:x1]
```
On my machine the dict lookup takes about half the time of the array lookup, and one less allocation. Although both times are small, in my case I am executing `getproperty` more than 100M times per test case, so the difference adds up.

Would you be open to including in `Rows` a `Dict` that maps column name to its index in `Rows.names`? Each `Row2` would then inherit this lookup, so it need only be created once.

**Comment by quinnj** [comment]
This is implemented in https://github.com/JuliaData/CSV.jl/pull/510
