### ISSUE TITLE
Skip unparseable rows

### ISSUE THREAD

**Issue by JockLawrie** [JuliaData/CSV.jl#509]
Hi there,

Currently a row that is invalidly quoted raises an error.
Can this throw a warning instead?

My use case is using [Schemata.jl](https://github.com/JockLawrie/Schemata.jl) to automatically inspect dozens of files, many being dozens of GB, and compare their content to a user-supplied schema. The output is a list of non-compliance issues.

It'd be preferrable if my code could, when it encounters a malformed line, include a message in the list of non-compliance issues and continue to the next line. But currently it fails on a malformed line.

Thoughts?

Cheers,
Jock

**Comment by quinnj** [comment]
The problem with invalid quotes is parsing just gets all mixed up. It can't tell how many columns were supposed to be there or if it consumed too much, so trying to continue parsing the rest of the file becomes completely undefined behavior, hence the error. Now, this is the _only_ error that is thrown once we start parsing a file, so I would suggest doing a try-catch and if the exception is `CSV.Error`, you know the file has invalid quotes, and can adjust appropriately.

**Comment by JockLawrie** [comment]
Skip to the first character after the next `\n` if it exists?
