### ISSUE TITLE
CSV.Rows chokes on large file on Windows

### ISSUE THREAD

**Issue by JockLawrie** [JuliaData/CSV.jl#519]
Hi there,

I am using `CSV.Rows` to chug through some large files on a Windows machine with 8GB RAM.

My code (the `compare` function in [Schemata.jl](https://github.com/JockLawrie/Schemata.jl)) works through an 8.4GB file without a hitch (and quickly too thanks to your efforts).
However it chokes on an 18GB file with mostly the same structure and data formatting.
I'm not sure what's happening here as memory usage hover around 1GB in both cases and I'm processing 1 row at a time.

I will try it on master as well as on Linux to see if I get a result, and report back.
In the meantime do you have any other tips?

Cheers,
Jock

**Comment by JockLawrie** [comment]
Success on Windows.
Updated to 0.5.14 and set `use_mmap=true`.
Interestingly, setting `use_mmap=false` fails even on small files.

**Comment by quinnj** [comment]
Great to hear; could you share the exact error you're seeing for `use_mmap=false`?

**Comment by JockLawrie** [comment]
Sure.

```bash
ERROR: LoadError: SystemError: mmap: The operation completed successfully.
Stacktrace:
 [1] #windowserror#45(::Nothing, ::typeof(Base.windowserror), ::Symbol, ::Bool) at .\error.jl:148
 [2] windowserror at .\error.jl:148 [inlined]
 [3] #mmap#1(::Bool, ::Bool, ::typeof(Mmap.mmap), ::Mmap.Anonymous, ::Type{Array{UInt8,1}}, ::Tuple{Int64}, ::Int64) at
C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Mmap\src\Mmap.jl:218
 [4] #mmap#14 at .\none:0 [inlined]
 [5] mmap at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Mmap\src\Mmap.
jl:251 [inlined]
 [6] getsource(::String, ::Bool) at C:\Users\jlaw1812\.julia\packages\CSV\skXyc\src\utils.jl:188
 [7] #Rows#44(::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Int64, ::Bool, ::Nothing, ::Bool, ::Bool, ::Array{String,1
}, ::String, ::Nothing, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Base.Ite
rators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Type{CSV.Rows}, ::String) at C:\Users\jlaw1812\.julia\pa
ckages\CSV\skXyc\src\rows.jl:108
```

**Comment by JockLawrie** [comment]
Another data point that may or may not be relevant:

I'm running the tests for [Schemata.jl](https://github.com/JockLawrie/Schemata.jl) on Windows, master branch.
Line 40 in `src/compare/ondisk_table.jl` uses `CSV.Rows`, with `use_mmap` taking the default value of `false`. In this case the tests pass.
If I set `use_mmap=true` the tests fail at the last hurdle, namely deleting the files that were created as part of the tests. That is, row iteration, parsing, etc works without issue. I just can't `rm` some files from disk.
Both cases work fine on Linux.

**Comment by quinnj** [comment]
@JockLawrie, I've tweaked a few things on current master; would you be willing to try your use-case again to see if you see the same errors?

**Comment by quinnj** [comment]
This should be even better on master and I have one more improvement that will help this as well before the next release.
