### ISSUE TITLE
Type determination error

### ISSUE THREAD

**Issue by somil55** [JuliaData/CSV.jl#52]
I have a CSV file with 1156 rows and 3 columns. Most of the entries in column 3 are NA's and some of them contains `Int64`s. When reading with `CSV.read` the type of column 3 is coming out to be `Nullable{WeakRefString{UInt8}}` which should have ideally been `Nullable{Int64}`. When i put first entry  in third column manually in 101th row it reads it as `Nullable{Int64}` but considers the column to be of type `Nullable{WeakRefString{UInt8}}` if first entry is in row 102 or ahead. So I presume the first 101 rows are being used to infer the type of the column. How can we correctly infer the type if the first element is beyond position 102?

[This](https://gist.github.com/somil55/ac9ce7a081810594a63e5a6a28ef32c2) is the link to the sample csv file. The function to read the file is `CSV.read("sample.csv")`

**Comment by quinnj** [comment]
In the docs [here](http://juliadata.github.io/CSV.jl/stable/#CSV.read), it mentions a keyword argument `rows_for_type_detect=100` that you can set.

You can also manually specify the types by doing something like `CSV.read(file; types=Dict(1=>Int)` to say that the first column is an `Int`, or just specify the types of all three columns `CSV.read(file; types=[Int,Int,Int])`.

**Comment by quinnj** [comment]
Do let me know if you have any other issues here.
