### ISSUE TITLE
Allow providing types to CSV.Rows

### ISSUE THREAD

**Issue by quinnj** [JuliaData/CSV.jl#521]

**Comment by JockLawrie** [comment]
Food for thought:

[Schemata.jl](https://github.com/JockLawrie/Schemata.jl) uses `CSV.Rows` to iterate through large files, parsing values and assessing them in terms of uniqueness, misssingness, etc. By default, the `String` values in each cell use `Parsers.jl` for parsing. Users can also supply, for any column in a table, a function that defines how the `String` values should be parsed. Within the package code, the user-defined functions are reduced to the form `value = f(input::String)` using closures. That is, args and kwargs are removed from the function signatures (before the row iteration starts).

It'd be great if these user-defined functions could be used without having to construct to a `String` first, i.e., `value = f(input)`, where `input`is not a `String`. I'd be happy to make some changes to the API to facilitate this, such as `value = f(row::CSV.Row2, colname::Symbol)` or `value = f(T, row::CSV.Row2, colname::Symbol)`.

Not a pressing issue, just nice to have and would likely improve performance.

**Comment by quinnj** [comment]
This is implemented on master
