### ISSUE TITLE
CSV.read cannot detect "Time" type string

### ISSUE THREAD

**Issue by evveric** [JuliaData/CSV.jl#526]
I have a DataFrame with a "Time" column

I CSV.write this DataFrame to a File, then CSV.read it back

DataFrame does not recognize it is a TIme, it reads as a "String"

How to fix it? Thank you

```
df = DataFrame(thistime=[Time(10,0,0), Time(12,0,0)])

CSV.write(raw"c:\temp\testtime.csv", df)

df2 = CSV.read(raw"c:\temp\testtime.csv") |> DataFrame

println(eltypes(df2))
```
DataType[String]

**Comment by quinnj** [comment]
You can provide the type manually, like:
```julia
julia> df2 = CSV.read("testtime.csv", types=[Time])
2×1 DataFrame
│ Row │ thistime │
│     │ Time     │
├─────┼──────────┤
│ 1   │ 10:00:00 │
│ 2   │ 12:00:00 │
```
But it does look like our auto-detection code isn't picking up the `Time` type here for you. Thanks for the report!
