### ISSUE TITLE
Setting `missingstrings=["NA"]` makes some columns not have names

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#530]
Consider a csv strucutred liked this

```csv
,column2
NA,2
2,3
```

```
nocolumn1name = CSV.read("c:/data/plsdel.csv", missingstrings=["NA"])
hascolumn1name = CSV.read("c:/data/plsdel.csv")
```

The top one has no column name for column1 but the 2nd way has.

See 
![image](https://user-images.githubusercontent.com/4497189/68992915-ea421400-08c5-11ea-8102-374714bae30b.png)

**Comment by quinnj** [comment]
Thanks for the report @xiaodaigh; fix is up here: https://github.com/JuliaData/CSV.jl/pull/535
