### ISSUE TITLE
Writing files with large # of columns polls forever?

### ISSUE THREAD

**Issue by caseykneale** [JuliaData/CSV.jl#538]
Tried to write a Dataframe via CSV.write with 50 rows and 11k variables and it took over 5min before cancelling it multiple times. Interestingly transposing the data, making the dataframe, and saving saved in << 1sec.

Not sure if this is known behaviour. Anyone have a good workaround?

**Comment by quinnj** [comment]
Sorry for the slow response; looking into this now

**Comment by caseykneale** [comment]
No worries, I'm swamped with work, hobbies, etc too. I'm not sure what would cause it, granted, it is a little ridiculous to write a line of values that long.

**Comment by quinnj** [comment]
Ok, discovered the issue: https://github.com/JuliaData/DataFrames.jl/pull/2051. In short, when iterating rows, DataFrames is trying to convert itself to a strongly typed NamedTuple of columns, which can be extremely costly in compile time for extremely wide DataFrames. I propose avoiding that, but there's perhaps a hybrid approach we should consider.

**Comment by caseykneale** [comment]
Go figure it's not with CSV, makes sense. Maybe it could be thresholded too? I've seen that has a motif in some Julia code bases where performances have some form of condition that makes it dynamic. Thanks for looking into this! A lot of people do work with really wide CSVs :)

**Comment by quinnj** [comment]
Fixed via https://github.com/JuliaData/DataFrames.jl/pull/2051
