### ISSUE TITLE
fix categorical for views

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#547]
The problem is:
```
julia> c = categorical([1,2,3], ordered=true)
3-element CategoricalArray{Int64,1,UInt32}:
 1
 2
 3

julia> c
3-element CategoricalArray{Int64,1,UInt32}:
 1
 2
 3

julia> isordered(c)
true

julia> cv = view(c, :)
3-element view(::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}, :) with eltype CategoricalValue{Int64,UInt32}:
 1
 2
 3

julia> isordered(cv)
true

julia> isordered(categorical(cv))
false
```

The core of the issue is how `_isordered` function is implemented (as it is not extensible now unfortunately). Probably a temporary fix is to define `_isordered` for `SubArrays`.

**Comment by nalimilan** [comment]
Did you mean to file this in CategoricalArrays? But yes, I think we can define `_isordered` to call `isordered` for any `AbstractArray{<:CategoricalValue}` which implements that function -- maybe falling back to checking whether each entry is ordered.

**Comment by bkamins** [comment]
Yes in CategoricalArrays.jl (I am in parallel looking at CategoricalArrays.jl, CSV.jl and DataFrames.jl so I have mixed this up - sorry for this). I am moving the issue there

**Comment by nalimilan** [comment]
You know we can transfer issues know? :-)
