### ISSUE TITLE
Some crashes in csv-comparison

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/CSV.jl#550]
I just reran my [CSV benchmark suite](https://github.com/davidanthoff/csv-comparison) (results [here](https://www.queryverse.org/benchmarks/)), and CSV.jl crashed for some of those runs. I've posted the logs of both the Windows and Mac runs [here](https://gist.github.com/davidanthoff/e5250cdeebac9b714a0d7a087e512627), somewhere in the middle you can find the error messages for the failed runs. I didn't systematically check, but I think it might be the threaded runs with categorical values. I had to restart the Linux runs because something went wrong with the R part of things, once I have those logs I'll also post them.

**Comment by quinnj** [comment]
Thanks for the report! I think I found the issue.
