### ISSUE TITLE
dev vs. add CSV

### ISSUE THREAD

**Issue by bjarthur** [JuliaData/CSV.jl#553]
in a new environment, `add CSV` installs 0.5.20 but `dev` results in 0.5.2.  this is on julia 1.2, 1.3, and 1.4.  is it a bug in Pkg or sth here?

**Comment by bjarthur** [comment]
DataFrames behaves similarly:  `add` gives the latest (0.20.0) but `dev` installs 0.18.2.  hmmm.

**Comment by quinnj** [comment]
My guess is that 0.5.2 is when you originally `dev`ed CSV.jl. Once you `dev` a package, it just clones it to your local dev directory, but it doesn't update it automatically for you (it assumes you're actually changing things and doesn't want to overwrite your local work). So if you `cd` manually into the directories and do a `git pull`, then it will pull the latest into your local directory.

**Comment by bjarthur** [comment]
doh.  sorry.
