### ISSUE TITLE
Unexpected whitespace handling in column names

### ISSUE THREAD

**Issue by jiahao** [JuliaData/CSV.jl#554]
It's not uncommon to find CSVs that are formatted so that the commas are aligned to the same text column. I was therefore surprised that spaces are not `strip()`-ped from the field names.

Example:

```jl
julia> df = CSV.read(IOBuffer("""
       A, B, C ,D
       1, 2, 3 ,4
       """))
1×4 DataFrames.DataFrame
│ Row │ A     │  B    │  C    │ D     │
│     │ Int64 │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┼───────┤
│ 1   │ 1     │ 2     │ 3     │ 4     │

julia> df.
 B   C   A    D
ERROR: ArgumentError: column name :B not found in the data frame; existing most similar names are: : B, :A and :D
Stacktrace:
 [1] getindex(::DataFrames.DataFrame, ::typeof(!), ::Symbol) at /Users/jiahao/.julia/packages/DataFrames/uPgZV/src/other/index.jl:253
 [2] getproperty(::DataFrames.DataFrame, ::Symbol) at /Users/jiahao/.julia/packages/DataFrames/uPgZV/src/abstractdataframe/abstractdataframe.jl:295

julia> df[Symbol(" B")]
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at REPL[16]:1
└ @ Core REPL[16]:1
1-element CSV.Column{Int64,Int64}:
 2
```

I would argue that `strip()`-ing whitespace from column names is the sensible default behaviour.

Versions: Julia 1.3, CSV v0.5.18, DataFrames v0.20.0

**Comment by quinnj** [comment]
It was debated, but ultimately we decided that not touching column names by default is safer; (I even remember Hadley Wickam chimed in). You can do `normalizenames=true` to ensure each column is whitespace-stripped and any non-identifier characters replaced with `_`

**Comment by quinnj** [comment]
For reference, here's the issue where we originally decided to have `normalizenames=false` be the default: https://github.com/JuliaData/CSV.jl/issues/295
