### ISSUE TITLE
Header parsing: Delimiters at end of line makes parsing continue in next line

### ISSUE THREAD

**Issue by AndiMD** [JuliaData/CSV.jl#555]
Hi there,

The following example shows how data from the second line can end up in column names, as well as in the column data. I was expecting the header parsing to stop at the EOL.
```
using CSV
CSV.read("bug.txt",header=true,ignorerepeated=true,delim=' ')
```
[bug.txt](https://github.com/JuliaData/CSV.jl/files/3978662/bug.txt)

Thanks!
AndiMD

**Comment by quinnj** [comment]
Thanks for the report @AndiMD and sorry for the slow response; I have a fix up at https://github.com/JuliaData/CSV.jl/pull/556
