### ISSUE TITLE
Correctly handling IO that does not support multithreading

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#558]
Not all `IO` objects support multithreading (see https://stackoverflow.com/questions/59601347/importing-a-text-csv-file-within-zip-file-from-ftp-url-causes-bound-error-bound for an example).

Currently you have to opt-out with `threded=false` in this case. Maybe it would be possible to detect this situation and automatically set `threded=false`. I have not had time yet to check if this is possible but it would be good to have, as it will probably hit many potential users.

**Comment by quinnj** [comment]
Will be resolved by https://github.com/JuliaData/CSV.jl/pull/658.
