### ISSUE TITLE
Option to add BOM header (UTF-8 with BOM)

### ISSUE THREAD

**Issue by oheil** [JuliaData/CSV.jl#567]
It would be nice to have an option to write a BOM header to a CSV file.
This is the following as the first bytes of the file:

`print(outStream,"\xEF\xBB\xBF")  #UTF-8 BOM header`

The resulting CSV file can be opened with Excel without wrongly interpreted UTF 8 characters.

**Comment by tpapp** [comment]
> Use of a BOM is neither required nor recommended for UTF-8

([page 36](https://www.unicode.org/versions/Unicode5.0.0/ch02.pdf))

**Comment by oheil** [comment]
But it helps with Excel (and with C# by the way)

**Comment by quinnj** [comment]
This would be a great up-for-grabs issue if someone wants to take a stab at it; just adding a keyword arg to CSV.write and writing out the bytes at the start of writing.

**Comment by oheil** [comment]
Any problems with the PR?

**Comment by quinnj** [comment]
Implemented in #571

**Comment by rna1990** [comment]
I know this is closed, but did that bom header option get eliminated recently? It stopped working after I installed julia 1.5 and updated CSV.jl

**Comment by oheil** [comment]
> I know this is closed, but did that bom header option get eliminated recently? It stopped working after I installed julia 1.5 and updated CSV.jl

I checked with 1.5.0  and CSV v0.7.7 and did not have any issues.
