### ISSUE TITLE
Inconsistent Float parsing

### ISSUE THREAD

**Issue by lsaenzt** [JuliaData/CSV.jl#572]
I am downloading interest rate data from Bank of Spain website.

The columns 2 to 7 are correctly assgined a Union{Missing, Float64} but from column 8 on the type is Union{Missing, String} in spite of the data also being float numbers.

Thanks.

The code:

   `
    using CSV, StringEncodings, HTTP
    
    tempIO=IOBuffer()
    file = HTTP.get("https://www.bde.es/webbde/es/estadis/infoest/series/ti_1_7.csv").body
    write(tempIO,file)
     
    bde_months = ["ENERO", "FEBRERO", "MARZO", "ABIRL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"]
    bde_monts_abbrev = ["ENE","FEB","MAR","ABR","MAY","JUN", "JUL","AGO","SEP","OCT","NOV","DIC"]

    Dates.LOCALES["BdE"] = Dates.DateLocale(bde_months,bde_monts_abbrev, [""],[""],)

    BdE_Format = DateFormat("dd uuuyyyy", "BdE") 

    tempdf = CSV.read(read(StringDecoder(seekstart(tempIO), enc"Latin1")), 
                      header=3, datarow=5, delim=',', decimal='.', quotechar='"', missingstring="_", dateformat=BdE_Format)`

**Comment by quinnj** [comment]
This seems to be a data issue as far as I can tell:
![Screen Shot 2020-02-06 at 11 37 13 AM](https://user-images.githubusercontent.com/2896623/73967425-1ec9d880-48d5-11ea-9ad7-9df59dd9bcac.png)

I found these problematic cells by doing `f = CSV.File(file; missingstring="_", header=false, datarow=5, types=Dict(8=>Union{Float64, Missing}));`; by setting the `types` keyword argument for column 8 to `Union{Float64, Missing}`, which will fix the column type to `Union{Float64, Missing}`, and warn (by default) on invalid values (replacing them with `missing`).

**Comment by lsaenzt** [comment]
Ooops. I wrongly assumed that, being data from the Bank of Spain, it was going to be solid. I should talk to them now.

I will use the fix you suggest for the rest of the columns. 

Thanks for your time. And congrats for this package. It is great.
