### ISSUE TITLE
Allow a default col type and some cols to have specific types

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaData/CSV.jl#575]
> One thing we should probably allow is doing something like type=Float64, types=(:col1=String, :col5=Int) or types=Dict(1=>String, 5=>Int), so you could specify the types of “all” columns, but override one [or some] column types.

**Comment by quinnj** [comment]
So it turns out this already works! I've added a test case to ensure it stays working.

**Comment by roflmaostc** [comment]
Does that still work?
I guess no, since 
```
julia> df = read_grading("test/simple_results.csv")
┌ Warning: `type` keyword argument is deprecated; a single type can be passed to `types` instead
```

What is the solution for that?

**Comment by nickrobinson251** [comment]
You can achieve the same thing by passing a function to `types` keyword. The function should take the column number and column name and return a type.

For example 'CSV.File("file.csv"; types=(i, name) -> name == :col1 ? String : Int)`

The docs would benefit from this being added as an example :) I'm sure a PR would be welcome if you could be tempted

Perhaps the corresponding test for this issue, added in https://github.com/JuliaData/CSV.jl/commit/430ff356ada39b96c6a3d788d5ea61e42ef46834, could also be updated to show this as a solution for when you don't want to give a type for every column individually, but this functionality is shown/tested elsewhere e.g. at 
https://github.com/JuliaData/CSV.jl/blob/2c02394b4ce11ee673ed1b6d0c811a98316bc2f9/test/basics.jl#L699
