### ISSUE TITLE
segfault when reading a tab-separated file with ignoreemptylines

### ISSUE THREAD

**Issue by pb866** [JuliaData/CSV.jl#577]
I am trying to read some pretty ugly files. They include copied content from a website and have unicode characters, are tab-separated and by default with `clrf` line endings (although changing to `lf` didn't have any effect).
This is an example file: [AAL432_01-SEP-2019_KPHX-PHOG.txt](https://github.com/JuliaData/CSV.jl/files/4256039/AAL432_01-SEP-2019_KPHX-PHOG.txt).

Reading the file without the `ignoreemptylines` flag works fine, with it results in a segfault:

```julia
import CSV
flight = CSV.read("AAL432_01-SEP-2019_KPHX-PHOG.txt", delim='\t', ignoreemptylines=true)

signal (11): Segmentation fault: 11
in expression starting at none:0
_platform_memmove$VARIANT$Haswell at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 79774919 (Pool: 79753660; Big: 21259); GC: 84
```

Also, the segfault is rather erratic and sometimes the first attempt to read the file works, while julia crashes repeating the task.

I am use CSV 0.5.24 together with Julia 1.3.1 on a Mac:
```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 6
```

**Comment by pb866** [comment]
I forgot, I was updating CSV from 0.5.18, where reading with `ignoreemptylines` worked fine.

**Comment by quinnj** [comment]
Ok, fix up: https://github.com/JuliaData/CSV.jl/pull/580. Turns out the issue didn't really have anything to do w/ `ignoreemptylines`, but it masked the problem when `false`. The issue was a combination of a column getting promoted to String type (from pooled type) in combination with a malformed row with missing columns.
