### ISSUE TITLE
Inconsistent resources used

### ISSUE THREAD

**Issue by pearcemc** [JuliaData/CSV.jl#58]
If I run 

```julia 
@elapsed pvs = CSV.read("chunky.csv")
```
The outcome is about 30 seconds, and fits comfortably into memory.

However if I run:

```julia
@elapsed pvs = CSV.read("chunky.csv", nullable=false, types=correct_types)
```

I end up having to crash out the REPL as the read consumes my entire memory and swap. 

The csv is perfectly formed with no null values.

Is there a good reason for this happening? Otherwise I find it counter-intuitive that a bunch of Nullable arrays containing data would be smaller than the data. Is something fancy like mmap going on?

EDIT: I think the damage is being done by supplying types, but still not sure why. I am also on the current `master` branch.

**Comment by nalimilan** [comment]
I think that's because `WeakRefString` objects can only be used with `NullableArray` at the moment, so lots of small strings need to be allocated when `nullable=true`. Does the dataset contain string columns? If you have a small number of categories, using a `CategoricalArray` would save a lot of memory (not sure it's supported yet.)

**Comment by pearcemc** [comment]
@nalimilan yes, that's correct. Is there a way to be able to specify WeakRefString as a datatype.

I'm still not entirely sure why this should explain the disparity though as:
- maximum length of any of the small strings is 14 UInt8s (so 14 bytes?) 
- minimum size of a WeakRefString appears to be 24 bytes (3 `Int64`s?)

I would have thought that the file should be small enough to fit into RAM using actual strings as:
```julia
N = 9999999
strlen = 14
colsize_mb = nrow*strlen*sizeof(UInt8))/1e6
#139.999986
```
There are 6 cols and I have 4GB RAM, so I'd expect a `String` version to take up roughly 840MB. 

I'd expect a `WeakRefString` version of the CSV to be similar. When I end my julia process after reading in with `WeakRefString` about 1GB RAM gets released (some cols are Int64), which is roughly consistent with the above numbers.

**Comment by nalimilan** [comment]
In Julia 0.5, `String` objects have a significant overhead due to their `Array` field (this will be much better in 0.6). I don't remember what the exact value is, but for short strings like yours it's a lot.

**Comment by pearcemc** [comment]
Thanks for following up. Investigating this the container size of a `String` seems to be 8 bytes.

```julia
julia> N = 10000;

julia> v = @timed ["hello" for i in 1:N]
(String["hello","hello","hello","hello","hello","hello","hello","hello","hello","hello"  …  "hello","hello","hello","hello","hello","hello","hello","hello","hello","hello"],0.045251508,1375438,0.0,Base.GC_Diff(1375438,1,0,12641,0,0,0,0,0))

julia> v[3]
1375438

julia> sizeof(v[1]) + length(v[1])*sizeof(v[1][1])
1300000

julia> tots = sizeof(v[1]) + length(v[1])*sizeof(v[1][1])
1300000

julia> tots/N
13.0
```

So if my strings are each 14 bytes + 8byte container = 22 bytes this should still be smaller than a 24 byte `WeakRefString`. 

So I'm still not sure the `String` overhead is sufficient to explain the nullable frame fitting into 1GB memory, but the typed version taking up 4GB + 4GBswap + ???.

**Comment by quinnj** [comment]
hey @pearcemc, thanks for opening an issue! Is there any chance you can share the file you're using? Could you also share your system info? I know there have been a few platform-specific issues before.

**Comment by pearcemc** [comment]
Sure, it's the `page_views_sample.csv` from [here](https://www.kaggle.com/c/outbrain-click-prediction/data).

My laptop `/proc/meminfo` looks like:
```
ubuntu@ubuntu-UX21E:/db/outbrain$ cat /proc/meminfo | head
MemTotal:        3946968 kB
MemFree:          413704 kB
Buffers:           61688 kB
Cached:          1299912 kB
SwapCached:       130404 kB
Active:          2008912 kB
Inactive:        1269984 kB
Active(anon):    1748120 kB
Inactive(anon):   993240 kB
Active(file):     260792 kB
```

I'm on Julia 0.5.0.

**Comment by quinnj** [comment]
This should be fixed on master since we're not relying on plain `Vector{Union{T, Null}}` for non-String columns, and `WeakRefStringArray` for String arrays, which will be memory efficient.
