### ISSUE TITLE
Warning; something went wrong trying to determine row positions for multithreading 

### ISSUE THREAD

**Issue by PernilleF** [JuliaData/CSV.jl#586]
Julia gives a warning when I load in data. I am using CSV.read and it does seem to be imported correctly. 

![Udklip2](https://user-images.githubusercontent.com/56150220/77539509-c9a44f00-6ea1-11ea-8d22-ca904a0ccad1.PNG)

**Comment by PernilleF** [comment]
`data = CSV.read("C:\\Users\\pff\\OneDrive - Vejdirektoratet\\LiRA\\DataM13\\M13_Mobile1_1pas_#1_dry.csv", delim=",", header=5, datarow=6, silencewarnings=true);`

**Comment by PernilleF** [comment]
The two dots is just where I inserted my path for the file.

**Comment by quinnj** [comment]
Thanks for reporting; can you perhaps share an example of the file, even if only privately with me so I can diagnose? (quinn.jacobd@gmail.com).

**Comment by PernilleF** [comment]
Unfortunately I cannot send you the file. But it seems to register an extra column with no input in any rows.

**Comment by quinnj** [comment]
Hmmm, there's not much I can do w/o a way to reproduce the issue; even with just a randomized data example of the file structure. Let me know if you find a way to be able to share.
