### ISSUE TITLE
First tab completion very slow after using CSV on julia v1.4.0

### ISSUE THREAD

**Issue by asasa137** [JuliaData/CSV.jl#589]
Hello,

I recently upgraded to julia v1.4.
I just noticed that just after "using CSV", I have a really long delay when I perfom a tab completion in the REPL.
For example : 

> using CSV
> strin[TAB]
It needs more than 1 minute to print the missing g and to be able to use the REPL.

Note that : 
- It is only for the first tab completion, if I perform another strin[TAB] it prints directly
- If I wait several minutes after using CSV, the first tab completion will still take ages
- I do not have any performance problem if I perform a tab completion before using CSV or after using another package
- I do not have any problem with an older version of Julia (v1.1)
- I have not tested on another computer
- CSV packages may lead for me to other latences as I first noticed that a function with CSV.read was kind of stuck 

I tried updating, removing, readd, rebuild the package but nothing changed...

Does anyone have tried this package with Julia v1.4.0 ?

Regards,

Axel

**Comment by quinnj** [comment]
This has been fixed in newer versions (at least) of Julia by a lot of the invalidation work
