### ISSUE TITLE
Error trying to convert `Bool` to `String`

### ISSUE THREAD

**Issue by ssfrr** [JuliaData/CSV.jl#593]
I have a CSV, and `CSV.read` and `CSV.File` both throw an error trying to load it:

```
MethodError: Cannot `convert` an object of type Bool to an object of type String
Closest candidates are:
  convert(::Type{String}, !Matched::Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R) at /home/sfr/.julia/packages/CategoricalArrays/dmrjI/src/value.jl:94
  convert(::Type{String}, !Matched::FilePathsBase.AbstractPath) at /home/sfr/.julia/packages/FilePathsBase/Oyg1p/src/path.jl:83
  convert(::Type{String}, !Matched::WeakRefStrings.WeakRefString) at /home/sfr/.julia/packages/WeakRefStrings/lqf5B/src/WeakRefStrings.jl:79
  ...
push!(::Array{String,1}, ::Bool) at array.jl:868
Parsers.Options(::Missing, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::Nothing, ::Nothing, ::Nothing, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at Parsers.jl:99
Parsers.Options(::Missing, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::UInt8, ::Nothing, ::Nothing, ::Nothing, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at Parsers.jl:62
file(::String, ::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Int64, ::Bool, ::Nothing, ::Bool, ::Bool, ::Array{String,1}, ::String, ::Nothing, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Nothing, ::UInt8, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Dict{Int8,Int8}, ::Bool, ::Float64, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::Nothing) at CSV.jl:382
#File#15(::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Int64, ::Bool, ::Nothing, ::Bool, ::Bool, ::Array{String,1}, ::String, ::Nothing, ::Bool, ::Char, ::Nothing, ::Nothing, ::Char, ::Nothing, ::UInt8, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Dict{Int8,Int8}, ::Bool, ::Float64, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::Nothing, ::Type{CSV.File}, ::String) at CSV.jl:258
CSV.File(::String) at CSV.jl:258
top-level scope at ch_results.jl:4
```

I'm guessing that the issue is that I have a column that should be typed as "string" (which seems to be detected correctly), but the first values are the string "true", so something in the parser is first converting them to `Bool` before `push!`ingt them.
A CSV that reproduces the issue is here:
https://gist.github.com/ssfrr/4921739d692a97ff47a96bf6f91d638a

edit: this also seems to happen even if the values are in the CSV as `"true"` (with quotes)

**Comment by ssfrr** [comment]
Oh, nvm, that's not the issue at all. The issue is that `Options` is getting called with `comment` = `true`. Looks like there's been some refactoring there, I'm trying on `master` now

**Comment by quinnj** [comment]
You need to make sure you have CSV.jl 0.6 with Parsers.jl 1.0. I'm pretty bummed that so many people have had issues with this; I thought I did the breaking Parsers.jl release correctly by bumping the major version, and doing a subsequent CSV.jl release w/ the compat correctly set on Parsers 1, but there have been a number of version mismatch issues like the one you reported.

**Comment by cyrillustan** [comment]
@ssfrr I actually have the same problem too. Can you explain how you solve it? Thanks!

**Comment by BioTurboNick** [comment]
Worth checking whether your own package has a "compat" entry for CSV that needs to be updated, because I had this issue couldn't figure out why it wasn't updating. Turns out I had pinned to v0.5.
