### ISSUE TITLE
CSV.file vs CSV.File

### ISSUE THREAD

**Issue by eirikbrandsaas** [JuliaData/CSV.jl#595]
Short description:
Why is there `CSV.file` and `CSV.File`, and why does `CSV.file()` not support keywords? (Note the lower/upper case f).
 
This is probably just me be being silly. In my code I had `CSV.file("file.csv")`. An update in the script that generates `file.csv` removed the headers, so I wanted to use `CSV.file("file.csv;header=false)`. However, that threw an error that took me quite long to figure out. Replacing `CSV.file` to `CSV.File` fixed the issue, but I couldn't find any documentation about the `file` vs `File` functions.

**Comment by quinnj** [comment]
`CSV.file` has been removed on master to avoid confusion
