### ISSUE TITLE
Reading CSV with boolean column

### ISSUE THREAD

**Issue by klangner** [JuliaData/CSV.jl#596]
hi I was reading data which contains boolean values. Here is an example:

no | name | active | rain | water | winddir | windlevel | temp
-- | -- | -- | -- | -- | -- | -- | --
502 | Gdynia ul. Inżynierska | True | True | False | False | False | False
503 | Gdynia ul. Janki Bryla | True | True | False | False | False | False

The problem is that the columns like `active` `rain` etc. are not recognised as having boolean values. They have string type.
When I read the same file using Python Pandas it looks ok:
```
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   no         107 non-null    int64 
 1   name       107 non-null    object
 2   active     107 non-null    bool  
 3   rain       107 non-null    bool  
 4   water      107 non-null    bool  
 5   winddir    107 non-null    bool  
 6   windlevel  107 non-null    bool  
 7   temp       107 non-null    bool  
 8   pressure   107 non-null    bool  
 9   humidity   107 non-null    bool  
 10  sun        107 non-null    bool  
dtypes: bool(9), int64(1), object(1)
memory usage: 2.7+ KB
```

So the problem is not with the file.
Do I miss something?

**Comment by quinnj** [comment]
In Julia, only `true` and `false` (all lowercase) are automatically detected as Bool; you can pass `truestrings=[“True”]` in order to parse `True` and similarly for false.

**Comment by klangner** [comment]
I see, thank you. Would you consider PR which will allow to parse boolean columns with different true, false values? Maybe by just converting field to lower case?

**Comment by quinnj** [comment]
@nalimilan @bkamins , (and anyone else), what do we think here? Should we, by default, parse things like `True`, `T`, `true` all as `Bool` columns? Or make users pass it in themselves? I don't feel too strongly; I feel like it could be equal parts convenient/inconvenient either way.

**Comment by bkamins** [comment]
First - I feel that if we decided to be more flexible we should:

1. be case sensitive, i.e. convert to `Bool` only if there are at most two distinct values in the column (i.e. mixing case like `[true, True, false False]` should not be allowed)
2. being more flexible could be the default (I do not feel to strongly about it either), but it should be possible to disable it. The reason is that the current implementation allows me to fully recover what was the contents of the original CSV file (i.e. reading it and saving it back will reproduce the original file) - allowing mixing does loose this feature;

> Would you consider PR which will allow to parse boolean columns with different true, false values?

@klangner - why do you think that what we currently have, i.e. that you can pass `truestrings` and `falsestrings`, is not enough?

**Comment by klangner** [comment]
I was taken by surprise here. I'm used to work with Python and Pandas where it works out of the box. But since I know how to solve it it is not a big deal. 
Having said that IMHO there is one reason to work with `true` and `True`. Pandas compatibility. It would be nice to have the possibility to save Bool column in Pandas and retrieve it as Bool in CVS.
That's why my suggestion was to be case insensitive.

**Comment by bkamins** [comment]
> It would be nice to have the possibility to save Bool column in Pandas and retrieve it as Bool in CVS.

A good point for the choice of the default.

**Comment by nalimilan** [comment]
Supporting "True", "TRUE", "False" and "FALSE" sounds like a good idea to me. I can't think of a situation where it would give an unexpected result.

OTC I'm less sure about allowing "T" and "F" by default, since that's not used by R by default either. Does any software write this kind of file?

**Comment by bkamins** [comment]
> I can't think of a situation where it would give an unexpected result.

When more than one value is mixed - e.g. `"True"` and `"TRUE"` and `"true"` in the same column - I think we should not allow this (i.e. in one column there should a unique string indicating `true` and a unique indicating `false` - maybe even we should enforce the same casing of them).

>  about allowing "T" and "F" by default

I would not allow them

**Comment by nalimilan** [comment]
Yes being strict regarding mixed casing would make sense. But in terms of implementation it's probably more tricky, and that would mean you can't just set `missingstrings=["true", "True", "TRUE"]` as the default (or that would prevent people from parsing values that mix different casings).

**Comment by klangner** [comment]
I don't have any strong opinion on mixed cases like `True` `true`. It looks strange to have this kind of values, but while working with data I saw many strange things :-).

Looking at the Pandas: 
  * If you have mixed cases even in different columns, Pandas will not recognize either column as boolean. If on the other hand all columns use consistent case, then it is ok.
  * Pandas also doesn't recognize `T` and `F`. (They will end up as objects)

**Comment by quinnj** [comment]
Yes, the implementation is tricky for mixed case; I think I'm fine moving the default to `truestrings = ["true", "True"]` and `faslestrings = ["false", "False"]` if @klangner would be willing to make a PR.

**Comment by bkamins** [comment]
if `truestrings = ["true", "True"]` and `faslestrings = ["false", "False"]` is the easiest way to go I think it is good enough (I preferred to be more strict, but if it is significantly complex to implement I think this default is acceptable)

**Comment by klangner** [comment]
Sure I can look at it. 
I will try to do it in more strict way (no mixing cases) since I agree that it is better to do it this way. But let me first look at the code. 
And please keep in mind that I just started learning Julia so I will need some time for it :-)

**Comment by bkamins** [comment]
@klangner - great. I would recommend you to start with a simple approach that @quinnj suggested. 

The better approach probably is quite challenging as CSV.jl uses a complex processing pipeline. If you are interested in the details I am copy-pasting @quinnj's own words on how the processing is done from Slack here so that they do not get lost as they are a very useful reference:

> The strategy in CSV.jl, is this:
> * A "tape" is allocated per column, and if the user didn't supply any types (so we're inferring types) and a non-string column is detected, a second tape is allocated
> * One tape is used to store the byte position and length of each cell for a column as a single UInt64; I think it's 48 bits used for the position, 16 bits for the length; this allows keeping track of essentially every cell in a file as a string
> * For non-string columns that we're inferring, we still track this position/length tape in case a string value is encountered later on in the file; we can then just promote the column type to string and switch the "value" tape to use the position/length tape
> * For the "value" tape (types of Int, Float64, Bool, Date, DateTime, Time, PooledString), the value is parsed and the raw bits are stored as a UInt64
> * For missing values, we choose a "sentinel" UInt64 bit pattern for each type that signals a missing; this is only tricky for Int64, where every bit pattern is a valid Int64 (all other types have "invalid" bit patterns that are unparseable); for Int64, we choose a very unlikely bit pattern, and if the value happens to be parsed, we cycle through other very unlikely bit patterns, recoding past parsed missing values as needed
> * We also use a single UInt8 "typecode" value to encode the types of each column as a Vector{UInt8}; we do our own type encoding for efficiency and simplicity; "missingness" is just setting the top bit, while other types each get their own bit (see https://github.com/JuliaData/CSV.jl/blob/master/src/utils.jl#L30), this allows us to do a very efficient "type promotion" as well, specific to csv-parsing rules (https://github.com/JuliaData/CSV.jl/blob/master/src/utils.jl#L98).
> * For multithreading, it's actually not too crazy: chunk up the file and let each thread work on a separate chunk w/ their own tapes/typecodes, and after all threads are done, we do a "merging" process where typecodes from each thread are all promoted and tapes are recoded as needed.

**Comment by klangner** [comment]
Great. Thank you.

**Comment by alecloudenback** [comment]
> 
> 
> Yes, the implementation is tricky for mixed case; I think I'm fine moving the default to `truestrings = ["true", "True"]` and `faslestrings = ["false", "False"]` if @klangner would be willing to make a PR.

Is "TRUE" excluded here intentionally? I've seen all upper more common than "True" iirc.

**Comment by quinnj** [comment]
For the implementation here, I would just change [this line](https://github.com/JuliaData/CSV.jl/blob/477c2334d6afdb093752cf3db6c7dc54739dfbc8/src/file.jl#L197) to `["true", "True", "TRUE"]` and the `falsestrings` default as well. Also change [this line](https://github.com/JuliaData/CSV.jl/blob/477c2334d6afdb093752cf3db6c7dc54739dfbc8/src/rows.jl#L104) for `CSV.Rows` to match (though `CSV.Rows` won't try to infer by default, so it doesn't make as much sense or matter as much there).

**Comment by quinnj** [comment]
Then run the tests and make sure nothing breaks; then add some tests to make sure things are getting inferred by default (for CSV.File); for that, you can either add something inline to `test/basics.jl` at the bottom of the file, or add an actual csv file in `testfiles/alternativebool.csv`, add an entry to the `testfiles` array in the `testfiles.jl` file, and make sure the test passes.
