### ISSUE TITLE
Support for custom types and/or formats

### ISSUE THREAD

**Issue by simonbyrne** [JuliaData/CSV.jl#598]
It would be useful to be able to support parsing of user-defined types, as well as custom formats, even if not integrated into the column type guessing framework (e.g. they would need to be provided manually).

We discussed this a while back on Slack, but there didn't appear to be an open issue.

**Comment by quinnj** [comment]
So I've been thinking a bit more about this. I don't think it's possible for us to do a really tight integration with the current parsing framework; it's really architected around the custom type encoding of the basic types and really compact/specialized representations in the tape structure (as UInt64s). That doesn't play well with trying to parse/store custom types.

Now, the good news is that columns parsed as String in `CSV.File` have a really efficient/compact representation. So if we can find an API for applying a custom format/parsing on a `CSV.Column{String}`, then that will basically be as efficient as if we did some "inline" integration. You can already just `map` over a `CSV.Column` and do whatever you want with the string, but we could also allow a `getindexraw` method that returned a `WeakRefString` if you wanted to avoid materializing the full `String` of each cell and had the ability to define your parsing method on a `WeakRefString`.

Thoughts?

**Comment by quinnj** [comment]
Going to close as dup of https://github.com/JuliaData/CSV.jl/issues/431; I've got some plans for this that will hopefully work out.
