### ISSUE TITLE
Support `quotecharopen` and `quotecharclose`

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/CSV.jl#60]
It would be useful if the quotes did not have to always open and close with the same character.
I have a delimitted format that looks like

```
{reddish}, {red, ish}
{darkish}, {dark, ish}
{greenish}, {green, ish}
....
{greyish}, {grey, ish}
```

Where every cell is quoted using `{` and `}`

**Comment by nalimilan** [comment]
Do you have examples of other software supporting this?

**Comment by oxinabox** [comment]
>Do you have examples of other software supporting this?

No, I don't.
I would have thought it would be a more common type of delimited format than it apparently is.
Feel free to close as "won't implement"

**Comment by quinnj** [comment]
Actually, I don't think this would be very hard to support.

**Comment by jonathanBieler** [comment]
While you are at it, supporting empty quotechar would be nice. Some discussion here: https://discourse.julialang.org/t/writing-dataframe-with-no-quotemarks/4599

**Comment by quinnj** [comment]
I have a local branch that supports this.

**Comment by quinnj** [comment]
This is supported on master with the switch to `CSV.File` (`CSV.read` still relies on the old `CSV.Source`, but there are plans to switch it over soon). You can now pass `CSV.File(file; openquotechar='{', closequotechar='}')`. 

Note for now, you can get a NamedTuple of Vectors on master by doing `using Tables; table = CSV.File(file; kwargs...) |> columntable`
