### ISSUE TITLE
Suppress Warnings

### ISSUE THREAD

**Issue by caseykneale** [JuliaData/CSV.jl#613]
So the ability to display warnings is really great, but - consider a file that is inconsistently delimitted but still A-Okay to load into CSV.jl? There should be an easy way to suppress these warnings because they consume a considerable part of file loading under those conditions.

IE: imagine 100k warning statements being displayed! It's not fun. A simple "verbose::Bool = true" flag for CSV.read would suffice I think.

**Comment by quinnj** [comment]
`silencewarnings=true`

**Comment by caseykneale** [comment]
didnt see it in the docs, sorry!!! Feel free to close!
