### ISSUE TITLE
CSV.read slow

### ISSUE THREAD

**Issue by Unoqualsiasi** [JuliaData/CSV.jl#62]
I have no idea why, but when i try to read a matrix with CSV.read it appears to be much slower than the classic readdlm. 

````
 @time s = CSV.read("file",delim= ' ',rows_for_type_detect=1,header=false);
 89.093956 seconds (796.97 M allocations: 18.175 GB, 5.53% gc time)

 @time a = readdlm("file");
 19.948536 seconds (466.06 k allocations: 4.317 GB, 8.12% gc time)

````

I wonder....what the hell am i doing wrong? The file is a matrix with 4845 rows and 24348 columns

**Comment by quinnj** [comment]
Are you able to share the file? Happy to take a look at what's going on here.

**Comment by Unoqualsiasi** [comment]
Sure i sent you an invitation on your Gmail account....the file is inside that Dropbox folder.

Thanks!

**Comment by quinnj** [comment]
@Unoqualsiasi, sorry it's taken so long to respond; my list of improvements to DataStreams & CSV was a tad long. I've been playing w/ this dataset though the last few days and it's a doozy. It's certainly non-traditional to have such a wide dataset. One question I had was if this dataset is meant to be transposed? It seems the first column is all strings like labels, and the rest of the columns are all integer codes, but the dataset has no header. Is that indeed the case? If it is, I actually have been working on a way to read in a csv file while transposing on the fly. For this csv file in particular, the read time goes down to 5-6s on my machine (vs. 70-80 on current 0.5 code).

**Comment by Unoqualsiasi** [comment]
So that dataset it's actually a small example of what you can find working in the genomic field......a lot of columns with only integers (usually o 1 and 2). The firs column is the ID (animal or person) and from the second column you have the SNPs. Usually you don't need labels because they are stored in a different file.
 Sometimes you need to transpose it, sometimes not. :D

**Comment by quinnj** [comment]
Ok, so the `CSV.TransposedSource` type is now officially on master. It allows convenient reading of transposed csv data into Julia structures. It's extremely accessible, you just have to do `CSV.read(file; transpose=true)`. For the original file here, I get timings of ~6s, which is about 3x `Base.readdlm` and the resulting dataset is probably much more useful (no additional transposing needed).

**Comment by biona001** [comment]
I am having a similar issue where CSV.read() on a 212×1005 matrix is excruciatingly slow (didn't complete in 3 minutes) while readtable() finishes in like 3 seconds. This is also a genetics dataset and I do not wish to transpose it later. I could share the dataset I'm reading as well

**Comment by animBreedTools** [comment]
I was using readtable, but upgraded to the newest version of Julia. I tried to implement CSV.read to my old codes, but a relatively small data of 2K*3K took forever.
