### ISSUE TITLE
CSV.File dateformat keyword with "mm/dd/yy" does not parse correctly

### ISSUE THREAD

**Issue by venuur** [JuliaData/CSV.jl#620]
I encountered a surprise when parsing a CSV (probably created from Excel) that used an American style short date "4/23/20". With `CSV.File(..., dateformat="mm/dd/yy")`, I would expected it to return the date "2020-04-23", but instead I got the date "0020-04-23".

Is there a way to parse this format? If not, I'm happy looking into how to implement it.

**Comment by quinnj** [comment]
This isn't a CSV.jl issue, but how Julia Date parsing works fundamentally (https://docs.julialang.org/en/v1.5-dev/stdlib/Dates/#Dates.DateFormat). It doesn't assume if a date belongs to a certain century. But it's usually pretty easy to fix after the fact, like:
```julia
df = DataFrame(CSV.File(file; dateformat="mm/dd/yy"))
df.date = df.date .+ Dates.Year(2000)
```
