### ISSUE TITLE
Full missing rows or random segfault when CSV with Windows newlines is read from Linux

### ISSUE THREAD

**Issue by diegozea** [JuliaData/CSV.jl#621]
I found this problem while running Julia inside the Windows Subsystem for Linux to read a CSV file created in Windows. The `readlines` function shows that Julia is removing `\n` but keeping `\r` in the problematic file. CSV reads the file given full missing rows:

![image](https://user-images.githubusercontent.com/2822757/80492684-ae2ad900-8964-11ea-8f90-4c1a455181ee.png)

Or it gives a segfault at the `show` step of the resulting `DataFrame`.

**Comment by quinnj** [comment]
Any chance you can share the file?

**Comment by lannet2000** [comment]
I did a quick test with a file made in Windows that have both EOL char and not notice this problem

**Comment by yakir12** [comment]
I get the following from [this](https://www.dropbox.com/s/yyijskhz76a68lh/factors.csv?dl=0) file:
```julia
julia> using DataFrames, CSV

julia> DataFrame(CSV.read("factors.csv"))
thread = 1 warning: only found 1 / 2 columns on data row: 1. Filling remaining columns with `missing`
thread = 1 warning: only found 1 / 2 columns on data row: 3. Filling remaining columns with `missing`
thread = 1 warning: only found 1 / 2 columns on data row: 5. Filling remaining columns with `missing`
thread = 1 warning: only found 1 / 2 columns on data row: 7. Filling remaining columns with `missing`
thread = 1 warning: only found 1 / 2 columns on data row: 9. Filling remaining columns with `missing`
thread = 1 warning: only found 1 / 2 columns on data row: 11. Filling remaining columns with `missing`
thread = 1 warning: only found 1 / 2 columns on data row: 13. Filling remaining columns with `missing`
14×2 DataFrame
│ Row │ factor            │ level          │
│     │ String?           │ String?        │
├─────┼───────────────────┼────────────────┤
│ 1   │ missing           │ missing        │
│ 2   │ transfer          │ 50m            │
│ 3   │ missing           │ missing        │
│ 4   │ transfer_location │ feeder         │
│ 5   │ missing           │ missing        │
│ 6   │ nest2feeder       │ 130 cm         │
│ 7   │ missing           │ missing        │
│ 8   │ experience        │ experienced    │
│ 9   │ missing           │ missing        │
│ 10  │ azimuth           │ 280 \xa1       │
│ 11  │ missing           │ missing        │
│ 12  │ place             │ vryburg        │
│ 13  │ missing           │ missing        │
│ 14  │ species           │ C.fulvopilosus │
```

**Comment by lannet2000** [comment]
Hi,
the problem is dou to the end of line char, at the end of each line you have this sequence  CR CR LF
or if you look at it with an hexadecimal program  (like Oketa on KDE-Manjaro/Fedora) 013 013 010 in Decimal.
CSV will strip CR and LF but we will have one more CR.
Hope this help you.

**Comment by yakir12** [comment]
so, from what you're saying this is a problem with the problem that was used to save that file?

Is the best way to deal with this fixing it in the source? I think the user that saved their data used `TextEdit` on a mac.

**Comment by lannet2000** [comment]
If the user can create a correct file yes , I usually fix those problem for my clients with a pre-processing  program or in Linux you can open the file in Oketa and replace the CRCRLF with Find-Replace or just use Julia and create a little program that do the substitution.
:)

**Comment by yakir12** [comment]
To be honest, if
> use Julia and create a little program that do the substitution

is viable, then that would be a good PR to this very package, don't you think? I mean, if CSV tries to read a file and a / each row ends with an extra CR, then it could automatically strip it away (and an option kwrd can override that).

**Comment by lannet2000** [comment]
Yes I can agree, they have to add a parsing option for issue like this one. 
So we can tell the CSV what is the end row chars.

**Comment by yakir12** [comment]
Wah, just had a look at src/detection.jl seems pretty far from a straight forward change to me... I think I'll let the owner to weigh in on this before I attempt a PR...

**Comment by lannet2000** [comment]
Yes the detection.jl is not easy to change , yes better if the owner change the way it save the file, sorry but is a few year I quit using a MAC ;)

**Comment by yakir12** [comment]
Right, I'm pinging you Jacob @quinnj since the last comment from you on this issue was 42 days ago (used `Dates` to calculate that with `Date(now()) - Date(2020, 4, 28)` :wink:) and @lannet2000 and I concluded our discussion, hope that's ok with you.

**Comment by lannet2000** [comment]
Sure Ok for me :)

**Comment by yakir12** [comment]
In the meantime, `ignoreemptylines` fixes this completely:
```
julia> CSV.read("factors.csv", ignoreemptylines = true)
7×2 DataFrame
│ Row │ factor            │ level          │
│     │ String            │ String         │
├─────┼───────────────────┼────────────────┤
│ 1   │ transfer          │ 50m            │
│ 2   │ transfer_location │ feeder         │
│ 3   │ nest2feeder       │ 130 cm         │
│ 4   │ experience        │ experienced    │
│ 5   │ azimuth           │ 280 \xa1       │
│ 6   │ place             │ vryburg        │
│ 7   │ species           │ C.fulvopilosus │
```

**Comment by lannet2000** [comment]
Wonderfull :)

**Comment by quinnj** [comment]
Yes, `ignoreemptylines` is the right solution if you're getting an extra `CR` in your file; there's nothing else we could change at a file/parser level that would do anything different.
