### ISSUE TITLE
Issue reading CSV files

### ISSUE THREAD

**Issue by vishaluk** [JuliaData/CSV.jl#622]
I downloaded latest JuliaPro(1.4.1-1) and added CSV package. But I am unable to read any csv file. Simple command of CSV.read(filepath) gives me following error -

_MethodError: no method matching streamtypes(::Type{DataFrame})_

I have DataFrames installed. Not sure what I am missing??
I am on windows 10 Pro.

**Comment by quinnj** [comment]
That error suggests you have some very old versions of things (i.e. DataStreams, an archived package). You'll want to try updating things. cc: @aviks
