### ISSUE TITLE
error row positions for multithreading;

### ISSUE THREAD

**Issue by johanmon** [JuliaData/CSV.jl#625]
Something is wrong in the threaded version of parsing files. 

The function findrowsstarts!() in  detection.jl is (from my understanding) jumping into the file and hopes to find the next line to parse. It does so using **ncols** which is the expected number columns. This might not be true since **ncols** is the number of headers provided by the user in CSV.File().

My program broke when trying in multi-threaded mode since I only bothered about the two first columns in the file (which worked in single threaded mode). 

Should I try to find a solution?

**Comment by quinnj** [comment]
Hi @johanmon , sorry for the slow response here. I _think_ I'm following what you're saying, but do you by chance have an example file + the julia commands you used and what went wrong? I just want to make sure as I look into it, we get your case solved/figured out.

**Comment by johanmon** [comment]
Hi,
the problem was that I had a file with more fields that I was interested in. The file test.csv has three fields but if I only need the two first I did:

  data = CSV.File("test.csv", header=[:one, :two], silencewarnings=true) 

worked fine. I then saw that there was multithreaded  suport and did:

  data = CSV.File("test.csv", header=[:one, :two], silencewarnings=true, threaded=true) 

that crashed.  The problem that I found was the ncols was set to 2 (since I only requested 2 fields) but the file contained three columns (afair). The multithreading simply jumps into the file and tries to find the next row but when it gets the numbers of columns wrong it breaks. 

8<----- test.csv
1,2,3
1,2,3
1,2,3

**Comment by quinnj** [comment]
Thanks for the explanation @johanmon; the correct way to do what you'd like is to specify `CSV.File(file; select=[:one, :two])`; this ensures the parsing still accounts for the actual # of columns in the file. I'm going to try and see if there's something we can do to warn users about what you tried to do.
