### ISSUE TITLE
Single threaded CSV.read twice slower than single threaded R's fread

### ISSUE THREAD

**Issue by deepaksuresh** [JuliaData/CSV.jl#627]
On this [dataset](https://www.kaggle.com/xiaodaizj/mortgageriskfeaturetools),  `CSV.read` takes about 79s while `fread` from `data.table` takes 36s. The times are from `@btime` for Julia and microbenchmark for R. Below is a plot of read times as the number of threads are increased.
![CSV loading_ R vs Julia](https://user-images.githubusercontent.com/9796812/81373979-b41a7a00-911b-11ea-9b54-6014e82fc087.png)

**Comment by quinnj** [comment]
This should be fixed on master (speed is about 2x faster on master vs. 0.6.2)
