### ISSUE TITLE
memory mapping failed with hyperthreading

### ISSUE THREAD

**Issue by FredSoftwares** [JuliaData/CSV.jl#628]
Hi,
I reopen [this issue](https://github.com/JuliaData/CSV.jl/issues/488) because I had the same problem with julia 1.4.1 and
[336ed68f] CSV v0.6.2
[a93c6f00] DataFrames v0.21.0

the problem is related to multithread and probably hyperthreading  [see this post](https://discourse.julialang.org/t/memory-mapping-failed-when-reading-many-csvs/27979/12)

A temporary solution is to disable multithreading using threaded=false

**Comment by quinnj** [comment]
@FredSoftwares , thanks for the report; is there any way you can share the file that causes problems for you?

It would also be helpful if you shared what OS you're on.

**Comment by FredSoftwares** [comment]
@quinnj 
I send you a [link](https://wetransfer.com/downloads/48026fe9ab84f594f496853002cbfca720200512163752/0165e19b1b3eae7bdf97839fde77781a20200512163811/5c1115) to download the file. The link will be available for 7 days.
This file produce and error on 
- Linux Manjaro up to date and bi-Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
- I also had the pbm on a super computer with bi-xeon too and CentOS (or Redhat not sure)
This file does not produce an error on
- Linux Manjaro up to date and Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (no hyperthreading)
That's why I suppose this bug is related to hyperthreading.
Try to read this file with CSV.read(), if you have no error, read it again, sometimes the error was observed at the 2nd read.
Thanks for this package ! I think it is not easy to fix ;-)

**Comment by quinnj** [comment]
@FredSoftwares, very sorry for the slow response here. Unfortunately, I wasn't able to grab the file and the link has expired now; is it possible to share again?

**Comment by FredSoftwares** [comment]
@quinnj 
The file is [here](https://we.tl/t-4I10s7vgFz) for 7 days. And below are the error produced by this file

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using CSV
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]

julia> CSV.read("CSV_test.csv")
ERROR: LLVM ERROR: out of memory

julia> CSV.File("CSV_test.csv") |> DataFrame!
ERROR: TaskFailedException:
SystemError: memory mapping failed: Ne peut allouer de la mémoire
Stacktrace:
 [1] systemerror(::String, ::Int32; extrainfo::Nothing) at ./error.jl:168
 [2] #systemerror#50 at ./error.jl:167 [inlined]
 [3] systemerror at ./error.jl:167 [inlined]
 [4] mmap(::Mmap.Anonymous, ::Type{Array{UInt64,1}}, ::Tuple{Int64}, ::Int64; grow::Bool, shared::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Mmap/src/Mmap.jl:209
```

**Comment by quinnj** [comment]
@FredSoftwares , have you tried running the code on current master branch? I'd be really interested if you still see errors; the current master branch has quite a large refactoring of hte multithreaded code, and I dont' see any issues on osx.

**Comment by quinnj** [comment]
By the way, you can get the current master branch code by doing `] add CSV#master`

**Comment by FredSoftwares** [comment]
@quinnj  with CSV#master I don't have the error
```

              _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> add CSV#master
    Cloning git-repo `https://github.com/JuliaData/CSV.jl.git`
   Updating git-repo `https://github.com/JuliaData/CSV.jl.git`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed SentinelArrays ─ v1.2.0
   Updating `~/.julia/environments/v1.4/Project.toml`
  [336ed68f] ~ CSV v0.6.2 ⇒ v0.6.2 #master (https://github.com/JuliaData/CSV.jl.git)
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [336ed68f] ~ CSV v0.6.2 ⇒ v0.6.2 #master (https://github.com/JuliaData/CSV.jl.git)
  [91c51154] + SentinelArrays v1.2.0

julia> using CSV#master
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
julia> using DataFrames

julia> CSV.File("CSV_test.csv") |> DataFrame!
4001×1399 DataFrame. Omitted printing of 1385 columns
```

**Comment by quinnj** [comment]
That's great to hear; indeed, the master branch has quite a different algorithm in terms of memory and multithreading that should hopefully be much easier on systems.
