### ISSUE TITLE
 MethodError: no method matching streamtypes(::Type{DataFrame})

### ISSUE THREAD

**Issue by earthlong** [JuliaData/CSV.jl#629]
I am getting the above error when trying to read a simple file which contains

> a,b,c
> 1,2,3
> 2,4,6
> 3,6,9

Here is how I am trying to read it

```
using CSV
df = CSV.read("Test.csv")
```

Here is the detailed message
```
MethodError: no method matching streamtypes(::Type{DataFrame})
Closest candidates are:
  streamtypes(!Matched::Type{Array}) at C:\Users\earthlong\.juliapro\JuliaPro_v1.4.0-1\packages\DataStreams\mEqAy\src\namedtuples.jl:11
  streamtypes(!Matched::Type{#s16} where #s16<:NamedTuple) at C:\Users\earthlong\.juliapro\JuliaPro_v1.4.0-1\packages\DataStreams\mEqAy\src\namedtuples.jl:53
  streamtypes(!Matched::Type{CSV.Sink}) at C:\Users\earthlong\.juliapro\JuliaPro_v1.4.0-1\packages\CSV\tT4Xy\src\Sink.jl:34
in top-level scope at tst.jl:41
in read at CSV\tT4Xy\src\Source.jl:347
in read at CSV\tT4Xy\src\Source.jl:347 
in #read#35 at CSV\tT4Xy\src\Source.jl:348
in  at DataStreams\mEqAy\src\query.jl:516
in #stream!#111 at DataStreams\mEqAy\src\query.jl:538
in  at DataStreams\mEqAy\src\query.jl:573
in #stream!#113 at DataStreams\mEqAy\src\query.jl:574
```

**Comment by nalimilan** [comment]
Can you check the version of CSV you're using? It doesn't use DataStreams for a long time anymore.

**Comment by earthlong** [comment]
Thanks for getting back. It is 0.3.1. I updated it now and it is the same version.

**Comment by nalimilan** [comment]
Then there's a problem with your installation. The last version is 0.6.2 (!). Maybe you have installed some packages which have conflicting requirements? Or a JuliaPro issue? You can try with a clean environment using `julia --project=some_directory`.

**Comment by earthlong** [comment]
It is the issue with JuliaPro which does not let me upgrade it. I tried Julia non-pro version, however that installs to v0.6.0 and not to 0.6.2

**Comment by nalimilan** [comment]
That's weird. Anyway I encourage you to file an issue against JuliaPro.

**Comment by earthlong** [comment]
Thank you for your help.
