### ISSUE TITLE
Cornercases in CSV.read with skipto and datarow keywords

### ISSUE THREAD

**Issue by IlyaOrson** [JuliaData/CSV.jl#631]
I found some unintuitive cornercases between `skipto`, `datarow` and `header` keywords when dealing with some csv files with description strings at the start of the file (like this one: [dummy.txt](https://github.com/JuliaData/CSV.jl/files/4685202/dummy.txt)).

It works great if only header is specified:  `CSV.read("dummy.txt", header=8)`

Cornercases:
* `CSV.read("dummy.txt", skipto=8)`: Parsed only 1 column instead of data with new "first" line as header. 
* `CSV.read("dummy.txt", datarow=9)`:  Parsed only 1 column instead of headerless data.
* `CSV.read("dummy.txt", skipto=2, header=8)`: Avoids correctly the description strings but repeats the header line in the data.
* `CSV.read("dummy.txt", skipto=8, datarow=2)`: I thought this would throw an error but instead parsed 1 column.
* `CSV.read("dummy.txt", skipto=18, header=8)`: I though this would throw because header was skipped but it worked the same as `CSV.read("dummy.txt", datarow=18, header=8)`

**Comment by quinnj** [comment]
I think there are some things we can clarify/clean up here:
* `skipto` and `datarow` are treated identically; they both specify on which row the _data_ of a file starts; they don't affect the `header` argument at all
* `header` can be an Integer specifying the row where the column names can be found; if unspecified, the `datarow` is assumed to be the next row after `header`.

So I can certainly understand the confusion in your cases:
* only specifying `skipto` or `datarow` means the `header` argument still defaults to `1`
* we should throw an error if `skipto` or `datarow` are < `header`
* we should probably throw an error if both `skipto` and `datarow` are specified
* `header=8` and `skipto=18` is valid; that says the header is found on row 8, then skip to row 18 to start reading data
