### ISSUE TITLE
FilePathsBase 0.8 compat restriction causes a downgrade catastrophe

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/CSV.jl#636]
Took me a while to figure out what was happening, but it turns out that this package restricting to FilePathsBase 0.8 was causing just about everything in my environment to downgrade to ancient versions.  Results will of course depend strongly on your environment, but suffice it to say in some cases this can be a huge problem.  Will attempt a fix.

**Comment by quinnj** [comment]
Fixed via #632
