### ISSUE TITLE
Memory bloat when reading floats

### ISSUE THREAD

**Issue by stillyslalom** [JuliaData/CSV.jl#640]
As noted on [Discourse](https://discourse.julialang.org/t/why-dataframes-v-0-21-2-julia-v1-4-2-requires-more-memory-than-the-previous-version/41171/13?u=stillyslalom), reading Float64 dataframes creates a huge memory footprint (much larger than the underlying file) when  `copycols = false`.
Generating a medium-sized dataframe with one Float64 column,
```
julia> a = rand(10^7);

julia> Base.summarysize(a)
80000040

julia> df = DataFrame(a = a);

julia> Base.summarysize(df)
80000624

julia> CSV.write("test.csv", df)
"test.csv"
```
…then reading it back,
```
julia> df2 = CSV.read("test.csv")
10000000×1 DataFrame
│ Row      │ a          │
│          │ Float64    │
├──────────┼────────────┤
│ 1        │ 0.150381   │
│ 2        │ 0.159632   │
│ 3        │ 0.869726   │
 ...

julia> Base.summarysize(df2.a)
284457443

julia> stat("test.csv").size
192696891
```
Additionally, even with `copycols = true`, the read operation requires several times more memory than the size of the data, which presents an obstacle when dealing with large datasets.

**Comment by quinnj** [comment]
This is fixed on master: 
```julia
julia> Base.summarysize(df2.a)
80000544

```
