### ISSUE TITLE
incorrect line reported on parsing error

### ISSUE THREAD

**Issue by klaff** [JuliaData/CSV.jl#642]
Example MWE:
```
using CSV

# create a csv file which is intentionally broken by  having another set of headers at the end of the file
open("MWE.csv", "w") do io
    write(io, "A,B\n")
    for i ∈ 1:4000
        write(io, "1.0, 1.0\n")
    end
    write(io, "A,B\n") # erroneous values at line 4001
end

# now let's try to read the csv file
f = CSV.read("MWE.csv",types=fill(Float64,2))
```
This gives the following error:
```
julia> 
thread = 2 warning: error parsing Float64 on row = 1000, col = 1: "A,", error=INVALID: SENTINEL | DELIMITED | INVALID_DELIMITER
thread = 2 warning: error parsing Float64 on row = 1000, col = 2: "B
", error=INVALID: SENTINEL | NEWLINE | EOF | INVALID_DELIMITER
```
Note that the bad data is in row 4000, but the error report states that it is in row 1000. This does not occur on much shorter files.

Observed with Julia 1.4.1 and 1.5.0-beta1.0 and CSV v0.6.2.

**Comment by quinnj** [comment]
Thanks for reporting; the issue here is when we go into multithreaded parsing mode (on larger files); each thread is parsing its own chunk of the file and reports its own "local" row, but that obviously doesn't make sense in aggregate. Let me see what we can do to improve the error message here.

**Comment by klaff** [comment]
Awesome, thank you!
