### ISSUE TITLE
can't write file .ERROR: MethodError: no method matching schema(::DataFrame)

### ISSUE THREAD

**Issue by liwen-alt** [JuliaData/CSV.jl#644]
ERROR: MethodError: no method matching schema(::DataFrame)
![image](https://user-images.githubusercontent.com/63285313/84594569-c9569700-ae85-11ea-9d08-2c17fd03de56.png)
![image](https://user-images.githubusercontent.com/63285313/84594582-d8d5e000-ae85-11ea-84dd-e67ca9fe7b2d.png)

**Comment by quinnj** [comment]
You seem to be stuck on a very old version; you'll want to check if you have any packages pinned or try manually upgrading some dependencies in order to get the latest version.

**Comment by liwen-alt** [comment]
The latest CSV package is which version.
where i can know it is version squence.

**Comment by quinnj** [comment]
https://github.com/JuliaData/CSV.jl/releases
