### ISSUE TITLE
Merge `header` and `writeheader` `CSV.write` arguments?

### ISSUE THREAD

**Issue by nalimilan** [JuliaData/CSV.jl#655]
`CSV.write` has both a `header` and a `writeheader` argument. The latter is a Boolean, while the former is a vector. At the same time, `CSV.File` has a single `header` argument which can be either an integer or range (indicating the rows), a vector of names, or a Boolean. Wouldn't it make sense to deprecate `writeheader` in favor of `header` for consistency?

**Comment by quinnj** [comment]
Yeah, good idea. See https://github.com/JuliaData/CSV.jl/pull/660
