### ISSUE TITLE
Switch (back) from at-threads to at-spawn to support multithreading from inside a Task

### ISSUE THREAD

**Issue by NHDaly** [JuliaData/CSV.jl#657]
I can't exactly remember the reasons, but I know that `@threads for` only works from the "main task"! 😮 
```julia
julia> Threads.nthreads()
3

julia> @sync Threads.@spawn begin
           Threads.@threads for i in 1:Threads.nthreads()
               @info i, Threads.threadid()
           end
       end
[ Info: (1, 2)
[ Info: (2, 2)
[ Info: (3, 2)
Task (done) @0x0000000114b8a650

julia> Threads.@threads for i in 1:Threads.nthreads()
           @info i, Threads.threadid()
       end
[ Info: (2, 2)
[ Info: (3, 3)
[ Info: (1, 1)

julia>
```

If possible, we should avoid using this inside library code like CSV, because it makes multithreading inaccessible from spawned tasks (e.g. for code that's handling requests to a server).

**Comment by NHDaly** [comment]
👍 Thanks @quinnj! 352a2b1 looks great.

The difference compared with `Threads.@threads` is of course that with `@spawn` we can't guarantee that those will actually all get spawned onto separate threads, but that's also sort of the whole point. :) If another thread is busy, then one of those tasks just wait, but also that's just fine because there's nothing else to do! Then if one of these tasks finishes before the other thread is ready, then we can just pick up the waiting task. So this is more flexible and should be better overall. :)


One interesting question that this poses, then, is just _how many_ tasks to spawn. I think going with `nthreads()` seems reasonable here: in the normal case, this is the only thing going on, and we'll use all the threads. The benefit of using more Tasks with smaller chunks would be if we expect different tasks will take unexpectedly varying amounts of time. If one Task takes 10x longer than all the others, we may have idle threads that could've been doing work if we'd spawned more smaller chunks. The problem with spawning many smaller chunks is of course the overhead of spawning tasks and task switching. So in this case, if we expect that every task should take approximately the same amount of time (which is a reasonable expectation as they're all performing the same task: parsing strings), then I think spawning N tasks makes sense.

This is a knob that could be tuned, maybe with some benchmarks? My guess is that maybe 1.5N - 2N tasks might be the happiest middle ground, especially since julia tasks are fairly cheap, but it probably depends a lot on the data.

Cheers! :)

**Comment by quinnj** [comment]
Yeah, I've pondered that question as well (how many tasks to spawn). In terms of the output `ChainedVector`, the indexing operation uses binary search, so having fewer "chunks" means slightly quicker indexing times. In a local branch, I actually am allowing passing a `threads=X` keyword argument, which should allow a little flexibility if people want to limit or increase the # of tasks that get spawn.

**Comment by NHDaly** [comment]
Yeah, makes sense!

To me, i think the most useful input is whether all the tasks are expected to take the same amount of time, or if it's expected that they can vary quite a bit. if we think there could be lots of variance, then yeah providing the control to spawn more smaller tasks might be worth it. 

🚀

**Comment by quinnj** [comment]
I would expect work across chunks to be very uniform.
