### ISSUE TITLE
Current buffer position is ignored when `header=[]` is passed to CSV.File()

### ISSUE THREAD

**Issue by lbilli** [JuliaData/CSV.jl#668]
Starting with CSV v0.7.0, specifying `header=[]` in `CSV.file()` causes a partially read `source` buffer to be parsed from the beginning. 

Here's an example to clarify the issue:
```julia
julia> using CSV
julia> buf = IOBuffer("""
       garbage
       a,b
       1,2
       """)
julia> readline(buf)   # discard the first line
"garbage"

julia> CSV.File(buf)   # read the rest: ok
1-element CSV.File{false}:
 CSV.Row: (a = 1, b = 2)

julia> CSV.File(buf, header=false)      # read again: ok
2-element CSV.File{false}:
 CSV.Row: (Column1 = "a", Column2 = "b")
 CSV.Row: (Column1 = "1", Column2 = "2")

julia> CSV.File(buf, header=["A", "B"]) # read and specify header names
3-element CSV.File{false}:
 CSV.Row: (A = "garbage", B = missing)  # <- this line shouldn't be here
 CSV.Row: (A = "a", B = "b")
 CSV.Row: (A = "1", B = "2")
```

**Comment by lbilli** [comment]
Also, interestingly, the buffer current position is not affected by `CSV.File()`.
Is it by design?

**Comment by quinnj** [comment]
Thanks for the report! I have a fix here: https://github.com/JuliaData/CSV.jl/pull/671.

And yes, currently `CSV.File` doesn't "consume" the IOBuffer because it just parses directly from the buffer underneath.
