### ISSUE TITLE
preallocated

### ISSUE THREAD

**Issue by yakir12** [JuliaData/CSV.jl#67]
Wouldn't it be grand to have an option for reading data into a preallocated sink? 

Something like:

```julia
# I know I have a bunch of files with 20 columns and 1000 rows
types = fill(Float64, 20)
x = DataFrame(types, Symbol.('a':'t'), 1000)
for file in files
     CSV.read!(file, x)
     # do something with x
end
```
You could even make `read` farm all the details from the preexisting sink (e.g. dimensions and column types).

**Comment by quinnj** [comment]
This is supported by default in the DataStreams framework (as long as the Sink supports pre-allocation). In the case of DataFrames, it will check to ensure the Source columns/types/rows exactly match the provided DataFrame and if so, no extra allocation will occur (i.e. the pre-allocated DataFrame will be used). The usage is:
```julia
df = DataFrame(...) # pre-allocate DataFrame w/ correct column names/types/rows
for file in files
    CSV.read(file, df)
    # do something with df
end
```

**Comment by yakir12** [comment]
Sweet!
