### ISSUE TITLE
SentinelArray instead of Array{Union{Missing,Float64},1}

### ISSUE THREAD

**Issue by Byrth** [JuliaData/CSV.jl#674]
```
fr = DataFrame!(CSV.File("gist.csv"))
fr2 = DataFrame(CSV.File("gist.csv"))
```
gist.csv: https://gist.github.com/Byrth/eb0b458453baba02b1cdf9a25bb559ea

These both result in a SentinelArray for the :var_cont1 column. It used to convert (in my opinion properly) to an `Array{Union{Float64,Missing},1}`.

I can revert to the old behavior through array comprehension:
~~~
fr.var_cont1 = [v for v in fr.var_cont1] # This makes it an Array again
~~~

Is this a bug?

**Comment by quinnj** [comment]
The idea here is that a `SentinelVector{Float64}` should in every respect act just like a `Vector{Union{Missing, Float64}}`, hence the no-conversion when copying. Are you running into issues w/ SentinelVector?

**Comment by Byrth** [comment]
I had a signature for `AbstractArray{T,1} where T <: AbstractString` and it was consequently failing. Is there a more Julian way to specify that?

**Comment by quinnj** [comment]
That seems to suggest that your eltype needs to be a subtype of `AbstractString`, right? So it wouldn't matter if you had a `SentinelVector{Float64}` or `Vector{Union{Missing, Float64}}`

**Comment by Byrth** [comment]
I convert it to string using
~~~
my_fun( string.(var_cont1) )
~~~

However, when I do that with a SentinelArray the resulting `eltype` is still reported as `Union{Missing,String}` even though all the values are now strings.

**Comment by quinnj** [comment]
Will be fixed by https://github.com/JuliaData/SentinelArrays.jl/pull/15

**Comment by quinnj** [comment]
Fix merged and just tagged a new release w/ the fix; I realized that returning SentinelArrays from broadcasting doesn't really gain you anything and we just kept running into corner cases that didn't do what you want. As `SentinelVector{T}` is supposed to be a drop-in replacement for `Vector{Union{T, Missing}}`, let's let the latter get returned in broadcasting.
