### ISSUE TITLE
`skipto` and `limit` not working properly in `CSV.read` for bigger files

### ISSUE THREAD

**Issue by daschw** [JuliaData/CSV.jl#675]
```julia
julia> using CSV, DataFrames

julia> fn = tempname() * ".csv"
"/tmp/jl_kIioXK.csv"

julia> df = DataFrame(rand(10000, 5))
10000×5 DataFrame
│ Row   │ x1       │ x2        │ x3       │ x4        │ x5        │
│       │ Float64  │ Float64   │ Float64  │ Float64   │ Float64   │
├───────┼──────────┼───────────┼──────────┼───────────┼───────────┤
│ 1     │ 0.934631 │ 0.583556  │ 0.33462  │ 0.234911  │ 0.678517  │
│ 2     │ 0.64835  │ 0.616996  │ 0.604498 │ 0.0836913 │ 0.414417  │
│ 3     │ 0.310521 │ 0.0724802 │ 0.821357 │ 0.561016  │ 0.97811   │
⋮
│ 9997  │ 0.178889 │ 0.0507727 │ 0.625109 │ 0.055949  │ 0.75317   │
│ 9998  │ 0.167764 │ 0.289579  │ 0.881564 │ 0.851277  │ 0.750682  │
│ 9999  │ 0.123207 │ 0.916808  │ 0.145744 │ 0.23233   │ 0.0919167 │
│ 10000 │ 0.645683 │ 0.421406  │ 0.176605 │ 0.785924  │ 0.728946  │

julia> CSV.write(fn, df)
"/tmp/jl_kIioXK.csv"

julia> CSV.File(fn, skipto = 1000, limit = 1000)
263-element CSV.File{true}:
 CSV.Row: (x1 = 0.3669435437168189, x2 = 0.15861978058316706, x3 = 0.44568794483489405, x4 = 0.07764006538187229, x5 = 0.4969758537623905)
 CSV.Row: (x1 = 0.7339499411690691, x2 = 0.9857704353467884, x3 = 0.8285803878100444, x4 = 0.08975203997476244, x5 = 0.01365104160251196)
 CSV.Row: (x1 = 0.5965072444144721, x2 = 0.18929762719080356, x3 = 0.5256202071397447, x4 = 0.6994997793893394, x5 = 0.5033149638305427)
 CSV.Row: (x1 = 0.15893179347601816, x2 = 0.5361361589059332, x3 = 0.9684062796139967, x4 = 0.21935364741865393, x5 = 0.4713024569633273)
 CSV.Row: (x1 = 0.7016548488099148, x2 = 0.49285970601293294, x3 = 0.0010953677464398126, x4 = 0.8849514774329692, x5 = 0.1867899538766935)
 ⋮
 CSV.Row: (x1 = 0.42764166827705385, x2 = 0.6315775883498909, x3 = 0.44440886396622714, x4 = 0.3326509201176604, x5 = 0.8951693069037656)
 CSV.Row: (x1 = 0.71836584574358, x2 = 0.31881788750669715, x3 = 0.06577632674227374, x4 = 0.10785718210443718, x5 = 0.9993607483488669)
 CSV.Row: (x1 = 0.4412219007833744, x2 = 0.1611313208725238, x3 = 0.7174764610213975, x4 = 0.4943942778921482, x5 = 0.9586586421585581)
 CSV.Row: (x1 = 0.23476657727741967, x2 = 0.40090951367210637, x3 = 0.4529022024943181, x4 = 0.819388593623587, x5 = 0.69924489729061)
 CSV.Row: (x1 = 0.4291562187029998, x2 = 0.12789710523046538, x3 = 0.7512997526085206, x4 = 0.5349789766450448, x5 = 0.6877754160146912)

(@csv) pkg> st
Status `~/.julia/environments/csv/Project.toml`
  [336ed68f] CSV v0.7.1
  [a93c6f00] DataFrames v0.21.4
```
Only 263 instead of 1000 rows are read. This used to work with CSV 0.6.2

**Comment by quinnj** [comment]
Hmmm, yeah, `limit` can be just a bit finicky with threaded parsing; previously, specifying `limit` also meant `threaded=false`, so that's an easy way you can get back the old behavior. Is there a chance you can share the file with me? I also hope this would be better on master where we're getting a more accurate row estimate (if you want to try, just do `] add CSV#master`).

**Comment by daschw** [comment]
> Is there a chance you can share the file with me?

I generated this file randomly above.
`threaded = false` works for me now, but I seem to remember that yesterday with a huge file it did not work either. I will check this again soon. I don't have access to that computer right now.
My code above works without `threaded = false` on CSV#master.

**Comment by daschw** [comment]
The problem persists for the original file, which is about 5_000_000 x 20 and 1GB even with `threaded=false`.
It works on v0.6.2, it returns not enough rows on v0.7.1 and it errors on master.

**Comment by quinnj** [comment]
Can you share how you generated the file? Or share a compressed version of the original file (even if privately; my email is on my github profile)?

**Comment by daschw** [comment]
It's in my first post:
```julia
df = DataFrame(rand(10000, 5))
CSV.write(fn, df)
```
The original file does not belong to me. A friend is working on it. I will check if she can provide it.

**Comment by daschw** [comment]
OK, I just got the file and I can't reproduce on my system with a MWE. It works on all CSV versions with `threaded=false` and on master even without. Sorry for the noise! We probably have to check her setup or code.

**Comment by quinnj** [comment]
Ok great, glad it's working. I'm going to try and get a new patch release out in the next day or two w/ a few other fixes.
