### ISSUE TITLE
NamedTuple method for CSV.File

### ISSUE THREAD

**Issue by bramtayl** [JuliaData/CSV.jl#689]
might be nice. This seems to work:

```
(; getfield(file, :lookup)...)
```

I could make a PR if you want

**Comment by quinnj** [comment]
Sure; we have `Tables.columntable`, but it isn't super obvious as the way to get a NamedTuple.

**Comment by bramtayl** [comment]
Could `Tables.columntable` just be `NamedTuple`?

**Comment by quinnj** [comment]
I actually like that `Tables.columntable` is fairly explicit, but I don't mind adding the alias in CSV

**Comment by bramtayl** [comment]
Ok, I can see that. I'll just use `Tables.columntable` instead.
