### ISSUE TITLE
CSV.File misses column - works fine in RStudio

### ISSUE THREAD

**Issue by outlace** [JuliaData/CSV.jl#694]
I'm trying to open a data set from the book/package Statistical Rethinking, reproduced below:

```csv
"dept";"applicant.gender";"admit";"reject";"applications"
"1";"A";"male";512;313;825
"2";"A";"female";89;19;108
"3";"B";"male";353;207;560
"4";"B";"female";17;8;25
"5";"C";"male";120;205;325
"6";"C";"female";202;391;593
"7";"D";"male";138;279;417
"8";"D";"female";131;244;375
"9";"E";"male";53;138;191
"10";"E";"female";94;299;393
"11";"F";"male";22;351;373
"12";"F";"female";24;317;341
```

`CSV.File("UCBadmit.csv") |> DataFrame!`
Gives me the following errors:
```julia
thread = 1 warning: parsed expected 5 columns, but didn't reach end of line around data row: 2. Ignoring any extra columns on this row
thread = 1 warning: parsed expected 5 columns, but didn't reach end of line around data row: 2. Ignoring any extra columns on this row
...
```

It loads the data but missing the last column. RStudio is able to import and parse this file properly with default settings. I've tried playing around with various keyword parameters without success.

**Comment by outlace** [comment]
Actually I see the data is in a weird format with an index column. I suppose it is more surprising that RStudio magically parses this than this being a deficit of CSV.jl

**Comment by quinnj** [comment]
Yeah, you could do `CSV.File(file; header=["index", "dept", "applicant.gender", "admit", "reject", "applications"], datarow=2)` and it should read all the columns.

I've been mulling over the possibility of trying to read these additional columns we encounter while parsing that weren't present when we parsed the header; it gets a little messy, but might be worth doing.
