### ISSUE TITLE
Long Loading Times using CSV.read

### ISSUE THREAD

**Issue by clibassi** [JuliaData/CSV.jl#699]
The problem here may just be me being stupid, but I've reproduced this now on two of my machines, each running a different version of Julia. My understanding is that loading in CSVs even with rows in the millions should be pretty zippy, but for me it takes several minutes. For the examples below, I'm using this historical stock price dataset: https://www.kaggle.com/ehallmar/daily-historical-stock-prices-1970-2018 which has ~21 million observations, but I've also found it with my own datasets more in the 14 million obs x 30 rows range. One note is that the drives I am pulling these files from is on a network drive at work. The first example is from a remote computer directly connected to the network at the office, the other from my machine connecting to the network from my house, which I often see causes differences in the speed of importing data files in Julia or Stata, but the files I'm working with contain data that has to stay on network drives, so any tips on what to do if that's the whole problem would be greatly appreciated: 

![image](https://user-images.githubusercontent.com/10570262/88707816-c71c6500-d0e0-11ea-986a-bf4428ef7e47.png)

And on the other machine: 

![image](https://user-images.githubusercontent.com/10570262/88745173-580e3300-d117-11ea-81a7-3c22d79caf2b.png)

**Comment by clibassi** [comment]
Just to follow up on this - here's the time of the file being read off of my local machine - so pulling from a network drive seems to the problem, but is there anything to be done about this? 

![image](https://user-images.githubusercontent.com/10570262/88746974-cead2f80-d11b-11ea-8948-1d9c763b4583.png)

**Comment by nalimilan** [comment]
How long does it take to copy the file from the network directory to your local machine? If that's much less than 400 seconds then there's indeed a problem. Maybe Windows isn't able to efficient mmap remote files?

**Comment by clibassi** [comment]
Just moved it and it took about 20 minutes. So you're saying that's a machine problem, not a CSV.read problem, right?

**Comment by nalimilan** [comment]
Well yeah, if you need 20 minutes just to copy it CSV can't do better than that.

**Comment by quinnj** [comment]
Feel free to comment more if there are additional questions, but it doesn't seem like there's anything actionable for CSV.jl here.
