### ISSUE TITLE
`DataFrame(CSV.File(...))` broken with header-only 

### ISSUE THREAD

**Issue by omus** [JuliaData/CSV.jl#702]
Starting with CSV.jl 0.7.5 parsing a file only containing a header will be treated like the file is empty.
```julia
julia> using CSV, DataFrames

julia> names(DataFrame(CSV.File(IOBuffer("a,b,c"))))
0-element Array{String,1}

julia> names(DataFrame(CSV.File(IOBuffer("a,b,c\n1,2,3"))))
3-element Array{String,1}:
 "a"
 "b"
 "c"
```
Calling `CSV.read` works as expected.

**Comment by quinnj** [comment]
Alternative fix proposed at https://github.com/JuliaData/DataFrames.jl/pull/2341
