### ISSUE TITLE
Regression in v0.7.5 when loading a CSV with only column names

### ISSUE THREAD

**Issue by Octogonapus** [JuliaData/CSV.jl#711]
I have noticed a regression introduced in `v0.7.5` when loading a CSV containing only column names.

Given a file `foo.csv` (containing only column names):
```
a, b
```

In CSV `v0.7.4`,
```julia
julia> import CSV
julia> using DataFrames
julia> DataFrame(CSV.File("foo.csv"))
0×2 DataFrame
```

In CSV `v0.7.5`,
```julia
julia> import CSV
julia> using DataFrames
julia> DataFrame(CSV.File("foo.csv"))
0×0 DataFrame
```

I am using Julia version 1.4.2. I get the same result with various versions of DataFrames `v0.21.x`.
CC @ianshmean

**Comment by quinnj** [comment]
This was fixed by https://github.com/JuliaData/DataFrames.jl/pull/2341; I think @bkamins is planning a new DataFrames release w/ the fix soon
