### ISSUE TITLE
Incorrect parsing of floats in corner cases 

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#714]
Here is an example:
```
julia> CSV.read(IOBuffer("x\n-1670."), DataFrame)
1×1 DataFrame
│ Row │ x          │
│     │ Float64    │
├─────┼────────────┤
│ 1   │ 1.84467e19 │
```

**Comment by nathanrboyer** [comment]
Here are examples of other numbers with the same issue.

Original CSV File: MiddlePrincipalStresses
FIltered CSV FIle: ElementsReadWrong

[ElementsReadWrong.txt](https://github.com/JuliaData/CSV.jl/files/5045413/ElementsReadWrong.txt)
[MiddlePrincipalStress.txt](https://github.com/JuliaData/CSV.jl/files/5045414/MiddlePrincipalStress.txt)

**Comment by bkamins** [comment]
I have not checked in detail, but it seems that it gets wrong if the number is negative and has a trailing `.` - is this correct?

**Comment by quinnj** [comment]
I think I have a fix for this; writing tests now

**Comment by nathanrboyer** [comment]
Seems to be only negative numbers with a trailing `.` that are affected.

**Comment by quinnj** [comment]
Yes, I believe those are the only cases affected

**Comment by quinnj** [comment]
Fix up: https://github.com/JuliaData/Parsers.jl/pull/61

**Comment by nathanrboyer** [comment]
My numerical data are now being read as Strings.

**Comment by quinnj** [comment]
I see that as well; investigating.

**Comment by quinnj** [comment]
Sorry about the hassle; the previous fix ended up only working for negative + trailing decimal; I have https://github.com/JuliaData/Parsers.jl/pull/64 which also fixes the non-negative case.
