### ISSUE TITLE
CSV.File broken with timestamps in 0.7.7

### ISSUE THREAD

**Issue by doorisajar** [JuliaData/CSV.jl#729]
A small reprex:

```
using CSV
using DataFrames
using Dates

df = DataFrame(
    timestamp = timestamp = ["2020-04-01T00:00:00Z", "2020-04-01T01:00:00Z"],
    value = [0.1, 0.2]
)

CSV.write("test.csv", df)

# works with 0.7.6 and 0.7.7
CSV.read(
    "test.csv",
    DataFrame,
    dateformat = "yyyy-mm-ddTHH:MM:SSZ"
)

# works with 0.7.6 but fails with 0.7.7
DataFrame!(
    CSV.File(
        "test.csv", 
        dateformat = "yyyy-mm-ddTHH:MM:SSZ",
        types = vcat(DateTime, Float64)
    )
)
```
The 0.7.7 failure throws this in `tryparsenext_tz` from `TimeZones`:
```ERROR: TypeError: in typeassert, expected Tuple{Char,Int64}, got a value of type Tuple{UInt8,Int64}```

Perhaps some type coercion internal to `CSV` in the `CSV.File` code path changed from 0.7.6 to 0.7.7?

**Comment by doorisajar** [comment]
I can also make it fail with 0.7.7 just by passing `types` to `CSV.read`:

```
CSV.read(
    "test.csv",
    DataFrame,
    dateformat = "yyyy-mm-ddTHH:MM:SSZ",
    types = vcat(DateTime, Float64)
)
```

**Comment by doorisajar** [comment]
It works with 0.7.7 if I remove the trailing `Z`s, but that shouldn't be necessary (and in my real application, I do have them).

```
df = DataFrame(
    timestamp = ["2020-04-01T00:00:00", "2020-04-01T01:00:00"],
    value = [0.1, 0.2]
)

CSV.write("test.csv", df)

CSV.read(
    "test.csv",
    DataFrame,
    dateformat = "yyyy-mm-ddTHH:MM:SS",
    types = vcat(DateTime, Float64)
)
```

**Comment by kenahoo** [comment]
Where are the date formats documented?  Trying to figure out whether `Z` in `yyyy-mm-ddTHH:MM:SSZ` is a format specifier or a literal.

**Comment by ianfiske** [comment]
Looks like `Z` is a literal: https://docs.julialang.org/en/v1/stdlib/Dates/#Dates.format-Tuple{TimeType,AbstractString}

**Comment by quinnj** [comment]
Hmmm......I can't reproduce the error; note I'm on CSV 0.7.7 and Parsers 1.0.9. Can you check your version of Parsers.jl? (that's where your error is coming from).

**Comment by doorisajar** [comment]
Looks like I have a newer version: `[69de0a69] Parsers v1.0.10`

**Comment by ianfiske** [comment]
The original error above is thrown from the TimeZones package.  How does Parsers.jl call `tryparsenext_tz` from TimeZones?

**Comment by quinnj** [comment]
Ah, I see the error now; note that you have to do `using TimeZones` in order to trigger the issue, so the comment:

> Unless somehow the inclusion of a zone string specifier automatically triggers parsing by the TimeZones package?

is indeed accurate; loading TimeZones.jl switches the parsing of `Z` from a literal to a timezone parser. Let me dig in and see if we can fix this in Parsers.jl or TimeZones.jl.

cc: @omus. The core issue here is that Parsers.jl operates on `Vector{UInt8}`, parsing byte-by-byte, whereas the Dates stdlib operates on strings.

**Comment by quinnj** [comment]
Ah, so the interesting thing here that I just realized is that your data doesn't actually have a timezone, just the character `Z`, so you _do_ want just the literal. So to solve the original problem, you can either parse the file _before_ calling `using TimeZones`, or you can escape your dateformat string like:
```julia
julia> f = CSV.File(
               "test.csv",
               dateformat = "yyyy-mm-ddTHH:MM:SS\\Z",
               types = vcat(DateTime, Float64)
           )
2-element CSV.File{false}:
 CSV.Row: (timestamp = DateTime("2020-04-01T00:00:00"), value = 0.1)
 CSV.Row: (timestamp = DateTime("2020-04-01T01:00:00"), value = 0.2)
```
to ensure the `Z` is treated as a literal.

That doesn't mean we should support parsing `ZonedDateTime`, which I'm digging into locally, but this at least solves your immediate problem.

**Comment by doorisajar** [comment]
I was running that reprex I posted in a fresh Julia session each time, and I haven't done `using TimeZones` directly at any point, but it's possible something else I loaded had an equivalent effect. The workaround does solve my problem for now, though, thanks!

**Comment by kenahoo** [comment]
In general a `Z` in a datetime should be considered as the offset, equivalent to `+0000`.  Using a literal `Z` in the format string would mean "die if the offset isn't a literal Z", whereas a timezone-format `Z` would mean "honor the offset in the data".  I would nearly always want the latter.

**Comment by kenahoo** [comment]
@ianfiske see https://timezonesjl.readthedocs.io/en/stable/conversions/#parsing-strings , where `z` and `Z` are added.

https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC) indicates that `Z` is the indicator for UTC.

**Comment by quinnj** [comment]
I don't think there's anything actionable here for CSV.jl; please comment if you feel otherwise.
