### ISSUE TITLE
How to have CSV.read() return a datatable instead of a dataframe?

### ISSUE THREAD

**Issue by holder66** [JuliaData/CSV.jl#73]
Am I missing something in the documentation? Do I need to specify a DataStreams sink? Does the snippet below suggest I am doing something wrong? 

`julia> using DataTables

julia> using CSV
WARNING: Method definition describe(AbstractArray) in module DataTables at /Users/henryolders/.julia/v0.5/DataTables/src/abstractdatatable/abstractdatatable.jl:381 overwritten in module DataFrames at /Users/henryolders/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:407.
WARNING: Method definition describe(Any, AbstractArray{#T<:Number, N<:Any}) in module DataTables at /Users/henryolders/.julia/v0.5/DataTables/src/abstractdatatable/abstractdatatable.jl:383 overwritten in module DataFrames at /Users/henryolders/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:409.
WARNING: Method definition describe(Any, AbstractArray{#T<:Any, N<:Any}) in module DataTables at /Users/henryolders/.julia/v0.5/DataTables/src/abstractdatatable/abstractdatatable.jl:400 overwritten in module DataFrames at /Users/henryolders/.julia/v0.5/DataFrames/src/abstractdataframe/abstractdataframe.jl:426.

julia> irist = CSV.read(joinpath(Pkg.dir("DataTables"), "test/data/iris.csv"))
150×5 DataFrames.DataFrame
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species     │
├─────┼─────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ 1   │ "5.1"       │ "3.5"      │ "1.4"       │ "0.2"      │ "setosa"    │
│ 2   │ "4.9"       │ "3.0"      │ "1.4"       │ "0.2"      │ "setosa"    │`

**Comment by quinnj** [comment]
This is being actively worked on. We're trying to ensure that the existing related packages all have a working 0.6 tag first and then full compatibility will be added for DataTables.jl

**Comment by holder66** [comment]
Thank you for the update!

**Comment by cjprybol** [comment]
Thanks for your patience on this @holder66! The changes haven't shown up in the online documentation yet (not sure how often those rebuild), but if you check out the latest master of DataTables `Pkg.update(); Pkg.checkout("DataTables")` you should be able to get CSV to return a DataTable by following the instructions [here](https://github.com/JuliaData/DataTables.jl/blob/master/docs/src/man/getting_started.md#importing-and-exporting-data-io). Let us know if you have any issues!

**Comment by quinnj** [comment]
DataTables has now been ported over to DataFrames and will no longer be developed.
