### ISSUE TITLE
CSV.read crashes with large file

### ISSUE THREAD

**Issue by caseykneale** [JuliaData/CSV.jl#749]
I am working on cutting a release for a package that allows some domain-specific data to be accessed easily for testing new methods, teaching, etc. I'm having trouble with one file, go figure it's the largest. I was able to load the file into Julia via CSV.jl in a previous version. It may have a parse error in one of the columns somewhere, but, it fails silently. So even if the file is not ideal, it would be nice to throw an error before killing the julia instance.

**Comment by quinnj** [comment]
Is there a way you can share a sample of the file? Even if just privately with me? I'd love to take a look somehow

**Comment by caseykneale** [comment]
Yes of course. I can share the whole file, but it's relatively large:
if you click this link, it'll take you to a line of code containing some JSON where the file can be downloaded from
https://github.com/caseykneale/ChemometricsData.jl/blob/dee77ad30ae424c09e47638efeb599b0e0b30280/src/manifest.jl#L202

**Comment by quinnj** [comment]
I don't see crashing; I see:
```julia
julia> @time f = CSV.File(file);
ERROR: 2; something went wrong trying to determine row positions for multithreading; often it's a mismatch in the # of columns expected in the file (in this case, 2239 columns were expected, probably from the `header` keyword argument, which tries to auto-detect from the 1st row of the file) vs. actual; pass `threaded=false` to avoid using multithreaded parsing; if you think you're seeing this error incorrectly, it'd be very helpful if you could open an issue at https://github.com/JuliaData/CSV.jl/issues so package authors can investigate
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] findrowstarts!(buf::Vector{UInt8}, len::Int64, options::Parsers.Options{false, true, true, false, Missing, UInt8, Nothing}, ranges::Vector{Int64}, ncols::Int64, types::Vector{Type}, flags::Vector{UInt8}, lines_to_check::Int64)
```

Are you passing any other keyword arguments to the reading function?

**Comment by caseykneale** [comment]
Sorry, yes, also passing "threaded = false". 
This will remove the error but terminate the julia instance, at least on my machine.

**Comment by quinnj** [comment]
Hmmm, not seeing a crash there either:
```julia
julia> @time f = CSV.File(file; threaded=false, silencewarnings=true);
 30.982004 seconds (124.93 k allocations: 20.616 GiB, 16.70% gc time, 0.05% compilation time)
```
I see a warning about missing 2 columns on each row; so it seems like there are 2 extra columns detected in the header row than actually exist in the data itself.

**Comment by quinnj** [comment]
@caseykneale, can you share the full crash stacktrace you're seeing?

**Comment by caseykneale** [comment]
Interesting. Well, I'll see what I can do. Maybe if I run it in the REPL I'll get a stack trace. So far, I've only had it kill my terminal in VSCode. Wondering if there's something else going on at this point.

**Comment by quinnj** [comment]
I've just put up https://github.com/JuliaData/CSV.jl/pull/754, which will stop printing so many warnings automatically when parsing large files with lots of warnings (like the file in this issue). I'd be interested to hear if it perhaps avoids the crash you were originally seeing.

**Comment by quinnj** [comment]
Closing for now, but feel free to reopen if you manage to reproduce
