### ISSUE TITLE
DataFrames.jl 0.22 releaes

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#771]
@quinnj - we are going to release 0.22 version of DataFrames.jl this week. Probably it would be good to release CSV.jl then also (I understand it would drop dependency on DataFrames.jl - right?)

**Comment by quinnj** [comment]
0.8 release is out

**Comment by bkamins** [comment]
Thank you!

**Comment by quinnj** [comment]
I guess we could consider bumping the DataFrames compat on the 0.7 release branch if someone wanted to do a quick PR

**Comment by bkamins** [comment]
see https://github.com/JuliaData/CSV.jl/pull/779
