### ISSUE TITLE
UInt64 column type is parsed incorrectly as strings

### ISSUE THREAD

**Issue by deltadecay** [JuliaData/CSV.jl#785]
Using CSV.jl v0.8.0 in julia 1.5.2
If I try to specify UInt64 as a column type, and load integer data from a csv-file, the resulting data has type String.
Below a minimum example:

```julia
using CSV
csv = """1,1,1,1,1,1
2,2,2,2,2,2
3,3,3,3,3,3"""
csvfile = CSV.File(IOBuffer(csv); header=0, types=[UInt64,Int64,UInt128,Int128,UInt32,Int32])
```
Only the first column has a type String and not the expected UInt64. The other columns are correctly parsed into their corresponding types.
```julia
typeof(csvfile[1].Column1) == UInt64
````
returns false.

**Comment by quinnj** [comment]
Thanks for the report! Definitely a bug. Took a little to figure out exactly what was going on, but I managed to track it down to an unintentional overload in the string parsing code. Fix is up: https://github.com/JuliaData/CSV.jl/pull/786.

**Comment by deltadecay** [comment]
Being new to Julia, I'm a bit uncertain to the workflow now. In a julia session I created a new environment and added your version and tested and I can verify it works. Not sure what is the best practice way to do this though. Anyway, thanks for a very quick response and a fix! 
What is the steps for this to be merged to master? and do I need to do anything? Asking questions as I don't have a clue.

**Comment by quinnj** [comment]
Some of the tests fail on my PR, so the fox isn't perfect yet. I have an idea of how to do a better fix, hopefully can get it done later tonight.

**Comment by quinnj** [comment]
No worries; I've merged the (new) fix (https://github.com/JuliaData/CSV.jl/pull/787), and tagged a new release here: https://github.com/JuliaData/CSV.jl/commit/c94256adbe6c2ae017be90ae91976f3b5bb74aa4. That means once the new release is accepted in the General registry, you can just do `] up CSV` in your local repl to get the fix included.
