### ISSUE TITLE
CSV reading memory usage

### ISSUE THREAD

**Issue by ohadle** [JuliaData/CSV.jl#794]
I need to read a CSV in a memory-constrained environment, and checked out CSV.jl. Following the snippet in [this discourse post](https://discourse.julialang.org/t/csv-reader-benchmarks-julia-reads-csvs-10-20x-faster-than-python-and-r/41974/14), I tried:
```julia
using CSV, DataFrames, PyCall, BenchmarkTools
pd = pyimport("pandas")
download("https://nyc-tlc.s3.amazonaws.com/trip+data/green_tripdata_2019-12.csv", 
    "test_data.csv")
@time df = CSV.File("test_data.csv") |> DataFrame # including compilation
@btime df = CSV.File("test_data.csv") |> DataFrame;
@btime pydf = pd.read_csv("test_data.csv");
```
CSV.File gives me 194 MiB allocations, while the pandas version gets 304 bytes.
What am I missing?

**Comment by nalimilan** [comment]
Pandas.jl probably doesn't report the actual memory used as it's allocated in Python's side (304 bytes is really small). Also allocations do not reflect the memory used at a single time point; what's more interesting is the memory use of the process.

**Comment by quinnj** [comment]
Yeah, it doesn't seem you're measuring quite the right things here. I've noticed myself recently that `CSV.File` can be a bit wasteful/excessive in terms of memory and I've added an action item to look into it more, but probably not for the next couple of months.

**Comment by ohadle** [comment]
Thanks!
Memory usage was a bit small to easily see in the process, so hopefully this is a more reflective measurement (in python):
```python
import pandas
%load_ext memory_profiler
%memit print('a') #peak memory: 79.37 MiB
%memit df = pandas.read_csv('test_data.csv')
peak memory: 277.70 MiB, increment: 198.23 MiB
```
(Although the `increment` keeps decreasing on subsequent runs, which I don't really understand).
I could also try measuring the process memory externally if that's helpful.

I'm happy to close this, unless you want to keep it around if you think there's room for improvement.

**Comment by quinnj** [comment]
Going to close this for now; but just a note that I'm planning on doing a round of performance/memory improvements in the near future.
