### ISSUE TITLE
read() slower than classical readdlm()

### ISSUE THREAD

**Issue by krishna-vasudev** [JuliaData/CSV.jl#795]
I am using julia 1.5.3.When i was running both read() and readdlm() for same dataset ,read was slower.But in earlier versions it was two times faster.I could not find any related issues,so i am opening this issue.The code reference is:
```
@btime P,H = readdlm("programminglanguages.csv",',';header=true);
@btime C = CSV.read("programminglanguages.csv",DataFrame);
  172.499 μs (322 allocations: 51.20 KiB)
  193.700 μs (227 allocations: 22.08 KiB)
```
So please guide me.

**Comment by nalimilan** [comment]
Could you provide a file that allows reproducing the problem?

**Comment by krishna-vasudev** [comment]
@nalimilan ,I am sharing link of the file ,which is giving me the above action.
https://github.com/krishna-vasudev/gitdemo/blob/master/programminglanguages.csv
Please have a look.

**Comment by quinnj** [comment]
I don't see any slowdown:
```julia
julia> @btime P,H = readdlm("programminglanguages.csv",',';header=true);
  108.174 μs (325 allocations: 51.17 KiB)

julia> @btime C = CSV.read("programminglanguages.csv",DataFrame);
  78.725 μs (223 allocations: 21.89 KiB)
```
Additionally, we're talking 74 rows, 2 columns, so the performance difference really shouldn't be expected to be dramatic in any case. What I mean is the amount of data is so small that you're really getting into benchmarking things like system IO more than actual parsing, which may vary from system to system. In short, I wouldn't worry too much about parsing performance on datasets these small. If you notice concerning numbers on larger datasets, then there's probably some work we can do.
