### ISSUE TITLE
CSV.write  UndefRefError: access to undefined reference

### ISSUE THREAD

**Issue by smitch151** [JuliaData/CSV.jl#798]
Whenever I try to save a file to .csv using CSV.write, I get the following error: "UndefRefError: access to undefined reference." A blank csv file is saved the location, but it is not filled in with the specified data. 

For example

```
using CSV, DataFrames

input = work * "input" 
code = work * "code"
output = work * "output"
temp = work * "temp"
raw = input * "/raw"

filename = input * "/retrosheet/GL2020.txt"
data = CSV.read(filename, header=false)

### export to csv
filename = output * "/retrosheet_clean.csv"
CSV.write(filename, data)

```

**Comment by quinnj** [comment]
Hmmmm.....I can't reproduce the issue on my side. This sounds very odd, like something is getting redefined, or you're on a really old version or something. Can you report what OS, Julia version, CSV.jl version you're using? (`versioninfo()` gives the first 2, `] st` gives the 3rd). Can you also show the full error stacktrace you're seeing? That might give a better insight into where the actual error is being thrown.

**Comment by smitch151** [comment]
I just needed to update my version of julia and now it works. Thanks for looking into this.
