### ISSUE TITLE
Specify column types from dictionary

### ISSUE THREAD

**Issue by briskequip** [JuliaData/CSV.jl#802]
When using CSV.File to import a txt file, I can't seem to specify column types from a dictionary.
I have the following txt file:
```Julia
Date, Time, Colour
2019/7/21, 14:40:15, red
2019/7/22, 14:40:15.001, yellow
2019/7/23, 14:40:15.002, green
```

When using the following Julia code, column types are atomically applied, as opposed to taking them from the dictionary:
```Julia
using CSV, DataFrames

filetypes = Dict(
    :Date => String,
    :Time => String,
    :Colour => String,
    );

df = DataFrame(CSV.File("file.txt"; header=1, delim=',', types=filetypes))
```

**Comment by bluesmoon** [comment]
I see the same. With a Dict:
```julia
julia> df = DataFrame(CSV.File("/data/testdb/test-802.csv"; header=1, delim=',', types=filetypes))
3×3 DataFrame
 Row │ Date        Time          Colour 
     │ String     Time          String  
─────┼──────────────────────────────────
   1 │ 2019/7/21  14:40:15       red
   2 │ 2019/7/22  14:40:15.001   yellow
   3 │ 2019/7/23  14:40:15.002   green
```

With an array:
```julia
julia> filetypes=[String, String, String]
3-element Array{DataType,1}:
 String
 String
 String

julia> df = DataFrame(CSV.File("/data/testdb/test-802.csv"; header=1, delim=',', types=filetypes))
3×3 DataFrame
 Row │ Date        Time           Colour 
     │ String     String         String  
─────┼───────────────────────────────────
   1 │ 2019/7/21   14:40:15       red
   2 │ 2019/7/22   14:40:15.001   yellow
   3 │ 2019/7/23   14:40:15.002   green
```

**Comment by quinnj** [comment]
The issue here, which is subtle, is that the column names parsed in the file (as directed by `header=1`), are `[:Date, Symbol(" Time"), Symbol(" Colour")]`, take note of the extra space before the `Time` and `Colour` columns. Hence when the types are inspected in the `filetypes` Dict, it doesn't find a match (since the column names in the Dict are _without_ the space). If you fix the file to remove extra spaces from the column names, or _include_ the space in the Dict column names, it all works as expected.

A few thoughts on how we could make things better here:
* We could maybe have a `trim_column_names=true` keyword arg on by default to trim whitespace on column names
* We could warn on column names provided to `types`, `select`, `drop`, etc. that aren't found in the file and issue a warning so it's clear something is wrong

**Comment by quinnj** [comment]
So I remembered that we do have `normalizenames=true`, which can be used to strip leading/trailing whitespace from column names.

@bkamins, @nalimilan, what do you think about warning on column names provided in `types`, `select`, `drop`, (and soon `pool`) that we don't find in the dataset? On the one hand, I think it'd mostly be helpful; on the other, people might have programmatic cases where they provide many names from a large pool or something and emitting a warning would be annoying.

**Comment by bkamins** [comment]
> warning on column names provided in

Maybe another kwarg, something like `strict::Union{Nothing, Bool}=nothing` would be good to have. By default a warning would be emitted, but for production `strict=true` or `strict=false` could be chosen depending on the use-case.

**Comment by nalimilan** [comment]
I general I tend to prefer throwing errors rather than warnings, with an argument to disable errors like @bkamins suggested.

**Comment by bkamins** [comment]
Yes - this is what we do in DataFrames.jl, but I understood that @quinnj prefers to print a warning as a default.

To be clear - in a similar situation in DataFrames.jl we would throw an error by default and allow to disable throwing error. We never generate any warnings in DataFrames.jl.

**Comment by bkamins** [comment]
The decision is if in the case when you emit a warning now it should be changed to an error indicating that user should add `strict=false` kwarg. As said - this is what we would do in DataFrames.jl. But if you strongly prefer to have three options:
1. warning by default
2. error or accept when `strict` kwarg is passed

This is not super bad, so if you prefer it I think we can go ahead with this. In DataFrames.jl we prefer to never throw warnings as we believed with @nalimilan that warning would be very often ignored/not seen and lead to bugs.

**Comment by quinnj** [comment]
Ok, PR up to do extra validation on keyword arguments passed as dicts: https://github.com/JuliaData/CSV.jl/pull/870
