### ISSUE TITLE
Error message when reading CSV file

### ISSUE THREAD

**Issue by ksawhney** [JuliaData/CSV.jl#803]
I'm getting the following error message when trying to read in a CSV file. The file is fairly large, about 200MB. I'm running Julia 1.5.3 on a Windows machine.

With the code:
`using CSV, DataFrames, Dates;
CSV.read("myfile.csv", DataFrame, dateformat = "yyyy-mm-dd")`

I get this error message:
`Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_IN_PAGE_ERROR at 0x3ccfdfa5 -- getindex at .\array.jl:809 [inlined]
peekbyte at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\utils.jl:220 [inlined]
parsedigits at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\floats.jl:201 [inlined]
typeparser at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\floats.jl:171 [inlined]
xparse at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\Parsers.jl:254 [inlined]
parsevalue! at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:907
in expression starting at In[7]:1
getindex at .\array.jl:809 [inlined]
peekbyte at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\utils.jl:220 [inlined]
parsedigits at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\floats.jl:201 [inlined]
typeparser at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\floats.jl:171 [inlined]
xparse at C:\Users\ksawhney\.julia\packages\Parsers\2MBHI\src\Parsers.jl:254 [inlined]
parsevalue! at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:907
unknown function (ip: 000000003cd04702)
parserow at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:653
unknown function (ip: 000000003ccd3ca1)
parsefilechunk! at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:541
unknown function (ip: 000000003cccdff2)
#File#23 at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:303
Type##kw at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:233
unknown function (ip: 000000003ccccfc1)
#File#22 at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:218
Type##kw at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\file.jl:217
#read#77 at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\CSV.jl:45
read##kw at C:\Users\ksawhney\.julia\packages\CSV\la2cd\src\CSV.jl:42
unknown function (ip: 000000003ccbe8e8)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:790
jl_parse_eval_all at /cygdrive/c/buildbot/worker/package_win64/build/src\ast.c:913
include_string at .\loading.jl:1091
softscope_include_string at C:\Users\ksawhney\.julia\packages\SoftGlobalScope\u4UzH\src\SoftGlobalScope.jl:65
execute_request at C:\Users\ksawhney\.julia\packages\IJulia\IDNmS\src\execute_request.jl:67
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
eventloop at C:\Users\ksawhney\.julia\packages\IJulia\IDNmS\src\eventloop.jl:8
#15 at .\task.jl:356
unknown function (ip: 000000002d2dc983)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:705
Allocations: 308623074 (Pool: 308564555; Big: 58519); GC: 145`

**Comment by quinnj** [comment]
Hmmmmm, a page error seems like something off w/ the m-mapping. Is there any way you could share a compressed version ofthe file w/ me, even if just privately? I've used http://ge.tt/ before which is nice as an auto-expiring file sharing link.

**Comment by ksawhney** [comment]
Thanks, I dug into the file some more and the underlying data had been corrupted somehow -- I couldn't even open the CSV in Excel or any other program. I re-created the file and the bug is no longer appearing, so I think I can close this issue.

**Comment by quinnj** [comment]
Oh, well I guess that's good then (the resolution, not the file corruption 😅)
