### ISSUE TITLE
problem of CSV.read in Jupyter notebook

### ISSUE THREAD

**Issue by hurricane007** [JuliaData/CSV.jl#806]
Hello, I am not sure if this is an issue related to CSV.jl or Jupyter notebook. 
I got a csv file that was correctly read in REPL, or in jupyter notebook with the DelimitedFiles package, but when using CSV to read the same file in jupyter notebook, the kernel becomes busy and there is no output although jupyter notebook seems finished the work. 
![image](https://user-images.githubusercontent.com/16286632/106869688-84ab9480-66d0-11eb-99bb-0e242515894c.png)
![image](https://user-images.githubusercontent.com/16286632/106869033-bd973980-66cf-11eb-943c-78c7b4a15b38.png)
![image](https://user-images.githubusercontent.com/16286632/106869422-34cccd80-66d0-11eb-8df4-68f8a30a8f12.png)

**Comment by nalimilan** [comment]
Maybe it's related to printing DataFrames rather than to CSV.jl? You could try adding a `;` at the end of the line to avoid printing it immediately.

**Comment by quinnj** [comment]
My guess is this was related to #817, which should now be fixed on current `main` branch. Please comment if this is still reproducible on current `main` branch.

**Comment by hurricane007** [comment]
> My guess is this was related to #817, which should now be fixed on current `main` branch. Please comment if this is still reproducible on current `main` branch.

I finally solved this problem by deleting the first element of the first line .... I guess that symbol made this problem.
