### ISSUE TITLE
TypeError: in new, expected CSV.PooledString, got a value of type String

### ISSUE THREAD

**Issue by aplavin** [JuliaData/CSV.jl#808]
I'm trying to read a CSV like this:
```
import Tables
import CSV

CSV.read("Weekly_excess_deaths_data.csv", Tables.rowtable)
```
Typically it works, but for a specific CSV file results in an error: `TypeError: in new, expected CSV.PooledString, got a value of type String`.
The file in question: [direct link](https://public.tableau.com/vizql/w/COVID_excess_mort_withcauses_02032021/v/WeeklyExcessDeaths/vudcsv/sessions/1A3C088DF49145DAA108DA31F3BE5BD7-0:0/views/14584835611662281462_10210739281033925186?summary=true); if link doesn't work then [go here](https://public.tableau.com/views/COVID_excess_mort_withcauses_02032021/WeeklyExcessDeaths?:embed=y&:jsdebug=y&:toolbar=n&:tabs=n&:display_count=n&:origin=viz_share_link) and click Download -> Data -> All rows as a text file.

I didn't see any obvious issues with the file. The first lines look like this:
```
Observed Number,Upper Bound Threshold,Day of Week-ending Date,Average Expected Number of Deaths,Flag,Note,Observed Number,Percent Excess Over Expected,Percent Excess Over Upper Bound,State,Total Number of Excess Deaths Over Upper Bound,Upper Bound Threshold
"60,064",,"January 23, 2021","60,909",,"Data in recent weeks are incomplete. Only 60% of death records are submitted to NCHS within 10 days of the date of death, and completeness varies by jurisdiction.  ",,0.0,0.0,United States,"417,057","63,090"
"70,543",,"January 16, 2021","60,972",+,"Data in recent weeks are incomplete. Only 60% of death records are submitted to NCHS within 10 days of the date of death, and completeness varies by jurisdiction.  ",,15.7,11.7,United States,"417,057","63,129"
```

**Comment by quinnj** [comment]
Thanks for the report and sorry for the delay. I understand the problem and have proposed a fix here: https://github.com/JuliaData/CSV.jl/pull/811. There might be other cases (like CSV.Rows) where we need to do something similar, but I wanted to put up the PR and see if CI complains about any other issues first.

**Comment by aplavin** [comment]
Thanks, now it works indeed!
