### ISSUE TITLE
Issues with CSV.read in Atom

### ISSUE THREAD

**Issue by nkashaev** [JuliaData/CSV.jl#809]
Hi,

I'm trying to read a relatively small file (2 columns 4099 rows). 
When I run CSV.read("location", DataFrame) in using Terminal there are no issues. However, when I run the same line in Atom, then Julia freezes. I thought it may just take more time, but after waiting for 10 min there is still nothing. 
I also ran ] test CSV and I got bunch of warnings and 
Test Summary:               | Pass  Fail  Total
CSV                         | 1824     1   1825
  CSV.File                  | 1622         1622
  CSV.write                 |   92     1     93
  PooledArrays              |   14           14
  LazyStringVector          |    7            7
  CSV.Rows                  |   37           37
  CSV.detect                |    8            8
  CSV.findrowstarts!        |    4            4
  CSV.promote_typecode      |    2            2
  CSV.File with select/drop |   38           38
ERROR: LoadError: Some tests did not pass: 1824 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/nailkashaev/.julia/packages/CSV/YUbbG/test/runtests.jl:13
ERROR: Package CSV errored during testing

p.s. 
Atom 1.54.0
Julia Version 1.5.3
     CSV v0.8.3
     Atom v0.12.30
System Apple Mac mini M1

**Comment by nalimilan** [comment]
Maybe it's just printing that takes time? What happens if you prevent printing by adding `;` at the end of the line?

**Comment by nkashaev** [comment]
I tried. It did not work.

**Comment by nalimilan** [comment]
Too bad. Maybe report this to Juno developers.

**Comment by quinnj** [comment]
I know there's been quite a bit of active development on Julia master to fully support apple silicon (like the mac mini m1): https://github.com/JuliaLang/julia/pulls?q=is%3Apr+%22Darwin%2FARM64%22. There might be some weird interaction between Atom/Juno and the M1 that's causing weirdness. In any case, I agree this seems to be a Juno issue, so better to report it there (I personally dont' really know much about atom/juno setup or how it works/uses julia).
