### ISSUE TITLE
CSV.read fail require sink argument

### ISSUE THREAD

**Issue by lydiazsq** [JuliaData/CSV.jl#814]
I just migrated to a Macbook with M1 chip, but julia hasn't been working since then. I used my regular syntax of reading a csv file: 
`using CSV`
`using DataFrame`
`CSV.read(string(filepath,"ps3.csv"),DataFrame)`

but julia either froze or gave the following error: ERROR: ArgumentError: provide a valid sink argument, like `using DataFrames; CSV.read(source, DataFrame). The same argument would have worked fine with my old julia. What went wrong?

**Comment by quinnj** [comment]
Hmmm, that sounds pretty weird. Can you post the full versions of everything? Julia, CSV.jl, DataFrames.jl, etc. Can you post the full script you're call and the full backtrace of the error?

**Comment by lydiazsq** [comment]
This is what I'm getting after starting atom. The deprecation is possibly due to reinstalling julia (via JuliaPro), and the CSV.read now gives the little running sign without any error message. 

![Screen Shot 2021-03-13 at 7 37 56 AM](https://user-images.githubusercontent.com/45860677/111032373-72a8ca00-83d1-11eb-8b4e-16cf203ba297.png)

![Screen Shot 2021-03-13 at 7 53 22 AM](https://user-images.githubusercontent.com/45860677/111032375-78061480-83d1-11eb-8d57-2f5f1c320ae0.png)

**Comment by quinnj** [comment]
Yeah, I can't recommend using Atom/Juno at all; it bakes in its own version of packages into the sysimg that totally bypass the Julia versioning system and make things incompatible. I'd highly recommend switching to VSCode with the Julia plugin that provides a more-actively-maintained package of functionality comparible to Juno.
