### ISSUE TITLE
CSV.Rows with gzipped files running out of memory

### ISSUE THREAD

**Issue by jbrnd** [JuliaData/CSV.jl#815]
This looks to be the same problem mentioned in issue #476.

Unfortunately the fix from that issue did not solve the problem for me (Julia 1.5.3, CSV.jl either 0.8.4 or commit 5e9130b556224869af1abdc15e009ac1c40478be). Reading a large gzipped CSV file (around 15 GB compressed) uses very large amounts of memory - it got to 80 GB, at which point the Julia process ran out of memory. I'm using essentially the same code as reported in issue #476, to be precise

    using CSV
    using CodecZlib
    
    function readfunc()
        path = "largefile.csv.gz"
    
        open(GzipDecompressorStream, path, "r") do stream
            df = CSV.Rows(stream, header=false, datarow=2)
    
            idx = 1
            for row in df
                idx < 4 && println(row)
                idx += 1
            end
        end
    end

Large amounts of memory start being used up before any rows are printed, so I suspect it's the initial scan of the file that's causing the problem.

**Comment by jbrnd** [comment]
Passing `limit=1000` to CSV.Rows doesn't change anything - it still runs out of memory.

**Comment by quinnj** [comment]
Yes, unfortunately we don't do any buffering when reading for `CSV.Rows` as of right now. So the first thing that happens in your case is:
```julia
buf = read(open(GzipDecompressorStream, path, "r"))
```

**Comment by jbrnd** [comment]
I see - thank you! And at present, there's no way to prevent that read from happening? I suppose I could chunk the input stream myself, then feed it to CSV.jl in chunks.

**Comment by quinnj** [comment]
On current `main` branch, you can do `CSV.Rows("largefile.csv.gz", header=false, datarow=2)` and the file will be gunzipped to a temp file automatically, then parsing will stream, row-by-row, over the temp file data. Once the `CSV.Rows` object goes out of scope, the tempfile will be removed (or if the process is killed). There is an option to decompress the gzip input data in memory by passing `buffer_in_memory=true`, but that's obviously not recommended for large files where the system has limited RAM. But anyway, this should be much better handled on current `main` branch.
