### ISSUE TITLE
Could the CSV.write argument order be interchanged ?

### ISSUE THREAD

**Issue by Lincoln-Hannah** [JuliaData/CSV.jl#819]
For most DataFrame functions, the DataFrame is the first argument.
This is useful when working with  @chain  that fills in the first argument as the previous line's output.
If the CSV argument order were swapped. the final line below would be just   CSV.write( outputFile )
(The underscore could be omitted) 

```
@chain CSV.read(  inputFile  ) begin
    stack([:Curve,:Tenor] |> Not)
    @where( :value .!= 0 )
    insertcols!(_, ([:Curve2,:Tenor2] .=>  split.( _.variable, '/' ) |> invert )...)
    groupby( [:Curve,:Curve2] )
    combine( :value => sum => :sumval  )    
    CSV.write( outputFile, _ )    
    end
```

**Comment by quinnj** [comment]
This is already supported? i.e. we have the definition `CSV.write(file; kwargs...) = x->CSV.write(file, x; kwargs...)`

**Comment by Lincoln-Hannah** [comment]
Thanks for your response Jacob.  I'm still no clear though sorry.
I'd like to be able to write:
   
       CSV.write(  df_name,    file_name )

That is, put the DataFrame before the file name, so that it can be omitted within a @chain block.

Is this possible?   I couldn't ascertain that from your response.

**Comment by quinnj** [comment]
Yeah, I'm saying you can just do:
```julia
@chain CSV.read(  inputFile  ) begin
    stack([:Curve,:Tenor] |> Not)
    @where( :value .!= 0 )
    insertcols!(_, ([:Curve2,:Tenor2] .=>  split.( _.variable, '/' ) |> invert )...)
    groupby( [:Curve,:Curve2] )
    combine( :value => sum => :sumval  )    
    CSV.write( outputFile)    
    end
```

**Comment by Lincoln-Hannah** [comment]
Here is a simpler example:

```
@chain DataFrame(A=1:4) begin    
    CSV.write( fileName, _  )
end
```

Removing the ,_ gives the error:

```
ERROR: ArgumentError: 'String' iterates 'Char' values, which doesn't satisfy the Tables.jl `AbstractRow` interface
Stacktrace:

[1] invalidtable(#unused#::String, #unused#::Char)

@ Tables ~.julia\packages\Tables\UxLRG\src\tofromdatavalues.jl:42

[2] iterate

@ ~.julia\packages\Tables\UxLRG\src\tofromdatavalues.jl:48 [inlined]

[3] write(::Nothing, rows::Tables.IteratorWrapper{String}, file::DataFrame, opts::CSV.Options{UInt8, UInt8, Nothing, Tuple{}, CSV.var"#60#63"}; append::Bool, header::Bool, bufsize::Int64)

@ CSV ~.julia\packages\CSV\CJfFO\src\write.jl:231

[4] write(file::DataFrame, itr::String; delim::Char, quotechar::Char, openquotechar::Nothing, closequotechar::Nothing, escapechar::Char, newline::Char, decimal::Char, dateformat::Nothing, quotestrings::Bool, missingstring::String, transform::CSV.var"#60#63", bom::Bool, append::Bool, writeheader::Nothing, partition::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})

@ CSV ~.julia\packages\CSV\CJfFO\src\write.jl:191

[5] write(file::DataFrame, itr::String)

@ CSV ~.julia\packages\CSV\CJfFO\src\write.jl:152

[6] top-level scope

@ h:\Documents\Julia Code\Jacobian_Analysis.jl:36

Closes block expression.

```

**Comment by quinnj** [comment]
Ah, I see. Chain.jl is doing their own transformation to the `CSV.write` line that prevents the functor form from getting called. Alternatively, if you use regular piping syntax, this works `df |> CSV.write("data.csv")`. I don't think there's much we can do for this. It's not really that much worse/weird to do `CSV.write(file, _)` and things are already designed to work w/ piping syntax.
