### ISSUE TITLE
CSV.File: kwargs missingstrings/missingstring

### ISSUE THREAD

**Issue by George9000** [JuliaData/CSV.jl#821]
The `missingstrings` kwarg takes input of `Vector{String}` type as does `missingstring`. However, `missingstring` will fail with more than one value. The error message for this mistake is opaque. Details here:
[Interpreting error message / stacktrace for CSV.File](https://discourse.julialang.org/t/interpreting-error-message-stacktrace-for-csv-file/58539)

As suggested in the solution for that discussion: 

"two almost identical kwargs that take different input types might warrant an argument check with a specific error message"

**Comment by quinnj** [comment]
Pull requests are definitely welcome to improve argument checking/errors like this!

**Comment by quinnj** [comment]
Proposal to merge `missingstring` and `missingstrings` keyword args here: https://github.com/JuliaData/CSV.jl/pull/846

**Comment by George9000** [comment]
Thank you. This merging makes sense and will help others avoid falling into the same pit wherein I became enmeshed.
