### ISSUE TITLE
Formatting of bulleted items in docstrings

### ISSUE THREAD

**Issue by cormullion** [JuliaData/CSV.jl#825]
As I was looking for helpful information, I typed 

```
help?> CSV.File
```

<img width="1060" alt="Screenshot 2021-04-14 at 08 38 57" src="https://user-images.githubusercontent.com/52289/114672373-f9b4cf00-9cfc-11eb-9ab2-c3b2e1f6cc84.png">

I think this could be improved with some newlines in the [docstring](https://github.com/JuliaData/CSV.jl/blob/9ab93e038162c577288edeb21f0d9d03f006f26b/src/file.jl#L141)  - easy to fix, but just checking that it's not autogenerated from somewhere else or formatted specially for Documenter...

**Comment by quinnj** [comment]
Gross! A PR would definitely be welcome to fix that!

**Comment by cormullion** [comment]
It's a  bit better. I get confused with Markdown "standards"!

<img width="1012" alt="Screenshot 2021-04-14 at 17 44 08" src="https://user-images.githubusercontent.com/52289/114747789-21ca1f80-9d49-11eb-882e-010a3c2884bb.png">
