### ISSUE TITLE
decimal comma

### ISSUE THREAD

**Issue by tpapp** [JuliaData/CSV.jl#83]
Is there a way to use `CSV.jl` with a file that is delimited by `;`, and floating-point numbers use a decimal comma? A typical row looks like
```
123;M;456,78;90
```
where `456,78` is actually the floating point number `456.78`.

Or is piping through `tr , .` my best bet at the moment?

**Comment by quinnj** [comment]
This is now supported on master; `CSV.read` takes a `decimal=','` keyword argument where you can specify what to use as the decimal separator.

**Comment by sylvaticus** [comment]
Thank you, working in France it's a very appreciated feature. Still missing in the documentation hovewer (sorry, I don't know where I land when I try to click "Edit on github" in the documentation, but it seems a death end).

**Comment by nalimilan** [comment]
The link points to the page of the manual which includes the docstrings, but the docstrings themselves are in the code: https://github.com/JuliaData/CSV.jl/blob/master/src/Source.jl
