### ISSUE TITLE
Additional Error Handling with multithreaded CSV file read

### ISSUE THREAD

**Issue by tbonza** [JuliaData/CSV.jl#830]
I'm using Julia 1.6.1 to read a CSV file with `julia --threads 8` as an arg.
```julia
df = DataFrame(CSV.File(fpath, type=String, quotechar='"'))
```
Inevitably, my questionable CSV files will crash. Given that I can't make the CSV files less questionable, is there a lower level approach I can try to access or create additional error handling? Thanks!

**Comment by quinnj** [comment]
Can you clarify what kind of error you're seeing? The only real "fatal" error is when cells are incorrectly quoted, where the csv parser just really can't tell where things are supposed to be.

**Comment by tbonza** [comment]
Yes, the incorrect quotations is exactly what's happening. An example of a field that would raise this error contains several newline characters within the field.

```
"This field starts out fairly normal.


It then ends after several newline characters."
```
I've been using CSV.jl for a couple years and haven't run into similar problems when reading the CSV file without threads. I'll occasionally run into an issue where I'm able to read a file if a server has 8 threads but not 96. I'm very open to helping if I can be pointed in a direction.

**Comment by quinnj** [comment]
Hmmmm, can you confirm which version of CSV.jl you're using? In the most recent (0.9 I believe), if multithreading can't determine the correct rows when chunking up a file, it should switch over to single-threaded parsing. You can run `CSV.File(....; debug=true)` to see a little more info while things are parsing. As a hard work-around, you can always pass `CSV.File(...; threaded=false)` to make sure no multi-threading is used.

In your example you gave, that's not exactly what I was referring to. I mean cases where you have a field like `"This is a bad field,next field, next field,oops we never had a closing double quote character for that first field,next field`.

**Comment by tbonza** [comment]
Checking my manifest, it's `version = "0.8.4"`. I'll do an upgrade either today or Monday and see if the issue goes away then write back

**Comment by quinnj** [comment]
(sorry for the delayed response) No, nothing has changed recently with regards to fatal error here. Is there any way you can share the erroring file with me so I can take a look? Even if just privately to my email, I'm happy to keep private data private. I'm currently in the middle of a large internals refactor (#837), so any help would be great as we look to improve things.

**Comment by tbonza** [comment]
I was able to generate an example file with anonymized data but the file isn't large enough to reproduce the error. The first row is the exact format of the row which crashes when using multiple threads but works without an issue on a single thread. Hopefully this can move things along, happy to make additional changes. See https://github.com/tbonza/CSV.jl/commit/01f6cb2c9a34d9dd713586b3cc31dc0a893368e8

**Comment by quinnj** [comment]
The internal algorithms around quote detection and the interaction with multithreaded parsing has been greatly improved on the `main` branch over the last few months. In particular, it won't "crash" any more if it cant' detect hte right chunks, but will instead fallback to single-threaded parsing. So going to mark this as closed since I think the situation is, on all accounts, better now.

**Comment by ym-han** [comment]
fyi I'm getting issues like the following when reading in a tsv file, and when julia has been started with multiple threads. Reading the tsv with Julia started with just 1 thread, however, is fine.

This is on a unix machine on a SLURM cluster.

```
julia> reddit_data = CSV.read(PATH_CLEANED_REDDIT_TRAIN_TSV, DataFrame, delim='\t')
┌ Warning: thread = 21 warning: only found 5 / 6 columns around data row: 116447. Filling remaining columns with `missing`
└ @ CSV ~/.julia/packages/CSV/jFiCn/src/file.jl:578
┌ Warning: thread = 9 warning: only found 5 / 6 columns around data row: 55452. Filling remaining columns with `missing`
└ @ CSV ~/.julia/packages/CSV/jFiCn/src/file.jl:578
ERROR: TaskFailedException

    nested task error: thread = 8 fatal error, encountered an invalidly quoted field while parsing around row = 62094, col = 2: ""1. I feel like you're kind of cheating on the third one. It seems more like you are arguing that it is reasonable to dismiss Clinton because she is fairly hawkish, not simply because of that one vote. That vote is really a symbol of what you see as the underlying issue, rather than the issue itself.
    ", error=INVALID: OK | QUOTED | EOF | INVALID_QUOTED_FIELD , check your `quotechar` arguments or manually fix the field in the file itself
```

**Comment by quinnj** [comment]
@ym-han, thanks for the report. Can you confirm which version of CSV.jl you're using? Also, is there any way you can setup the file to be shared, even if just privately with me somehow? I'd love to be able to get it myself and try to recreate the scenario where it's failing for you to see if there's anything we can do automatically in CSV.jl to avoid the error.

**Comment by ym-han** [comment]
] pkg status CSV tells me that I'm on 0.10.4.

A copy of the tsv can be found here: https://drive.google.com/file/d/1FHQ1XoBYwQMliHHxkqqViHasAIn-oByJ/view?usp=sharing

It could be that something about my env is bonked; I haven't tried running it with a fresh env yet.

**Comment by quinnj** [comment]
Thanks; could you also share how many threads your julia session starts with when seeing the error?

**Comment by ym-han** [comment]
I just replicated the error with 2 threads; hopefully that helps (I can't remember the exact number the last time I did it).
