### ISSUE TITLE
Error when reading CSV files. 

### ISSUE THREAD

**Issue by FedX-sudo** [JuliaData/CSV.jl#832]
Whenever I read a CSV file  via `CSV.read("data.csv")` I run into the error

` ERROR: LoadError: UndefVarError: CSV not defined `

I ran the `Pkg test CSV `command and this is the result: 

```
Test Summary:                  | Pass  Fail  Total
     CSV                       | 1830     1   1831
     CSV.File                  | 1628         1628
     CSV.write                 |   92     1     93
     PooledArrays              |   14           14
     LazyStringVector          |    7            7
     CSV.Rows                  |   37           37
     CSV.detect                |    8            8
     CSV.findrowstarts!        |    4            4
     CSV.promote_typecode      |    2            2
     CSV.File with select/drop |   38           38

ERROR: LoadError: Some tests did not pass: 1830 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/fedx/.julia/packages/CSV/CJfFO/test/runtests.jl:13
ERROR: Package CSV errored during testing
```

**Comment by quinnj** [comment]
You have to make sure you do `using CSV, DataFrames` before you call `CSV.read("data.csv", DataFrame)`.

**Comment by FedX-sudo** [comment]
I did make sure I was `using DataFrames` however, I did not realize that  CSV reading required the DataFrame part, is that a predefined variable?

**Comment by quinnj** [comment]
CSV doesn't require DataFrames.jl. When call `CSV.read(filename, sink)`, however, you're required to provide a 2nd argument of the kind of thing you want to read the csv file into. Alternatively, you can just call `f = CSV.File(filename)` and you get a `CSV.File` object returned, which can be useful for most people. You can iterate rows like:
```julia
for row in CSV.File(file)
    # so something with row.col1, for example
end
```
Or access entire columns like:
```julia
col1 = f.col1
```

**Comment by FedX-sudo** [comment]
Ok, I am sending the output into an empty data frame, via

```
df = DataFrame()
CSV.read("data.csv", df)
```

**Comment by quinnj** [comment]
You need to load the CSV.jl package first. When you start the `julia` program, the CSV.jl package isn't loaded yet, so you need to do something like:
```julia
using CSV, DataFrames
df = CSV.read("data.csv", DataFrame)
```
Note that for the 2nd argument to `CSV.read`, you pass `DataFrame`, which is a _function_ that tells the CSV package how to read the csv file into.

**Comment by FedX-sudo** [comment]
Ok, I did load the package in the last program, but the issue was I needed to define the df variable using CSV.read. Sorry for taking up your time and thank you so much for your help!

**Comment by quinnj** [comment]
No problem; happy to help
