### ISSUE TITLE
How to use `CSV.Rows()` and `CSV.Rows2`?

### ISSUE THREAD

**Issue by jankap** [JuliaData/CSV.jl#833]
Dear all, I'm trying to do row by row file processing with `CSV.Rows()`. I can iterate through the file's rows and also print the contents. However, I can't modify them, because no `setindex()` is implemented. 
Therefore, I try to cast a row into some other Tables.jl compatible interface. However, no functions seem to support CSV.Rows2 as parameter?

What I'd like to do is to modify the buffer line by line and save it into another CSV file. It must be line by line because the file probably does not fit into memory. I'm going to try out CSV.Chunks later when I got this working.

```
using CSV
using DataFrames
using Tables

file = """
"5674012";"530489692";"batch_145322";"10/31/2019 15:00:13"
"5674012";"530489702";"batch_145323";"10/31/2019 15:00:32"
"5674012";"530489728";"batch_145327";"10/31/2019 15:01:56"
"""


io = IOBuffer(file)
rows = CSV.Rows(io, header=false, delim=";", type=String, reusebuffer=true);

for row in rows
    for iCol = 1:length(row) # manually looping, since documentation states there is no column iterator
        # row[iCol] = row[iCol] * "_test"; # error
    end
    # alternative idea: stream the whole row into something else as proposed by documentation, but I don't find compatible interfaces
    # rowConverted = Tables.table(row); # error, no abstract matrix
    # rowConverted = DataFrame(row); # error, CSV.Row2 iterates string values
    # rowConverted = Matrix(row); # error, no method matching

   # write modified buffer back to a file
   # CSV.write("outfile.txt", rowConverted, delimiter=";")
end
```

Maybe I don't understand the purpose of `CSV.Rows()`. Would you please be so kind and help me out here?

Thanks!

**Comment by quinnj** [comment]
`CSV.Rows` is indeed used for processing delimited files w/ as small a footprint as possible. But you're also correct that `CSV.Row2` is immutable. I would probably approach this problem with something like:
```julia
rows = CSV.Rows(...) |>
    TableOperations.map(row -> (; (k => v * "_test" for (k, v) in pairs(row))...)) |>
    CSV.write("outfile.txt")
```
