### ISSUE TITLE
Reading Transposed CSV with unequal rows reads only minimum size of data

### ISSUE THREAD

**Issue by shakisparki** [JuliaData/CSV.jl#834]
### Data (test.txt)
a, 0.1, 0.2, 0.3
b, 0.4

### Code
`julia> f = CSV.File(read("test.txt"), transpose=true, normalizenames=true)`
`1-element CSV.File{false}:`
` CSV.Row: (a = 0.1, b = 0.4)`

### Issue
 Output ignores remaining data in first row instead of reading all data for row 1, and row 2 while reporting "missing" data in row 2.

**Comment by quinnj** [comment]
Fixed in #837
