### ISSUE TITLE
quotechar = '\0' into documentation

### ISSUE THREAD

**Issue by jesseseeem** [JuliaData/CSV.jl#836]
I just had an extremely helpful response on Julia Discourse from @quinnj  regarding a fatal error while reading in a big messy dataset: 
https://discourse.julialang.org/t/fatal-error-while-reading-in-messy-data-using-dataframes-csv/61314

I think it would be really useful to have some option like this, or quotechar = false, etc., to tell CSV.read to not interpret any characters as quoted/escaped fields. If quotechar = '\0' is already the canonical solution, it would be great if this were listed more prominently in the help files and documentation. 
Thanks on all the hard work on an awesome package!

**Comment by quinnj** [comment]
Ok, PR is up: https://github.com/JuliaData/CSV.jl/pull/848. With that PR, you would just pass `quoted=false` to have parsing ignore any quoting.
