### ISSUE TITLE
Feature Request: Custom parsing functions without overloading Base.parse

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaData/CSV.jl#838]
I currently need to read types such as `Tuple` from a CSV file. For example, consider the following mockup
```
id,pos,f
5,"(5, 10)",0.15
```
Usually such non-scalar fields would be split across columns, but each column corresponds to a field of a user-defined struct (so it can be passed in to a constructor). It's currently impossible to pass custom parsing functions, and instead there's no alternative to overloading `Base.parse`. Such type-piracy is better avoided, especially since this goes in a package (https://github.com/JuliaDynamics/Agents.jl/pull/499)

Can it be made possible to pass functions into the `types` keyword argument? For example `CSV.Rows(filename; types = [Int, mytupleparsingfunction, Float64)`

**Comment by quinnj** [comment]
So just to clarify, you don't need to type-pirate if you're trying to parse a Tuple of something; just create a custom wrapper type like `struct MyTuple; end`, then overload `Base.tryparse(::Type{MyTuple}, str::String) = ...` and return a tuple from there.
