### ISSUE TITLE
How to use `CSV.read()`

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaData/CSV.jl#843]
Hey folks, someone mentioned here: that `csv.read()` has been updated which I see in the source code: https://github.com/JuliaData/CSV.jl/blob/fc209672d0a894954c5dc1e0835e0426b9d2925c/src/CSV.jl#L41

However, when I run it without a sink, I do not get an error. Any ideas as to why?

My code: 
```
@btime C = CSV.read("programming_languages.csv");
```

```
  [336ed68f] CSV v0.8.5
```

**Comment by quinnj** [comment]
Are you by chance using Juno/atom IDE? There have been issues with "baked in" old package versions.

**Comment by logankilpatrick** [comment]
No, I am using a Jupyter notebook with Julia 1.6.0

**Comment by logankilpatrick** [comment]
In my REPL session it error's but in the Notebook with 1.6 kernel, it is fine

**Comment by logankilpatrick** [comment]
![Screen Shot 2021-06-12 at 6 26 22 PM](https://user-images.githubusercontent.com/35577566/121791086-b3200b80-cbab-11eb-8467-68ca86498c23.png)

**Comment by logankilpatrick** [comment]
Fascinating, it looks like my Jupyter Env (same kernel as my REPL) is using:
```
  [336ed68f] CSV v0.6.2
```
Any suggestions as to why that would be? I thought they would have to be the same

**Comment by logankilpatrick** [comment]
Ah, nvm, it is pointing to the local Project file : )
