### ISSUE TITLE
Error when file is not found

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#859]
The message in
https://github.com/JuliaData/CSV.jl/blob/0eaacb4c4d5787a5186dac8edf523ee9052db27f/src/context.jl#L179
is reported to be misleading by the users.

Maybe we could split the `isfile` condition to a separate test and if file is not found report that it was not found? (users think that "valid file" means that file exists but did not pass validation)

**Comment by nickrobinson251** [comment]
Do we need to split out the `isfile` condition or just change the wording in this one check (e.g. to `"No such file \"$source\"")?

i.e. does this error ever get triggered except for non-existent filepaths? I tried to trigger it by passing in various silly arguments to `CSV.File` (e.g. `md` files, `xml` files, `Vector{UInt16}`) and couldn't trigger it -- either i hit a different error of reading succeeded (turn's out CSV.jl will read markdown somewhat successfully!)

**Comment by bkamins** [comment]
Indeed `isfile` will throw an error if something that is not a file is passed to it. However, I think we could consider adding a restriction that we accept `AbstractString` here (and then throw "file not found") or on any other type throw an error?

The issue is that `isfile` calls `stat` which has the following methods:
```
julia> methods(stat)
# 7 methods for generic function "stat":
[1] stat(s::IOStream) in Base at iostream.jl:57
[2] stat(fd::Base.Libc.WindowsRawSocket) in Base.Filesystem at stat.jl:79
[3] stat(path::AbstractString) in Base.Filesystem at stat.jl:80
[4] stat(fd::RawFD) in Base.Filesystem at stat.jl:83
[5] stat(fd::Integer) in Base.Filesystem at stat.jl:85
[6] stat(f::Base.Filesystem.File) in Base.Filesystem at filesystem.jl:246
[7] stat(path...) in Base.Filesystem at stat.jl:109
```
And I am not sure all of them are properly handled later by `CSV.File`, e.g. is this expected:
```
julia> CSV.File(1)
0-element CSV.File{false}
```
?

**Comment by nickrobinson251** [comment]
> we could consider adding a restriction that we accept AbstractString here

I think this would break `FilePathsBase.AbstractPath`, which are currently supported due to the lack of type constraints (or require us adding a FilePathsBase dependency)

**Comment by bkamins** [comment]
I am flexible here - maybe even `CSV.File` supports all that `stat` supports - @quinnj will know hopefully.

**Comment by quinnj** [comment]
How about https://github.com/JuliaData/CSV.jl/pull/863?
