### ISSUE TITLE
add AbstractVecOrMat method to CSV.write

### ISSUE THREAD

**Issue by stevengj** [JuliaData/CSV.jl#861]
It would be nice to add a method
```jl
CSV.write(file, x::AbstractVecOrMat) = CSV.write(file, Tables.table(x), writeheader=false)
```
for convenience (see e.g. https://stackoverflow.com/questions/52900232/export-an-array-to-a-csv-file-in-julia). 

(Until https://github.com/JuliaData/Tables.jl/issues/243 is fixed, you could only support `AbstractMatrix` with the method as written above; `AbstractVector` currently requires a `reshape` call or wrapping in a named tuple ala `(x=x,)`.)

**Comment by quinnj** [comment]
Tables.jl just tagged a new 1.5 release with the fix; the problem with adding a convenience method is the `::Vector` case becomes ambiguous with many common table-types that are `Vector{<:AbstractRow}`, where each element is treated as a row. I think we'll still need to require users to call `CSV.write(file, Tables.table(vec))`.
