### ISSUE TITLE
Columns with mixed data types

### ISSUE THREAD

**Issue by IljaK91** [JuliaData/CSV.jl#88]
I have a csv with a column that mainly has integers but also some floats. Going ahead without specifying any types, I get the following error:

```
CSV.CSVError("error parsing a `Int64` value on column 21, row 130; encountered '.'")
in #read at base\<missing>
in #read at base\<missing>
in #read#30 at CSV\src\Source.jl:302
in #stream!#5 at DataStreams\src\DataStreams.jl:151
in stream! at DataStreams\src\DataStreams.jl:187
in streamto! at DataStreams\src\DataStreams.jl:173
in streamfrom at CSV\src\Source.jl:195
in parsefield at CSV\src\parsefields.jl:107
in parsefield at CSV\src\parsefields.jl:127
in checknullend at CSV\src\parsefields.jl:56
```

It seems to me that the standard read command should catch that case when columns have some integers and some floats. Is there a way to still read it without specifying a type for each column?

Thanks a lot

**Comment by quinnj** [comment]
There isn't currently a way, but we could probably support the Int64=>Float64 case.

**Comment by IljaK91** [comment]
This here does the trick, but should be still not necessary in my opinion, at least in the case Int64 => Float64

`df1 = CSV.read(file; types=Dict(21=>Float64))`

**Comment by quinnj** [comment]
Hmmmm.....I've been noodling on this all week and honestly I'm not sure this will ever be a possibility. There's just not an easy way to switch column types like this and keep performance. We do now have the `CSV.validate(file)` function, which can be run on a file beforehand that will avoid allocation and give an informative error if values can't be parsed according to their detected type. Between that and the fact that you can always manually specify the column types, I think that's enough of a solution here.
