### ISSUE TITLE
re-exporting InlineString[X] types

### ISSUE THREAD

**Issue by bkamins** [JuliaData/CSV.jl#887]
I think CSV.jl should re-export `InlineString[X]` types. Now only `InlineString` is exported.
This causes very long type signatures, see: https://github.com/JuliaData/DataFrames.jl/pull/2865/files

**Comment by bkamins** [comment]
see also https://github.com/JuliaData/WeakRefStrings.jl/issues/85

**Comment by quinnj** [comment]
Yeah, I agree we should re-export the `StringX` names
