### ISSUE TITLE
Vector of inputs enhancements

### ISSUE THREAD

**Issue by quinnj** [JuliaData/CSV.jl#891]
- [ ] at least support appending columns where one may be `Vector{T}` and another may be `Vector{Union{Missing, T}}`; may need additional support in SentinelArrays.jl for this
- [ ] support the automatic addition of a "partition" column; i.e. the "name" of each file would be a constant valued column for each partition

**Comment by mahiki** [comment]
The things I do manually to read partitioned paths (Spark or Redshift style, with `<column>=<partition_value>` elements of an s3 key or file path:

```jl
using AWSS3, FilePathsBase, Pipe

dataset_root = "s3://muh-bucket/datasets/csv/example_customer_dataset"

fileslist = @pipe walkpath(S3Path("$dataset_root")) |>
    collect |>
    filter(x -> extension(x) == "csv", _)

partition_regex = r"/(\w+?)=([\w-]+?)/"

partitions = @pipe fileslist |>
    eachmatch.(partition_regex, convert.(String, _), overlap = true)

# and here I just hack it together manually, I haven't figured out a nice way to get all the nested partitions
```

From that point I imagine best would be grouping the datafile paths into vectors for each associated set of partition key/values. That way we can pass a vector of csv file paths (or s3 keys) to CSV.File.

It seems like something like this for a `date` and `category` partitioned dataset could organize the files for reading and appending static columns:

```jl
Dict(
[p"s3://bucket/<path>/000.csv", p"s3://bucket/<path>/001.csv"] => [["date", "2021-05-01"], ["category", "apparel"]]
[p"s3://bucket/<path>/003.csv", p"s3://bucket/<path>/004.csv"] => [["date", "2021-05-02"], ["category", "apparel"]]
...
[p"s3://bucket/<path>/051.csv", p"s3://bucket/<path>/052.csv"] => [["date", "2021-05-25"], ["category", "sporting_goods"]]
```

**Comment by quinnj** [comment]
Implemented in https://github.com/JuliaData/CSV.jl/pull/920
