### ISSUE TITLE
Problems with type conversions in CSV 0.9.x

### ISSUE THREAD

**Issue by pb866** [JuliaData/CSV.jl#901]
After upgrading from CSV 0.8.5 to CSV 0.9.x and reading
[this file](https://github.com/JuliaData/CSV.jl/files/7160974/CPro_Lidar_Altitudes_m.txt), 
the following code does not work anymore on Julia 1.6.1.

Previously working:

```julia
using CSV, DataFrames
CSV.read("CPro_Lidar_Altitudes_m.txt", DataFrame, type = Float32)
CSV.read("CPro_Lidar_Altitudes_m.txt", DataFrame, types = Dict(:CPro => Float64, :CLay => Float32))
```

Erroring on CSV 0.9.x:

```julia
using CSV, DataFrames
CSV.read("CPro_Lidar_Altitudes_m.txt", DataFrame, types = Float32)
CSV.read("CPro_Lidar_Altitudes_m.txt", DataFrame, types = Dict(:CPro => Float64, :CLay => Float32))
```

Work-around for first example:

```julia
using CSV, DataFrames
CSV.read("CPro_Lidar_Altitudes_m.txt", DataFrame, types = Dict(:CPro => Float32))
```

1. I can't specify `Float32` anymore with `type` (or `types`), which was previously working. A work-around is to specify `Float32` for specific columns with a `Dict`, but a setting of `Float32` as default type should work as well.
2. Previously, I could pass column names in a Dict for type conversions that did not exist in the actual table. That stopped working. While the new behaviour is much cleaner, the old behaviour could be handy, when there were different versions of a table with slightly different column names, e.g. `speed (m/s)` or `speed (mps)`. With the old behaviour, one could load the different versions of a column name and ensure the type conversion for every version of a file works with very compact code and not having to find out about the version of the tabular data.

**Comment by quinnj** [comment]
Could you share hte error stacktraces you're seeing in the 1) example?

**Comment by pb866** [comment]
Sorry, I forgot about that. Full disclosure, I'm on a Mac:

```
julia> CSV.read("CPro_Lidar_Altitudes_m.dat", DataFrame, type = Float32)
ERROR: bad column type: Float32)
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] parserow
   @ ~/.julia/packages/CSV/eB98W/src/file.jl:688 [inlined]
 [3] parsefilechunk!(ctx::CSV.Context, pos::Int64, len::Int64, rowsguess::Int64, rowoffset::Int64, columns::Vector{CSV.Column}, #unused#::Type{Tuple{}})
   @ CSV ~/.julia/packages/CSV/eB98W/src/file.jl:596
 [4] CSV.File(ctx::CSV.Context, chunking::Bool)
   @ CSV ~/.julia/packages/CSV/eB98W/src/file.jl:267
 [5] File
   @ ~/.julia/packages/CSV/eB98W/src/file.jl:223 [inlined]
 [6] #File#23
   @ ~/.julia/packages/CSV/eB98W/src/file.jl:219 [inlined]
 [7] read(source::String, sink::Type; copycols::Bool, kwargs::Base.Iterators.Pairs{Symbol, DataType, Tuple{Symbol}, NamedTuple{(:type,), Tuple{DataType}}})
   @ CSV ~/.julia/packages/CSV/eB98W/src/CSV.jl:66
 [8] top-level scope
   @ REPL[9]:1

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by pb866** [comment]
I also noticed, columns with strings are saved as `WeakRefStrings.String` not `String`, which messes up a lot of my functions, which check for a `Vector{String}` and I would have to rewrite the code to check for a `Vector{<:AbstractString}`:

```julia
shell> cat strings.txt
String
ABC-1234
DEF-5678
GHI-0000

julia> data = CSV.read("strings.txt", DataFrame)
3×1 DataFrame
 Row │ String
     │ String15…
─────┼───────────
   1 │ ABC-1234
   2 │ DEF-5678
   3 │ GHI-0000

julia> typeof(data.String)
Vector{WeakRefStrings.String15} (alias for Array{WeakRefStrings.String15, 1})

julia> typeof(data.String) <: Vector{<:String}
false

julia> typeof(data.String) <: Vector{<:AbstractString}
true
```

**Comment by quinnj** [comment]
As noted in the [release announcement](https://discourse.julialang.org/t/ann-csv-jl-0-9-release/67844), the new `StringX` types are the default for efficiency reasons; they avoid excessive GC pressure vs. regular `String`, which can make a big difference for large files.

This is configurable though, and all you need to do is `CSV.read(..., DataFrame; stringtype=String)` to read string columns as plain `String`.

**Comment by pb866** [comment]
Thanks a lot for the clarification. That helped. I've overlooked that announcement. I usually just check the release page on GitHub, the official documentation page, and any files like News.md as done for Julia itself. Changes are usually not obvious from only a list of commits. Probably something that could be added/changed in the future, so people don't have to scan different sources to find out about updates. Overall, really great package though.  
And yes, I have seen performance increases of a factor of 2 for some large files with the default string type, that's good.

**Comment by quinnj** [comment]
Alright, there were a few different things going on in this issue, but a fix (and accompanying explanations) are up: https://github.com/JuliaData/CSV.jl/pull/902
