### ISSUE TITLE
Columns with missing data are filled with stale data using CSV.Rows

### ISSUE THREAD

**Issue by Mrbigmatt** [JuliaData/CSV.jl#903]
When importing the attached file with CSV.Rows and iterating through the rows, the column with missing data is filled with the previous row's data. CSV.File seems to import this file correctly. This is with CSV.jl 0.9.2.

[test.csv](https://github.com/JuliaData/CSV.jl/files/7166408/test.csv)

**Comment by quinnj** [comment]
Thanks for reporting! Unfortunate bug from a recent refactoring; fix is up: https://github.com/JuliaData/CSV.jl/pull/904.
