### ISSUE TITLE
Incorrect BigFloat read

### ISSUE THREAD

**Issue by zmoitier** [JuliaData/CSV.jl#916]
I have a file `tmp.csv` exactly containing
```
value
0.44311945001372019574271437679879349172
```
Then I read this file using
```julia
df = CSV.read("tmp.csv", DataFrame; types=BigFloat)
```
Then if I compare the true value with the read one I get
```julia
julia> BigFloat("0.44311945001372019574271437679879349172")
0.4431194500137201_957427143767987934917199999999999999999999999999999999999999978
julia> df.value[1]
0.4431194500137201_61951624731955234892666339874267578125
```
The two number start being different where I have put the underscore, it is like the number was read as a Float64 instead of a BigFloat.

---
- Occur with Julia `v1.6.3`, CSV `v0.9.4`, and DataFrames `v1.2.2`.

**Comment by quinnj** [comment]
Thanks for reporting @zmoitier! The issue is actually in the Parsers.jl code for high-precision floats; a fix is proposed here: https://github.com/JuliaData/Parsers.jl/pull/91.

**Comment by zmoitier** [comment]
Great! Thank you @quinnj.
