### ISSUE TITLE
buffer_to_tempfile for Gzip stream - multiple tempfiles, one not cleared up

### ISSUE THREAD

**Issue by kcajf** [JuliaData/CSV.jl#917]
If I read a CSV from a gzip-encoded stream (e.g. an IOStream), with `buffer_to_tempfile=true` (default), two tempfiles are created. One contains the compressed bytes read straight from the stream, and the other contains the uncompressed bytes.

The immediate issue is that first file isn't cleaned up after parsing. In this code, if the buffer is detected as being gzip-encoded, `tfile` gets overwritten and only the second value of `tfile` is passed up the call chain for removal after parsing:
https://github.com/JuliaData/CSV.jl/blob/main/src/utils.jl#L213

Beyond that, I wonder if we could avoid creating two tempfiles? Could the original stream be detected as being gzip-encoded, and decompressed (as a stream) directly into a tempfile?

**Comment by quinnj** [comment]
Thank you @kcajf for reporting! Your analysis is spot on. A fix is proposed: https://github.com/JuliaData/CSV.jl/pull/922
