### ISSUE TITLE
null="-" on Integer columns produces zeros

### ISSUE THREAD

**Issue by lbilli** [JuliaData/CSV.jl#92]
This data file
```
x,y
1,2
-,4
```
when processed by `CSV.read(..., null="-")` produces `Nullable{Int64}` columns with `0` instead of `#NULL`.
```
│ Row │ x │ y │
├─────┼───┼───┤
│ 1   │ 1 │ 2 │
│ 2   │ 0 │ 4 │
```
The behavior looks otherwise correct for non-integer types: e.g. `Float` or `String`.

**Comment by cjprybol** [comment]
Thanks for the report! I'm not sure why this isn't working. [`detecttype` checks if the field is null before trying to parse the field as an `Int`](https://github.com/JuliaData/CSV.jl/blob/master/src/io.jl#L181). I'm working on adding some requested features into the parser, I'll make sure to include a fix and test for this before opening the pull request

**Comment by quinnj** [comment]
Thanks for the report; just pushed a fix to master.
