### ISSUE TITLE
Failed to precomplile CSV to 

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/CSV.jl#93]
I installed CSV using Pkg25 (instead of Pkg) and when I run using CSV it gave the below error. I have no idea how to fix it. 

I am running Windows 10 - Julia 0.6 - Juno

_INFO: Precompiling module CSV.
WARNING: 
Module Compat with uuid 59704903181311 is missing from the cache.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: 
Declaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:

 [1] 
_require
(::
Symbol) at .\loading.jl:448
 [2] require(::Symbol) at .\loading.jl:398
 [3] include_from_node1(::String) at .\loading.jl:569
 [4] include(::String) at .\sysimg.jl:14
 [5] 
anonymous at .\<missing>:2
while loading C:\Users\dzj\.julia\v0.6\CSV\src\CSV.jl, in expression starting on line 4_

**Comment by cjprybol** [comment]
I don't know what is causing this, but I don't think it's related to CSV. Another user reported a similar uuid issue in a different package [here](https://github.com/JuliaStats/DataArrays.jl/issues/286).

Could you try running `Pkg.update()` and then removing the precompiled caches with `rm ~/.julia/lib/v0.6/*.ji`. After that run `using Compat, CSV` and see that works.

**Comment by quinnj** [comment]
Yeah, sometimes things can get in a weird state, particularly if you use different versions of Julia, change package source code, etc. The best option is to 1) delete your `.julia/lib/v0.X` directory, 2) restart julia, and 3) load the package again.
