### ISSUE TITLE
CSV.read fail with column of BigFloat

### ISSUE THREAD

**Issue by zmoitier** [JuliaData/CSV.jl#938]
Take a file `test.csv` containing 
```csv
val
0.05104619901579189669824087649217258663054956230471330488402001033936318763639466
0.9943228419955072710755409695069762391445782640285798257467039551335684069690842
```
and if we try to read it, we get
```julia
julia> using CSV, DataFrames
julia> y = CSV.read("test.csv", DataFrame; types=Dict(:val => BigFloat))
2×1 DataFrame
 Row │ val                               
     │ BigFloat                          
─────┼───────────────────────────────────
   1 │ 0.994322841995507271075540969506…
   2 │ 0.994322841995507271075540969506…
```
as we can see it just repeated the last value. This bug seems to be in `Parsers.jl` because it does occur with `Parsers@2.1.1` but not with `Parsers@2.1.0`. However, I did not manage to reduce this issue to just `Parsers.jl`.

---

Additional information:
- This bug does not occur if there is only one value in the column.
- It does occur for two or more values in the column.
- The values do not matter as they can be chosen randomly, it seems that the bug occur each time.
- Julia `v1.6.3`; CSV `v0.9.10`; DataFrames `v1.2.2`.

**Comment by quinnj** [comment]
Fixed via https://github.com/JuliaData/Parsers.jl/commit/04f46b5da890fc26a6729e2436c18a9ec774be10; a new Parsers.jl release has been tagged, so once that goes through the registry, you'll just need to update Parsers.jl.

**Comment by zmoitier** [comment]
Great, thank you @KristofferC and @quinnj.
