### ISSUE TITLE
    StackOverflowError when combining csv, hybridarrays and symbolics in 1.7 

### ISSUE THREAD

**Issue by judober** [JuliaData/CSV.jl#946]
When using `CSV`, `HybridArrays` and `Symbolics` in combination with 1.7.0, I get an `StackOverflowError()`.
MWE (thanks @lawless-m):
```
using CSV, Symbolics, HybridArrays

function test1()
    CSV.File(""; delim = "; ", types = Float64)
end

test1()
```

The code works in 1.6.4.

See also [Discourse](https://discourse.julialang.org/t/stackoverflowerror-when-compining-csv-hybridarrays-and-symbolics-in-1-7/72652)

Edit: Sorry for the bad title

**Comment by quinnj** [comment]
Hmmm....I'm not sure what you're expecting `CSV.File(""; ...)` to do? it's not a file or valid csv data?

**Comment by lawless-m** [comment]
> Hmmm....I'm not sure what you're expecting `CSV.File(""; ...)` to do? it's not a file or valid csv data?

Are you expecting 1000s of lines of error messages and a crash ? Which doesn't happen without the presence of `using HybridArrays, Symbolics`

It is the same if it has a file, so taking the file out makes the MWE even more M than needing the file

**Comment by quinnj** [comment]
This is being tracked in the JuliaLang/julia repo where it will be fixed: https://github.com/JuliaLang/julia/issues/43357
