### ISSUE TITLE
CSV.write strange behaviour

### ISSUE THREAD

**Issue by animBreedTools** [JuliaData/CSV.jl#978]
Hi All

Julia v1.5.1, CSV v0.8.5

I have a data of 5K*0.5M.
I can write out part of it (first 10 columns, for example).

`CSV.write("XXXX",convert(DataFrame,XXX[:,1:10]),header=false)`

When i go for the full data, I get:

> ArgumentError: column name :newline not found in the data frame

This is not all... When I try to write **another data** 200K*5, in the same session just ignoring the above, I get UndefVarError: x..... not defined.

UndefVarError: x22727 not defined

> Stacktrace:
>  [1] writerow(::Array{UInt8,1}, ::Base.RefValue{Int64}, ::Int64, ::IOStream, ::Tables.Schema{(:id, :chr, :bp, :M, :cM),NTuple{5,Any}}, ::DataFrameRow{DataFrame,DataFrames.Index}, ::Int64, ::CSV.Options{UInt8,UInt8,Nothing,Tuple{},CSV.var"#60#63"}) at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:342
>  [2] #66 at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:215 [inlined]
>  [3] (::CSV.var"#73#74"{CSV.var"#66#67"{Bool,Bool,Tables.Schema{(:id, :chr, :bp, :M, :cM),NTuple{5,Any}},DataFrames.DataFrameRows{DataFrame},CSV.Options{UInt8,UInt8,Nothing,Tuple{},CSV.var"#60#63"},NTuple{5,Symbol},Int64,Int64,Array{UInt8,1}}})(::IOStream) at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:279
>  [4] open(::CSV.var"#73#74"{CSV.var"#66#67"{Bool,Bool,Tables.Schema{(:id, :chr, :bp, :M, :cM),NTuple{5,Any}},DataFrames.DataFrameRows{DataFrame},CSV.Options{UInt8,UInt8,Nothing,Tuple{},CSV.var"#60#63"},NTuple{5,Symbol},Int64,Int64,Array{UInt8,1}}}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:325
>  [5] open at ./io.jl:323 [inlined]
>  [6] with at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:278 [inlined]
>  [7] #write#65 at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:205 [inlined]
>  [8] write(::String, ::DataFrame; delim::Char, quotechar::Char, openquotechar::Nothing, closequotechar::Nothing, escapechar::Char, newline::Char, decimal::Char, dateformat::Nothing, quotestrings::Bool, missingstring::String, transform::CSV.var"#60#63", bom::Bool, append::Bool, writeheader::Nothing, partition::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:191
>  [9] write(::String, ::DataFrame) at /usr/home/qgg/emre/.julia/packages/CSV/Zl2ww/src/write.jl:152
>  [10] top-level scope at In[23]:1
>  [11] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091

**Comment by quinnj** [comment]
Thanks for the report; this has been fixed in the CSV.jl 0.9.3 release (based on issue #900), which also requires Tables.jl 1.5.2 for the full fix.
